### PR TITLE
GTI: ensure SRS gets applied to spatial filters (fixes #14301)

### LINKED ISSUE #14301: GTI driver does not seem to use SRS/MINX/MINY/MAXX/MAXY when reading a stac-geoparquet file
### What is the bug?

I am really interested in using the GTI driver to represent mosaics of STAC items/assets as raster data sources. While testing it out I have found a possible bug in the way the STAC items are filtered when the user provides the `SRS` and `MINX`/`MINY`/`MAXX`/`MAXY` open options. When the provided `SRS` does not match the CRS of the stac-geoparquet file's geometry column (always epsg:4326 unless the file has been reprojected) the GTI driver fails to find the correct assets and loads an empty dataset (all nodata?).

The workaround I have been using is to reproject the stac-geoparquet file to my target CRS with `gdal vector reproject` first, then open the reprojected file with the GTI driver (with the open options to define the extent).

Maybe the filter that runs on the parquet filter is not dealing with the user-provided SRS and extent values?

### Steps to reproduce the issue

Here are some `gdal raster info` calls that demonstrate the issue:

```bash
# use gdal raster reproject to reproject and clip a small bbox
docker run -v /tmp:/tmp ghcr.io/osgeo/gdal:alpine-normal-latest \
  gdal raster reproject \
  --dst-crs epsg:3857 \
  --bbox -11128000,4152000,-11127000,4153000 \
  GTI:/vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet \
  /tmp/reprojected_clipped.tif

# check the stats
docker run -v /tmp:/tmp ghcr.io/osgeo/gdal:alpine-normal-latest \
  gdal raster info \
  --stats \
  /tmp/reprojected_clipped.tif
```

Output:
```
Driver: GTiff/GeoTIFF
Files: /tmp/reprojected_clipped.tif
Size is 819, 819
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
...
Data axis to CRS axis mapping: 1,2
Origin = (-11128000.000000000000000,4153000.000000000000000)
Pixel Size = (1.221001221001221,-1.221001221001221)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-11128000.000, 4153000.000) ( 99d57'52.29"W, 34d55'11.61"N)
Lower Left  (-11128000.000, 4152000.000) ( 99d57'52.29"W, 34d54'45.09"N)
Upper Right (-11127000.000, 4153000.000) ( 99d57'19.95"W, 34d55'11.61"N)
Lower Right (-11127000.000, 4152000.000) ( 99d57'19.95"W, 34d54'45.09"N)
Center      (-11127500.000, 4152500.000) ( 99d57'36.12"W, 34d54'58.35"N)
Band 1 Block=819x2 Type=Byte, ColorInterp=Red
  Description = Red
  Min=0.000 Max=251.000
  Minimum=0.000, Maximum=251.000, Mean=130.225, StdDev=38.970
  Metadata:
    STATISTICS_MAXIMUM=251
    STATISTICS_MEAN=130.22465378876
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=38.970471279068
    STATISTICS_VALID_PERCENT=100
...
```

Then if you try to provide a specific SRS and extent via open options, the projection and extent match expectation but the raster appears to be all nodata (0):

```bash
docker run \
  -v /tmp:/tmp \
  ghcr.io/osgeo/gdal:alpine-normal-latest  \
  gdal raster info \
  --oo SRS=epsg:3857 \
  --oo MINX=-11128000 \
  --oo MINY=4152000 \
  --oo MAXX=-11127000 \
  --oo MAXY=4153000 \
  --stats \
  GTI:/vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet
```

Output:
```
Driver: GTI/GDAL Raster Tile Index
Files: none associated
Size is 818, 818
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
...
Data axis to CRS axis mapping: 1,2
Origin = (-11128000.000000000000000,4153000.000000000000000)
Pixel Size = (1.222521789820938,-1.222521789820938)
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-11128000.000, 4153000.000) ( 99d57'52.29"W, 34d55'11.61"N)
Lower Left  (-11128000.000, 4151999.977) ( 99d57'52.29"W, 34d54'45.09"N)
Upper Right (-11126999.977, 4153000.000) ( 99d57'19.95"W, 34d55'11.61"N)
Lower Right (-11126999.977, 4151999.977) ( 99d57'19.95"W, 34d54'45.09"N)
Center      (-11127499.989, 4152499.989) ( 99d57'36.12"W, 34d54'58.35"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Description = Red
  Minimum=0.000, Maximum=0.000, Mean=0.000, StdDev=0.000
  Metadata:
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=0
    STATISTICS_MEAN=0
    STATISTICS_STDDEV=0
    STATISTICS_VALID_PERCENT=100
...
```

Workaround: reproject parquet file to target CRS first

```bash
# use ogr2ogr to reproject the input parquet to the target CRS
docker run \
  -v /tmp:/tmp \
  ghcr.io/osgeo/gdal:alpine-normal-latest  \
  gdal vector reproject \
  --dst-crs epsg:3857 \
  /vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet \
  /tmp/reprojected.parquet

# use open options to define the SRS and extent of the reprojected data source - WORKS!
docker run \
  -v /tmp:/tmp \
  ghcr.io/osgeo/gdal:alpine-normal-latest  \
  gdal raster info \
  --oo SRS=epsg:3857 \
  --oo MINX=-11128000 \
  --oo MINY=4152000 \
  --oo MAXX=-11127000 \
  --oo MAXY=4153000 \
  --stats \
  GTI:/tmp/reprojected.parquet
```

Output:
```
Driver: GTI/GDAL Raster Tile Index
Files: none associated
Size is 818, 818
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
...
Data axis to CRS axis mapping: 1,2
Origin = (-11128000.000000000000000,4153000.000000000000000)
Pixel Size = (1.222521789820938,-1.222521789820938)
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-11128000.000, 4153000.000) ( 99d57'52.29"W, 34d55'11.61"N)
Lower Left  (-11128000.000, 4151999.977) ( 99d57'52.29"W, 34d54'45.09"N)
Upper Right (-11126999.977, 4153000.000) ( 99d57'19.95"W, 34d55'11.61"N)
Lower Right (-11126999.977, 4151999.977) ( 99d57'19.95"W, 34d54'45.09"N)
Center      (-11127499.989, 4152499.989) ( 99d57'36.12"W, 34d54'58.35"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Description = Red
  Minimum=0.000, Maximum=251.000, Mean=130.222, StdDev=38.970
  Metadata:
    STATISTICS_MINIMUM=0
    STATISTICS_MAXIMUM=251
    STATISTICS_MEAN=130.22223982401
    STATISTICS_STDDEV=38.969732922581
    STATISTICS_VALID_PERCENT=100
...
```

### Versions and provenance

I am running this on `ghcr.io/osgeo/gdal:alpine-normal-latest`:
```
$ docker run ghcr.io/osgeo/gdal:alpine-normal-latest gdal --version

GDAL 3.13.0dev-b436f3f8a3bd0e28b06778c86049d63b6ad4cdea, released 2026/04/07
```

### Additional context

Here is a notebook that shows how I am hoping to use the GTI driver with stac-geoparquet files. https://github.com/hrodmn/stac-gti-xarray/blob/cd52069c5fb3472d359c57ab51700f6a51a5b61e/demo.ipynb

### PR DESCRIPTION
**Pull request by hrodmn**
## What does this PR do?
When a user provided the open options `SRS` and `MINX/MINY/MAXX/MAXY` the spatial filter rectangles were not being transformed from the output SRS to the index layer's native SRS.
This uses the same `OGRWarpedLayer` wrapper in the case of a custom SRS being provided as is used in the auto-detection case for STAC items with projection metadata.

This ensures that the asset geometry comparisons/filters are correct if a user provides a `SRS` open option to set the GTI layer's SRS. I tested the failing examples from #14301 and now they work as expected!

## What are related issues/pull requests?
#14301 

## AI tool usage

 - [x] AI (Claude) supported my development of this PR. See our [policy about AI tool use](https://gdal.org/community/ai_tool_policy.html). Use of AI tools *must* be indicated.

## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [x] Add test case(s)
 - [x] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [x] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: Fedora 43
* Compiler: GCC 15.2.1

### CODE REVIEW

**Comment by rouault** [comment]
The SRS, MINX, MINY, MAXX, MAXY parameters have never been intented to perform on-the-fly reprojection of the feature layer, but to specify missing parameters of vector layers
The correct fix would be to make the doc clearer in that regard.

For your purpose , just do: "gdal raster reproject --dst-crs EPSG:3857 --bbox -11128000,4152000,-11127000,4153000 GTI:/vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet gti_3857.vrt", and then request on that file

**Comment by rouault** [comment]
> The SRS, MINX, MINY, MAXX, MAXY parameters have never been intented to perform on-the-fly reprojection of the feature layer, but to specify missing parameters of vector layers The correct fix would be to make the doc clearer in that regard.
> 
> For your purpose , just do: "gdal raster reproject --dst-crs EPSG:3857 --bbox -11128000,4152000,-11127000,4153000 GTI:/vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet gti_3857.vrt", and then request on that file

although I'm realizing this would cause potentially double reprojection :  tile SRS -> EPSG:4326 if STAC GeoParquet lacks PROJ extension or SRS of the first tile -> EPSG:3857.

What about the following: if  ``SRS`` is defined and m_poLayer->GetSpatialRef() != nullptr, if they differ, emit a warning like "SRS parameter is not consistent with the SRS of the vector layer. If you intend to override it without reprojection, specify SRS_BEHAVIOR=OVERRIDE. If you intend to reproject from the source layer SRS to the specified SRS, specify SRS_BEHAVIOR=REPROJECT".   This is a bit verbose but should cover all use cases and avoid ambiguities.
And if  ``SRS`` is defined and m_poLayer->GetSpatialRef() if none, keep silently the current behavior.

**Comment by hrodmn** [comment]
> What about the following: if SRS is defined and m_poLayer->GetSpatialRef() != nullptr, if they differ, emit a warning like "SRS parameter is not consistent with the SRS of the vector layer. If you intend to override it without reprojection, specify SRS_BEHAVIOR=OVERRIDE. If you intend to reproject from the source layer SRS to the specified SRS, specify SRS_BEHAVIOR=REPROJECT". This is a bit verbose but should cover all use cases and avoid ambiguities.
And if SRS is defined and m_poLayer->GetSpatialRef() if none, keep silently the current behavior.

@rouault I like that idea. Adding `SRS_BEHAVIOR` would make the meaning of `SRS` explicit. 

> For your purpose , just do: "gdal raster reproject --dst-crs EPSG:3857 --bbox -11128000,4152000,-11127000,4153000 GTI:/vsicurl/https://github.com/stac-utils/stac-geoparquet/raw/main/tests/data/naip.parquet gti_3857.vrt", and then request on that file

The GTI -> vrt approach would work well but it would be nice to be able to define the SRS/extent/resolution directly with the GTI driver similar to a VRT. I thought that GTI was an _alternative_ to VRT rather than complementary, but I see how it would make sense to keep extent/reprojection left entirely to VRT.

**Comment by rouault** [comment]
> I thought that GTI was an _alternative_ to VRT rather than complementary, but I see how it would make sense to keep extent/reprojection left entirely to VRT.

VRT has several different features gathered under the same way: either a way of capturing on-the-fly reprojection of a single raster, or being a virtual mosaic, or being a virtual pansharpened dataset, etc.  Here the suggestion is just on-the-fly reprojection of the GTI virtual mosaic output. But I'm open for that PR to be modified to implement the SRS_BEHAVIOR option and offer the wished functionality directly in the GTI driver, which makes sense

File: frmts/gti/gdaltileindexdataset.cpp [hunk 1]
```diff
@@ -2671,7 +2728,14 @@ static GDALDataset *GDALTileIndexDatasetOpen(GDALOpenInfo *poOpenInfo)
 GDALTileIndexDataset::~GDALTileIndexDataset()
 {
     if (m_poVectorDS && m_bIsSQLResultLayer)
-        m_poVectorDS->ReleaseResultSet(m_poLayer);
+    {
+        // If a warped layer was created, m_poLayer points to it rather than
+        // to the original SQL result layer, so retrieve the base layer.
+        OGRLayer *poLayerToRelease = m_poWarpedLayerKeeper
```
Comment (rouault) [inline frmts/gti/gdaltileindexdataset.cpp]: It would be cleaner IMHO to set a m_poLayerToRelease member variable at the time we run ExecuteSQL(), and remove m_bIsSQLResultLayer which becomes redundant.

We also want to explicitly run "m_poWarpedLayerKeeper.reset()" before running this part of the code  (with a code comment explaining why the order matters)

File: autotest/gdrivers/gti.py [hunk 2]
```diff
@@ -2999,9 +3004,11 @@ def test_gti_read_non_existing_source(tmp_vsimem):
 
     vrt_ds = gdal.Open(index_filename)
 
-    with gdal.config_option("GDAL_NUM_THREADS", "1"), gdaltest.error_raised(
-        gdal.CE_Failure
-    ), gdaltest.disable_exceptions():
+    with (
```
Comment (rouault) [inline autotest/gdrivers/gti.py]: python 3.8 desn't seem to like that syntax

Comment (hrodmn) [reply autotest/gdrivers/gti.py]: I think my editor autoformatted that change, reverting it now.

**Review by rouault — APPROVED** [review]
