### PR TITLE
JSON: Fix json mixed types roundtrip

### LINKED ISSUE #7336: ogr2ogr: GeoJSON with mixed property types is converted to string
Input:

`gh_51911_original.json`

```json
{
"type": "FeatureCollection",
"name": "gh_51911",
"features": [
{ "type": "Feature", "properties": { "prop0": 42 }, "geometry": { "type": "Point", "coordinates": [ 102.0, 0.5 ] } },
{ "type": "Feature", "properties": { "prop0": "astring" }, "geometry": { "type": "Point", "coordinates": [ 102.0, 0.5 ] } },
{ "type": "Feature", "properties": { "prop0": { "nested": 75 } }, "geometry": { "type": "Point", "coordinates": [ 102.0, 0.5 ] } }
]
}
```

`ogrinfo` output (partial)

```bash
prop0: String(JSON) (0.0)
OGRFeature(gh_51911):0
  prop0 (String(JSON)) = 42
  POINT (102.0 0.5)

OGRFeature(gh_51911):1
  prop0 (String(JSON)) = astring
  POINT (102.0 0.5)

OGRFeature(gh_51911):2
  prop0 (String(JSON)) = { "nested": 75 }
  POINT (102.0 0.5)
```

Command:

```bash
ogr2ogr --debug on -f GeoJSON gh_51911_translated.json gh_51911_original.json
GeoJSON: First pass: 100.00 %
GDAL: GDALOpen(gh_51911_original.json, this=0x563b09ceb480) succeeds as GeoJSON.
GDAL: QuietDelete(gh_51911_translated.json) invoking Delete()
GDAL: GDALDriver::Create(GeoJSON,gh_51911_translated.json,0,0,0,Unknown,(nil))
GDALVectorTranslate: Transferring layer NATIVE_DATA
GDALVectorTranslate: 3 features written in layer 'gh_51911'
GDAL: GDALClose(gh_51911_original.json, this=0x563b09ceb480)
GDAL: GDALClose(gh_51911/gh_51911_translated.json, this=0x563b09d228d0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

`gh_51911_translated.json`

```json
{
"type": "FeatureCollection",
"name": "gh_51911",
"features": [
{ "type": "Feature", "properties": { "prop0": "42" }, "geometry": { "type": "Point", "coordinates": [ 102.0, 0.5 ] } },
{ "type": "Feature", "properties": { "prop0": "astring" }, "geometry": { "type": "Point", "coordinates": [ 102.0, 0.5 ] } },
{ "type": "Feature", "properties": { "prop0": { "nested": 75 } }, "geometry": { "type": "Point", "coordinates": [ 102.0, 0.5 ] } }
]
}
```

### PR DESCRIPTION
**Pull request by elpaso**
Fix #7336 (only when NATIVE_DATA=TRUE)

### CODE REVIEW

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp [hunk 1]
```diff
@@ -871,10 +871,41 @@ json_object *OGRGeoJSONWriteAttributes(OGRFeature *poFeature,
             const size_t nLen = strlen(pszStr);
             poObjProp = nullptr;
             if (eSubType == OFSTJSON ||
-                (pszStr[0] == '{' && pszStr[nLen - 1] == '}') ||
-                (pszStr[0] == '[' && pszStr[nLen - 1] == ']'))
+                ((pszStr[0] == '{' && pszStr[nLen - 1] == '}') ||
+                 (pszStr[0] == '[' && pszStr[nLen - 1] == ']')))
```
Comment (rouault) [inline ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp:875]: it doesn't look to me that this extra quoting is needed

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp [hunk 2]
```diff
@@ -871,10 +871,41 @@ json_object *OGRGeoJSONWriteAttributes(OGRFeature *poFeature,
...
+                    OGRJSonParse(poFeature->GetNativeData(), &poNativeObjProp,
+                                 false);
+                    if (json_object *poProperties = OGRGeoJSONFindMemberByName(
+                            poNativeObjProp, "properties"))
+                    {
+                        if (json_object *poProperty =
+                                OGRGeoJSONFindMemberByName(
+                                    poProperties, poFieldDefn->GetNameRef()))
+                        {
+                            if (strcmp(json_object_get_string(poProperty),
```
Comment (rouault) [inline ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp:892]: I believe json_object_get_string() can return nullptr, and thus needs to be checked

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp [hunk 3]
```diff
@@ -871,10 +871,41 @@ json_object *OGRGeoJSONWriteAttributes(OGRFeature *poFeature,
...
+                                       pszStr) == 0)
+                            {
+                                poObjProp = poProperty;
+                            }
+                        }
+                    }
+                }
```
Comment (rouault) [inline ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp:899]: to avoid memeak:
```suggestion
                }
                json_object_put(poNativeObjProp);
```

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp [hunk 4]
```diff
@@ -871,10 +871,41 @@ json_object *OGRGeoJSONWriteAttributes(OGRFeature *poFeature,
...
+                            poNativeObjProp, "properties"))
+                    {
+                        if (json_object *poProperty =
+                                OGRGeoJSONFindMemberByName(
+                                    poProperties, poFieldDefn->GetNameRef()))
+                        {
+                            if (strcmp(json_object_get_string(poProperty),
+                                       pszStr) == 0)
+                            {
+                                poObjProp = poProperty;
```
Comment (rouault) [inline ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp:895]: to increase refcont, due to the below json_object_put()
```suggestion
                                poObjProp = json_object_get(poProperty);
```

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp [hunk 5]
```diff
@@ -871,10 +871,41 @@ json_object *OGRGeoJSONWriteAttributes(OGRFeature *poFeature,
...
             {
-                OGRJSonParse(pszStr, &poObjProp, false);
+                if (poFeature->GetNativeMediaType() &&
+                    strcmp(poFeature->GetNativeMediaType(),
+                           "application/vnd.geo+json") == 0 &&
+                    poFeature->GetNativeData())
+                {
+                    json_object *poNativeObjProp = nullptr;
+                    OGRJSonParse(poFeature->GetNativeData(), &poNativeObjProp,
+                                 false);
```
Comment (rouault) [inline ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp:884]: If there would be a lot of fields, doing the above parsing could potentially be costly. It could perhaps be done once in the loop

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp (hunk 1 above)
Comment (elpaso) [reply ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp:875]: Yeah, I added it for clarity but no problems to remove it.

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp (hunk 5 above)
Comment (elpaso) [reply ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp]: done

File: ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp (hunk 2 above)
Comment (elpaso) [reply ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp]: done
