### PR TITLE
gdalenhance: do not transfer statistics from input to output

### LINKED ISSUE #13298: Gdalenhance copies the statistics but it shouldn't
### What is the bug?

The gdalenhance utility enhances the contrast of raster images using histogram equalization. It means that the statistics of the output image almost evidently differ from the statistics of the source image. However, if the source raster has existing statistics then gdalenhance just copies them into the target raster. 

### Steps to reproduce the issue

Use image https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/data/int16.tif
It is a 16bit image but the max value is 255 so make a more suitable version with `gdal raster calc`

`gdal raster calc -i "A=int16.tif" --calc "A*5" -o int16-v2.tif`
Compute statistics
`gdal info int16-v2.tif --stats --of text`
See
```
Metadata:
    STATISTICS_MAXIMUM=1275
    STATISTICS_MEAN=633.825
    STATISTICS_MINIMUM=370
    STATISTICS_STDDEV=114.21556100199
    STATISTICS_VALID_PERCENT=100
```
Run gdalenhance
`gdalenhance -equalize int16-v2.tif int16-v2-eq.tif`
Run `gdal info int16-v2-eq.tif` and see the same statistics even the image is now 8bit
```
Band 1 Block=20x20 Type=Byte, ColorInterp=Gray
  Min=370.000 Max=1275.000
  Minimum=370.000, Maximum=1275.000, Mean=633.825, StdDev=114.216
  Metadata:
    STATISTICS_MAXIMUM=1275
    STATISTICS_MEAN=633.825
    STATISTICS_MINIMUM=370
    STATISTICS_STDDEV=114.21556100199
    STATISTICS_VALID_PERCENT=100
```
For seeing the correct statistics they must be re-computed
`gdal raster edit --stats int16-v2-eq.tif`

```
gdal info int16-v2-eq.tif --of text
...
Band 1 Block=20x20 Type=Byte, ColorInterp=Gray
  Min=0.000 Max=255.000
  Minimum=0.000, Maximum=255.000, Mean=127.343, StdDev=73.588
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=127.3425
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=73.587704093483
    STATISTICS_VALID_PERCENT=100
```

Maybe the statistics get copied here
https://github.com/OSGeo/gdal/blob/7c38f3f9027b0c6368abb9adb8c6387daead1c4f/apps/gdalenhance.cpp#L714

### Versions and provenance

GDAL 3.12.0dev-4947e350c1 on Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13298

### CODE REVIEW

File: apps/gdalenhance.cpp [hunk 1]
```diff
@@ -713,7 +714,10 @@ CPLErr WriteEnhanced(GDALDatasetH hDataset, int **papanLUTs, int nLUTBins,
         /* ---------------------------------------------------------------- */
         /*      copy over some other information of interest.               */
         /* ---------------------------------------------------------------- */
-        poVRTBand->CopyCommonInfoFrom(poSrcBand);
+        poVRTBand->SetColorInterpretation(poSrcBand->GetColorInterpretation());
+        if (strlen(poSrcBand->GetDescription()) > 0)
+            poVRTBand->SetDescription(poSrcBand->GetDescription());
+        GDALCopyNoDataValue(poVRTBand, poSrcBand);
```
Comment (jratike80) [inline apps/gdalenhance.cpp]: What if the input is int16 and nodata something like -32768?

Comment (rouault) [reply apps/gdalenhance.cpp]: that should be fine if the output is int16 too, otherwise, yes, there will be an issue. PR amended to check input type == output type before setting nodata
