### PR TITLE
Fix for RasterIO error when writing target raster in certain cases (#2027)

### LINKED ISSUE #2027: gdal_viewshed RasterIO error when writing target raster
## Expected behavior and actual behavior.

Certain maxdistance values may cause RasterIO errors, which also depends on the geotransform parameters from the input raster. This happens when the upper or lower row of the output raster falls outside of the area in range (specified by maxdistance).
The expected behavior is that the target raster should be written successfully in these cases.

## Steps to reproduce the problem.

The following use case was reported on the gdal-dev list:

```
gdal_viewshed -md 800 -ox 985710 -oy 658590
http://download.osgeo.org/gdal/data/aaigrid/095b_dem_90m.asc
output3.tif

```
## Operating system

This issue is OS independent

## GDAL version and provenance

Applies to GDAL master

### PR DESCRIPTION
**Pull request by szekerest**
#1737  What does this PR do?

fixes #2027 and updates description comments to GDALViewshedGenerate

## What are related issues/pull requests?

#2027 

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

N/A

### CODE REVIEW

File: gdal/alg/viewshed.cpp [hunk 1]
```diff
@@ -121,44 +121,49 @@ inline static double CalcHeight(double dfZ, double dfZ2, GDALViewshedMode eMode)
...
  * @param  dfVisibleVal pixel value for visibility (default 0)
  *
  * @param dfInvisibleVal pixel value for invisibility (default 255)
  *
- * @param dfOutOfRangeVal Out of range value
+ * @param dfOutOfRangeVal The value to be set for the cells that fall outside of the
+ * range specified by dfMaxDistance.
  *
- * @param dfNoDataVal NODATA value to use
+ * @param dfNoDataVal The value to be set for the cells that has no data.
```
Comment (rouault) [inline gdal/alg/viewshed.cpp]:
```suggestion
 * @param dfNoDataVal The value to be set for the cells that have no data.
```

**Comment by szekerest** [comment]
Regarding to the autotest, I'm planning to put something together within the scope of https://github.com/OSGeo/gdal/issues/1917
