### PR TITLE
SQLite SQL dialect: assume that if NULL content is found in first row…

### LINKED ISSUE #14113: ogr2ogr: if a SQL statement returns a NULL geom on the first row, an error is thrown
### What is the bug?

When running the [geofileops](https://github.com/geofileops/geofileops) tests using the GDAL master conda package, the test executing a spatialite function on the geometry where the result is NULL for the first row, following error is now given (on GDAL master).

**EDIT**: the error occurs when the input file is a .shp and output is a .gpkg:
```
geofileops.util._ogr_util.GDALError: Error Terminating translation prematurely after failed
translation from sql statement.
May be caused by: Cannot create field geom. It has the same name as the geometry field. while creating/updating /tmp/pytest-of-runner/pytest-0/popen-gw3/test_vector_translate_sql_geom2/output.gpkg using sql_stmt SELECT * FROM (
          SELECT ST_Buffer(geometry, -10) AS geom, oidn, uidn
            FROM "polygon-parcel_31370_None"
          )
        ORDER BY geom IS NULL DESC
```

On the currently released GDAL 3.12.2, this error doesn't occur.

### Steps to reproduce the issue

The script below is basically the same code as in the test that is now failing.

**EDIT**: updated script so input file is a .shp

Script::

``` python
from osgeo import gdal
import geopandas as gpd

gdal.UseExceptions()

src = "/vsizip//vsicurl/https://github.com/geofileops/geofileops/raw/main/tests/data/poly_shp.zip"

# If the geom column is the result of a Spatialite function and this results to NULL for
# the first row returned, all geometries in the column will be NULL.
dst = "/vsimem/dst_function.gpkg"
for order_by in ["DESC", "ASC"]:
    # Order by ASC -> NULL values will be last, so that will have proper results
    sql = f"""
        SELECT geom FROM
            (SELECT ST_Buffer(geometry, -100) AS geom FROM "poly")
        ORDER BY geom IS NULL {order_by}
    """
    options = gdal.VectorTranslateOptions(
        SQLStatement=sql, SQLDialect="SQLite", geometryType="MULTIPOLYGON"
    )

    try:
        ds_output = gdal.VectorTranslate(
            srcDS=src, destNameOrDestDS=dst, options=options
        )
        print(
            f"geom column is Spatialite function, with order by {order_by}:\n{gpd.read_file(dst)}\n"
        )
    except Exception as e:
        print(
            f"geom column is Spatialite function, with order by {order_by}:\nError: {e}\n"
        )

gdal.Unlink(dst)
```

### Versions and provenance

This seems to be a new issue on GDAL master and isn't occuring on the released GDAL 3.12.2.

Noticed in the [geofileops](https://github.com/geofileops/geofileops) tests running on GDAL master conda package:
https://github.com/geofileops/geofileops/actions/runs/23001231471/job/66785992342

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
… of a 'geom'/'geometry' column, it is a geometry column

Fixes #14113

### CODE REVIEW

File: ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp [hunk 1]
```diff
@@ -871,6 +957,15 @@ OGRFeature *OGRSQLiteLayer::GetNextRawFeature()
...
             }
         }
+        else if (!(nSQLite3Type == SQLITE_TEXT || nSQLite3Type == SQLITE_BLOB))
+        {
+            bUnexpectedType = true;
+        }
+        if (bUnexpectedType)
+        {
+            CPLErrorOnce(CE_Warning, CPLE_AppDefined,
+                         "Received unexpected data type for geometry column");
```
Comment (elpaso) [inline ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp]: Perhaps also useful to print the actual data type name?
```suggestion
                         "Unexpected data type for geometry column");
```

Comment (rouault) [reply ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp]: fixed
