### PR TITLE
OGRGetXMLDateTime(): Interpret TZFlag correctly (fixes #996)

### LINKED ISSUE #996: OGR: OGRGetXMLDateTime() interprets TZFlag incorrectly
## Expected behavior and actual behavior.

As described in [a comment on an earlier issue](https://github.com/OSGeo/gdal/issues/841#issuecomment-412350929), the function [`OGRGetXMLDateTime()`](https://github.com/OSGeo/gdal/blob/cdbba83cc3eea4ef48b3205865432f40fe0bbc52/gdal/ogr/ogrutils.cpp#L1378) interprets the `TZFlag` member of a date/time field in a way that disagrees with the documentation:

> [The documentation for `OGRFeature::SetField()`](https://gdal.org/classOGRFeature.html#a4ca0f1bca72c88fe9f881871cdc401a5) gives this description:
> 
> > nTZFlag (0=unknown, 1=localtime, 100=GMT, see data model for details)
> 
> but [`OGRGetXMLDateTime`'s implementation](https://github.com/OSGeo/gdal/blob/cdbba83cc3eea4ef48b3205865432f40fe0bbc52/gdal/ogr/ogrutils.cpp#L1378-L1419) assumes values of both 0 and 100 indicate GMT, and treats the value 1 as specifying an actual offset.
> 
> It seems to me it should output
> 
> - The "Z" time zone specifier when TZFlag equals 100, to indicate GMT;
> - _No_ time zone specifier when TZFlag equals 0 or 1, since the time zone is indeterminate in these cases; and
> - A computed time zone offset for all other values.

I'll submit shortly a pull request that implements this fix.

## Operating system

Ubuntu 16.04.5 64-bit (via Windows Subsystem for Linux on Windows 10)

## GDAL version and provenance

GDAL 2.4.0dev, compiled from the code in `master`

### PR DESCRIPTION
**Pull request by simonsouth**
## What does this PR do?

Modifies [the `OGRGetXMLDateTime()` function](https://github.com/OSGeo/gdal/blob/cdbba83cc3eea4ef48b3205865432f40fe0bbc52/gdal/ogr/ogrutils.cpp#L1378) to interpret a date/time field's `TZFlag` member in accordance with [the documentation](https://gdal.org/classOGRFeature.html#a4ca0f1bca72c88fe9f881871cdc401a5). Specifically, when formatting a date/time field, the function now

- Appends no timestamp qualifier for an unknown (`TZFlag` = 0) or local (`TZFlag` = 1) time zone;
- Appends "Z" for the GMT time zone (TZFlag = 100); and
- Appends a computed time-zone offset for all other `TZFlag` values.

I've reviewed every use of this function in the library and can see no areas where these changes would cause issues. No driver appears to modify either the field members before or the returned string after the function call to accommodate its existing behaviour (the one exception being [the GMLAS driver](https://github.com/OSGeo/gdal/tree/cdbba83cc3eea4ef48b3205865432f40fe0bbc52/gdal/ogr/ogrsf_frmts/gmlas), which only [splits the returned string](https://github.com/OSGeo/gdal/blob/cdbba83cc3eea4ef48b3205865432f40fe0bbc52/gdal/ogr/ogrsf_frmts/gmlas/ogrgmlaswriter.cpp#L2320-L2336) into its component date and time values).

In addition to the above, this change

- Refactors `OGRGetXMLDateTime()` to eliminate redundant code, and
- Adds a set of test cases that exercises each of the function's code paths.

## What are related issues/pull requests?

Fixes issue #996.

## Tasklist

 - [X] Add test case(s)
 - [X] Modify implementation
 - [X] Review use of function across library
 - [ ] Review pull request
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: Ubuntu 16.04.5 64-bit (via Windows Subsystem for Linux on Windows 10)
* Compiler: gcc 5.4.0

### CODE REVIEW

**Comment by rouault** [comment]
A number of autotests should be adjusted. See https://api.travis-ci.com/v3/job/150932610/log.txt

**Comment by simonsouth** [comment]
Thanks. The `ogr_mvt` test cases were easy to fix.

The `ogr_gmlas_writer_check_xml_xsd` test is failing because [it bounces data to a SQLite database and back](https://github.com/OSGeo/gdal/blob/26116b3d1c0216dbe86c2d39d0599ea19a815c5a/autotest/ogr/ogr_gmlas.py#L2398-L2403), and the SQLite driver [strips time-zone information from date/time fields](https://github.com/OSGeo/gdal/blob/26116b3d1c0216dbe86c2d39d0599ea19a815c5a/gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitelayer.cpp#L3325-L3399) as they're retrieved. (Because `OGRGetXMLDateTime()` previously interpreted missing time-zone information as GMT, this problem was masked.)

Before I invest a lot of time in correcting this,

- Is the lack of time-zone support in the SQLite driver intentional?
- Would it make more sense to improve `OGRSQLITEStringToDateTimeField()` to recognize time-zone modifiers, or to change the `ogr_gmlas_writer_check_xml_xsd` test case so it expects time-zone information to be lost?

**Comment by rouault** [comment]
>     * Is the lack of time-zone support in the SQLite driver intentional?

Probably not. Just that it wasn't implemented

> Would it make more sense to improve OGRSQLITEStringToDateTimeField() to recognize time-zone modifiers

Seems reasonable

**Comment by simonsouth** [comment]
Even, here are the completed changes I'm proposing.

Rather than extend the driver-unique `OGRSQLITEStringToDateTimeField()` I've replaced it with calls to [`OGRParseDate()`](https://github.com/OSGeo/gdal/blob/4b906b2dfd49c259e2bd3c53aece4b5a6139e2c9/gdal/ogr/ogrutils.cpp#L960-L1193), which recognizes the same date and time formats but honours time-zone information and is shared among drivers. This effectively brings time-zone support to the SQLite driver.

There is one small change in functionality: Whereas `OGRSQLITEStringToDateTimeField()` would modify the target field value only if it successfully parsed its input string, `OGRParseDate()` _always_ modifies the target field, [resetting its values to zero](https://github.com/OSGeo/gdal/blob/4b906b2dfd49c259e2bd3c53aece4b5a6139e2c9/gdal/ogr/ogrutils.cpp#L1000-L1007) even if parsing fails. I can see this making a difference only [within the (driver-internal) `OGR2SQLITE_FeatureFromArgs()`,](https://github.com/OSGeo/gdal/blob/4b906b2dfd49c259e2bd3c53aece4b5a6139e2c9/gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp#L1558-L1559) and I note that all tests pass, but it is something you may want to consider.

`OGRSQLITEStringToDateTimeField()` had a secondary function of identifying the simplest field type (among `OFTDate`, `OFTTime` and `OFTDateTime`) that corresponded to a given date or time string. I've preserved this in a new function, `OGRGetDateTimeFieldType()`, internal to the driver. It accepts a _presumed-valid_ date or time string and performs a few simple tests to determine the appropriate field type. (It might be useful down the road to merge this functionality into `OGRParseDate()`, which can easily make the determination at the same time it's parsing the string.)

Only one change had to be made to the GMLAS test cases, to remove from their reference output a GMT time-zone identifier that is [not present in the source data](https://github.com/OSGeo/gdal/blob/4b906b2dfd49c259e2bd3c53aece4b5a6139e2c9/autotest/ogr/data/gmlas/gmlas_test1.xml#L41). With my changes applied the driver now correctly recognizes the input time zone as unspecified.

File: gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp [hunk 1]
```diff
@@ -1554,11 +1554,9 @@ static OGRFeature* OGR2SQLITE_FeatureFromArgs(OGRLayer* poLayer,
                     case OFTDate:
                     case OFTTime:
                     case OFTDateTime:
-                    {
-                        if( !OGRSQLITEStringToDateTimeField( poFeature, i, pszValue ) )
+                        if( !OGRParseDate( pszValue, poFeature->GetRawFieldRef(i), 0 ) )
```
Comment (rouault) [inline gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp]: can you call poFeature->UnsetField(i) when OGRParseDate() fails ? Similarly for the other call sites of OGRSQLITEStringToDateTimeField(). Or maybe keep OGRSQLITEStringToDateTimeField() to do just that: call OGRParseDate() and UnsetField() when it fails ?

**Comment by rouault** [comment]
@simonsouth Will you continue work on this PR ?

**Comment by simonsouth** [comment]
Yes, I've just been snowed under lately with the start of a new job. I plan to return to this this weekend.

**Comment by simonsouth** [comment]
@rouault I've updated the PR with these changes. Please let me know what you think.

In the end, only [two](https://github.com/OSGeo/gdal/pull/997/files#diff-76632a86d0980b449fcab6f7f5f56a8dR873) [uses](https://github.com/OSGeo/gdal/pull/997/files#diff-76632a86d0980b449fcab6f7f5f56a8dR886) of `OGRParseDate()` in `ogrsqlitelayer.cpp` seemed to need updating:

- [At line 456](https://github.com/OSGeo/gdal/pull/997/files#diff-76632a86d0980b449fcab6f7f5f56a8dR456), a scratch field is used that does not need to be unset.

- [In `ogrsqlitevirtualogr.cpp`](https://github.com/OSGeo/gdal/pull/997/files#diff-4382d18ebb366547e844b3e326fa47cbR1557), the field's value is _always_ set: To a date value, if one can be parsed; otherwise to the (unparseable) source string.

**Comment by rouault** [comment]
OK. Looks good to me. Thanks
