### PR TITLE
Addresses minor issues in the LVBAG driver

### LINKED ISSUE #3462: LVBAG Driver: not identified with vsizip when .zip file contains single XML file
## Expected behavior and actual behavior.
Dutch Addresses and Buildings (BAG) data is distributed by Dutch Kadaster as XML files in nested .zip files (up to three levels of nesting).

That nesting is not the problem here, GDAL/OGR `/vsizip` can handle that. 
The LVBAG Driver always identifies the XML files as BAG files for XML and .zip files. Only
when a BAG **.zip file (nested or not) contains a single `.xml` file** that file is not identified as LVBAG
but as `GML` (as GML comes later in the `OGR Formats` chain).

## Steps to reproduce the problem.

Using a `bash` script I paste here:

```
#!/bin/bash
#
# Test (nested) vsizip for LVBAG
#
# Municipalities
# outer: BAGGEM0221L-15092020.zip
# inner: 0221GEM15092020.zip
# inner-inner: 0221PND15092020.zip
# content:  0221PND15092020-000001.xml

# source: https://extracten.bag.kadaster.nl/lvbag/extracten/Gemeente%20LVC/0221/BAGGEM0221L-15022021.zip
# ogrinfo /vsizip{/vsizip/{/vsizip/{BAGGEM0221L-15092020.zip}/0221GEM15092020.zip}/0221PND15092020.zip}
BAG_URL="https://extracten.bag.kadaster.nl/lvbag/extracten"
DATE="15022021"

# Doesburg
GEM_CODE="0221"
BAG_ZIP="BAGGEM${GEM_CODE}L-${DATE}.zip"
BAG_ZIP_URL="${BAG_URL}/Gemeente%20LVC/${GEM_CODE}/${BAG_ZIP}"

echo "Download ${BAG_ZIP}"
curl --silent -o ${BAG_ZIP} ${BAG_ZIP_URL}

OBJS="LIG NUM OPR PND STA VBO WPL"
for OBJ in ${OBJS}
do
	# Ex:   /vsizip/{/vsizip/{/vsizip/{BAGGEM0221L-Doesburg-15092020.zip}/0221GEM15092020.zip}/0221PND15092020.zip}
	ogrinfo /vsizip/{/vsizip/{/vsizip/${BAG_ZIP}/${GEM_CODE}GEM${DATE}.zip}/${GEM_CODE}${OBJ}${DATE}.zip}
done

```
The output is:

```
Download BAGGEM0221L-15022021.zip
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221LIG15022021.zip}'
      using driver `GML' successful.
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221NUM15022021.zip}'
      using driver `GML' successful.
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221OPR15022021.zip}'
      using driver `GML' successful.
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221PND15022021.zip}'
      using driver `LVBAG' successful.
1: Pand (Multi Polygon)
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221STA15022021.zip}'
      using driver `GML' successful.
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221VBO15022021.zip}'
      using driver `LVBAG' successful.
1: Verblijfsobject (Point)
INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221WPL15022021.zip}'
      using driver `GML' successful.
```
Edit: explicitly specifying the full path of the XML file within the .zip identifies ok, like the latter (WPL):

```
ogrinfo /vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221WPL15022021.zip}/0221WPL15022021-000001.xml

INFO: Open of `/vsizip/{/vsizip/{/vsizip/BAGGEM0221L-15022021.zip/0221GEM15022021.zip}/0221WPL15022021.zip}/0221WPL15022021-000001.xml'
      using driver `LVBAG' successful.
1: Woonplaats (Multi Polygon)
```

I would expect ` using driver 'LVBAG' successful.` for all files. Only the zip-files that contain more than one `.xml` are identified as `LVBAG`. Also tested with larger municipalities e.g. Amsterdam (0363) and the entire Netherlands. 
There all zip-files except WPL (Woonplaats) have multiple XML files, so:

```
INFO: Open of `/vsizip/{/vsizip/BAGNLDL-08112020.zip/9999LIG08112020.zip}'
      using driver `LVBAG' successful.
1: Ligplaats (Polygon)
INFO: Open of `/vsizip/{/vsizip/BAGNLDL-08112020.zip/9999STA08112020.zip}'
      using driver `LVBAG' successful.
1: Standplaats (Polygon)
INFO: Open of `/vsizip/{/vsizip/BAGNLDL-08112020.zip/9999WPL08112020.zip}'
      using driver `GML' successful.
1: Polygon (None)
```

So `9999WPL08112020.zip` is not identified as `LVBAG` (as it contains a single xml file).

## Analysis

This issue looks similar to issue #1739. So when a vsizip .zip contains a single file 
this is not considered a directory. I found no way to enforce the LVBAG Driver by
prepending `LVBAG:` (that would be of great help!)

IMHO the relevant lines in LVBAG identification sniffer are

* [ogrlvbagdriver.cpp#L40](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp#L40) 
* [ogrlvbagdriver.cpp#L86](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp#L86)

Possible solution could be similar to [Identification in GML Driver](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/gml/ogrgmldriver.cpp#L52) (?) 

## Operating system

Any, but tested on Mac OS 10.14.6 and Docker `osgeo/gdal:alpine-small-latest`.

## GDAL version and provenance

Mac OS via Homebrew: GDAL 3.2.1, released 2020/12/29
and latest Docker on Feb 11, 2021.

### LINKED ISSUE #3467: LVBAG Driver: Building Pand geometry should be Polygon
## Expected behavior and actual behavior.

The Dutch LV BAG XSD 2.1.0 defines the geometry of a Pand (Building) as a GML `Surface` (not `MultiSurface`), like `Ligplaats` and `Standplaats`. (Only Woonplaats can be either `Surface`  or `MultiSurface`, so `MultiPolygon` is ok there). 

The LVBAG GDAL driver defines `Pand` geometry as `wkbMultiPolygon`.
 
See https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp#L228

## Steps to reproduce the problem.

We define a Pand table beforehand as to have all types according to the XSD as follows:
```
CREATE TABLE pand
(
    gid serial,
    identificatie character varying(16),
    oorspronkelijkbouwjaar integer,
.
.
    geovlak geometry(Polygon, 28992),
    PRIMARY KEY (gid)
);
```

This raises an error when running `ogr2ogr`. If we define geometry column as `geovlak geometry(MultiPolygon, 28992),`, loading is ok. Also in BAG v1 we used `Polygon` without problems. 

The only "multi" facet of Pand geometry are Polygons with a single `exterior` and one or more `interior`s. 
This is luckily preserved within the MultiPolygon now.  An example of such a Pand is:

`SELECT st_asGML(geovlak) FROM pand WHERE identificatie = '0221100000312258' and eindregistratie is null;`

image

## Operating system

Any

## GDAL version and provenance

Latest as on feb 19, 2021 and latest Docker on that date.

### PR DESCRIPTION
**Pull request by yorickdewid**
## What does this PR do?

* Remove the XML extension check
* Addressing issue in which an archive with a single file is not identified by the driver
* Conform specification; PND dataset should report polygon, not multiPolygon

## What are related issues/pull requests?

Fixes #3467
Fixes #3462

## Tasklist

 - [x] Add test case(s)
 - [x] Add documentation
 - [x] Review
 - [x] Adjust for comments
 - [x] All CI builds and checks have passed

### CODE REVIEW

File: gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp [hunk 1]
```diff
@@ -38,13 +38,14 @@ static int OGRLVBAGDriverIdentify( GDALOpenInfo* poOpenInfo )
...
     if( poOpenInfo->bIsDirectory )
-        return -1;  // Unsure.
+        return -1;  // Check later
     if( poOpenInfo->fpL == nullptr )
         return FALSE;
  
-    CPLString osExt(CPLGetExtension(poOpenInfo->pszFilename));
-    if( !EQUAL(osExt, "xml") )
-        return FALSE;
+    if( STARTS_WITH(poOpenInfo->pszFilename, "/vsizip/") ||
```
Comment (rouault) [inline gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp:45]: can't you just remove that check ? Normally if you open a file through /vsizip/ and the like, you should get in poOpenInfo->pabyHeader the header bytes.
And you could then just remove the zip test file and associated test, since there's normally no need to do any particular processing for the /vsizip/ case compared to a regular file

Comment (yorickdewid) [reply gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp:45]: Sure, forgot to remove

**Comment by rouault** [comment]
There's something wrong that make autotest times out

**Comment by yorickdewid** [comment]
Rebase build.

I am not sure if the stuck jobs are caused by the patch

**Comment by yorickdewid** [comment]
It does seems to be related to testcases, I'll look into it
