### PR TITLE
GDALRasterBand::ComputeStatistics(): fix imprecise result on stddev on Float64 with SSE2/AVX2 optimization (3.12.0 regression)

### LINKED ISSUE #13543: HFA Float64 Statistics. Standard deviation value changed since previous version.
### What is the bug?

A routine test of raster statistics calculations on different formats/data types/scales now shows up a difference when compared with the equivalent calculation in numpy. The difference is only for HFA format, only for Float64 datatype, and only for the value of standard deviation. This test passes fine in GDAL 3.11.5, but for GDAL 3.12.0 it now shows differences in the 6th or 7th significant digit. Given that it is Float64, this seems quite large. There is no similar difference for Float32.

The test script below gives the following under GDAL 3.11.5: 

    GDAL stddev: 20.453280258840802
    Numpy stddev: 20.453280258840962
    Diff: 1.5987211554602254e-13

but under GDAL 3.12.0, gives a difference value 9 orders of magnitude larger:

    GDAL stddev: 20.453057295689366
    Numpy stddev: 20.453280258840962
    Diff: 0.0002229631515966446

The only relevant change I could find in the release notes is

    ComputeStatistics(): speed-up on Intel SSE2 for number of data types

although it is not clear to me why this would only affect HFA. 

According to /proc/cpuinfo, SSE2 is supported on my hardware, so it could be relevant.

### Steps to reproduce the issue

The following script will report the difference in std dev between GDAL and Numpy.

```python
#!/usr/bin/env python
"""
Report difference in Std dev between GDAL & Numpy. Run under GDAL
versions 3.11.5 and 3.12.0 to see change in the Diff value.
"""
import os
import numpy
from osgeo import gdal, gdal_array


gdal.UseExceptions()


crOpt = {
    'HFA': ['COMPRESS=YES'],
    'KEA': [],
    'GTiff': ['COMPRESS=DEFLATE', 'TILED=YES']
}


def main():
    drvrName = 'HFA'
    gdtype = gdal.GDT_Float64
    ndtype = gdal_array.GDALTypeCodeToNumericTypeCode(gdtype)
    (nRows, nCols, nBands) = (500, 500, 1)

    drvr = gdal.GetDriverByName(drvrName)
    ext = drvr.GetMetadataItem('DMD_EXTENSION')
    filename = f'testStd.{ext}'
    if os.path.exists(filename):
        drvr.Delete(filename)
    ds = drvr.Create(filename, nCols, nRows, nBands, gdtype, crOpt[drvrName])

    # A ramp array
    (x, y) = numpy.mgrid[:nRows, :nCols]
    ramp = ((x + y) * 100.0 / (nRows - 1 + nCols - 1)).astype(ndtype)

    band = ds.GetRasterBand(1)
    band.WriteArray(ramp)

    (minVal, maxVal, mean, stddev) = band.ComputeStatistics(approx_ok=False)
    npStd = ramp.std()

    print('GDAL stddev:', stddev)
    print('Numpy stddev:', npStd)
    print('Diff:', abs(stddev - npStd))


if __name__ == "__main__":
    main()
```

### Versions and provenance

Linux Ubuntu 24.04.1
GDAL 3.12.0 "Chicoutimi", released 2025/11/03
Installed from conda-forge
Python 3.14.2
Numpy 2.3.5

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13543

### CODE REVIEW

File: gcore/gdalrasterband.cpp [hunk 1]
```diff
@@ -6580,175 +6612,117 @@ static int
 ComputeStatisticsFloat32_SSE2(const float *pafData,
                               [[maybe_unused]] float fNoDataValue, int iX,
                               int nCount, float &fMin, float &fMax,
-                              float &fBlockMean, float &fBlockM2,
-                              int &nBlockValidCount)
+                              double &dfBlockMean, double &dfBlockM2,
+                              double &dfBlockValidCount)
```
Comment (elpaso) [inline gcore/gdalrasterband.cpp:6616]: Why is this now a floating point type?

Comment (rouault) [reply gcore/gdalrasterband.cpp:6616]: To increase the accuracy and get comparable results to GDAL < 3.12.0 or numpy.std() for example. The impact on performance of doing the computations on double rather than float is very moderate

**Comment by rouault** [comment]
The backport to `release/3.12` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 536104a779... GDALRasterBand::ComputeStatistics(): fix imprecise result on stddev on Float64 with SSE2/AVX2 optimization (3.12.0 regression)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/gcore/gdal_stats.py
CONFLICT (content): Merge conflict in autotest/gcore/gdal_stats.py
Auto-merging gcore/gdalrasterband.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.12 release/3.12
# Navigate to the new working tree
cd .worktrees/backport-release/3.12
# Create a new branch
git switch --create backport-13549-to-release/3.12
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 536104a779248cca67e5d8d7902a3a49a9cfb4e7,a8fd930ae8487601c9e63f59160b3b17803b2a23
# Push it to GitHub
git push --set-upstream origin backport-13549-to-release/3.12
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.12
```
Then, create a pull request where the `base` branch is `release/3.12` and the `compare`/`head` branch is `backport-13549-to-release/3.12`.

File: gcore/gdalrasterband.cpp (hunk 1 above)
Comment (elpaso) [reply gcore/gdalrasterband.cpp:6616]: I was talking about the dfBlockValidCount variable.

Comment (rouault) [reply gcore/gdalrasterband.cpp:6616]: In the computation, we do a division on type double by the number of valid pixels processed, so it is more efficient to store it on double rather than doing multiple int <--> double conversions.   This is the same as the very similar Float64 implementation of this method.

**Comment by rouault** [comment]
backport to 3.12 per https://github.com/OSGeo/gdal/pull/13552
