### PR TITLE
Remove dir only if it exists

### LINKED ISSUE #11485: TileDB test failure with tiledb 2.27 on Windows Conda
@sgillies Any desire to take care of TileDB related stuff ;-) ?

master test failure in https://github.com/OSGeo/gdal/actions/runs/12298734799/job/34322855248:
```
2024-12-12T15:09:08.2457022Z 38: FAILED tiledb_write.py::test_tiledb_write_overviews - RuntimeError: Array::delete_array(C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-2\test_tiledb_write_overviews0\test.tiledb\l_1) failed: [TileDB::IO] Error: Failed to delete path 'C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-2\test_tiledb_write_overviews0\test.tiledb\l_1'; not a valid path.
```

Recent successful builds were on tiledb 2.26.2  (https://github.com/OSGeo/gdal/actions/runs/12287644512/job/34290038383), so this is 2.27.0 specific

### PR DESCRIPTION
**Pull request by sgillies**
Hopefully this solves compatibility issues and resolves #11485 for all recent TileDB versions.

In TileDB 2.27.0, `delete_array()` and `delete_group()` will clean up the parent directory when they can. I suspect the test fails because the driver code tries to delete a directory that has already been removed.

### CODE REVIEW

File: frmts/tiledb/tiledbdense.cpp [hunk 1]
```diff
@@ -2933,7 +2933,9 @@ CPLErr TileDBRasterDataset::IBuildOverviews(
             {
                 CPL_IGNORE_RET_VAL(poODS->Close());
                 tiledb::Array::delete_array(*m_ctx, poODS->GetDescription());
-                vfs.remove_dir(poODS->GetDescription());
+                if (vfs.is_dir(poODS->GetDescription()) {
```
Comment (rouault) [inline frmts/tiledb/tiledbdense.cpp:2936]:
```suggestion
                if (vfs.is_dir(poODS->GetDescription())) {
```

can you also include a revert of 733a50e5629efaa3892d8803f1f0d61bc321e6b6 in your PR? Thanks

File: frmts/tiledb/tiledbdense.cpp [hunk 2]
```diff
@@ -2933,7 +2933,9 @@ CPLErr TileDBRasterDataset::IBuildOverviews(
             {
                 CPL_IGNORE_RET_VAL(poODS->Close());
                 tiledb::Array::delete_array(*m_ctx, poODS->GetDescription());
-                vfs.remove_dir(poODS->GetDescription());
+                if (vfs.is_dir(poODS->GetDescription())) {
```
Comment (rouault) [inline frmts/tiledb/tiledbdense.cpp:2936]:
```suggestion
                if (vfs.is_dir(poODS->GetDescription()))
                {
```

**Comment by sgillies** [comment]
Thanks @rouault ! As you can probably tell, I was being lazy and editing files on my phone through the GitHub UI 😅

**Comment by rouault** [comment]
That has fixed it (the failures on Fedora Rawhide, or Conda builds are unrelated). Thanks

**Comment by rouault** [comment]
backported to 3.10 per 0d0ccb9eefd0d6eb2ffa2a8c3449858db74f5f4c
