### PR TITLE
[rasterize] Calculate one size from the other and the input extent

### LINKED ISSUE #13424: GDAL CLI: rasterize - add functionality to auto calc pixel dims.
### Feature description

Greetings,

When using gdal raster resize I can use --size 0,800 and it will compute the width.

However, when using gdal vector rasterize --size 0,800 it throws the error:

ERROR 1: Wrong value for -ts parameter.

Having it compute the missing value is highly desirable!

GDAL v3.12.0

Thanks!
Scott 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
... if one of the size values is 0

This allows to specify only one of the sizes (-ts) arguments.

Fixes #13424

### CODE REVIEW

File: apps/gdal_rasterize_lib.cpp [hunk 1]
```diff
@@ -1072,6 +1072,82 @@ GDALDatasetH GDALRasterize(const char *pszDest, GDALDatasetH hDstDS,
...
+            if (bCloseOutDSOnError && hDstDS)
+            {
+                GDALClose(hDstDS);
+            }
+            return nullptr;
+        }
+
+        if (psOptions->nXSize == 0)
+        {
+            const_cast<GDALRasterizeOptions *>(psOptions)->nXSize =
```
Comment (rouault) [inline apps/gdal_rasterize_lib.cpp]: rather than doing the const_cast, it would be cleaner to modify around line 992, to have something like
```
GDALRasterizeOptions sOptions;
if (psOptionsIn)
    sOptions = *psOptionsIn;
```
and replace all uses of psOptions by sOptions

File: apps/gdal_rasterize_lib.cpp [hunk 2]
```diff
@@ -1072,6 +1072,82 @@ GDALDatasetH GDALRasterize(const char *pszDest, GDALDatasetH hDstDS,
...
+                static_cast<int>(
```
Comment (rouault) [inline apps/gdal_rasterize_lib.cpp]: there's a slight chance of division by zero, and that cast to int overflows. It would be nice to catch them (true for line 1144 and 1211-1223).  A lambda or some helper function to make that code common between the osSQL.empty() and !osSQL.empty() cases could be appropriate

File: apps/gdal_rasterize_lib.cpp [hunk 3]
```diff
@@ -1072,6 +1072,82 @@ GDALDatasetH GDALRasterize(const char *pszDest, GDALDatasetH hDstDS,
...
+                    (sEnvelop.MaxX - sEnvelop.MinX) /
+                    ((sEnvelop.MaxY - sEnvelop.MinY) / psOptions->nYSize));
```
Comment (jratike80) [inline apps/gdal_rasterize_lib.cpp]: I suppose that somewhere in the code the case with a single point input dataset with Envelop.MaxX=Envelop.MinX is considered. Or a case with a single line that is either vertical or horizontal.

File: doc/source/programs/gdal_rasterize.rst [hunk 4]
```diff
@@ -166,6 +166,8 @@ raster data is supported.
 
     Set output file size in pixels and lines. Note that :option:`-ts` cannot be used with
     :option:`-tr`
+    If one of the two values is set to 0, it will be computed from the other value in order to
+    preserve the aspect ratio.
```
Comment (jratike80) [inline doc/source/programs/gdal_rasterize.rst:170]: Is it so complicated? When the result would be something else than ResX=ResY?

File: apps/gdal_rasterize_lib.cpp (hunk 3 above)
Comment (elpaso) [reply apps/gdal_rasterize_lib.cpp]: Are you sure that's handled? I'm writing tests for that case and they all err out with `RuntimeError: Could not determine bounds`, because the extent is checked (in `CreateOutputDataset`), even if the size is specified.

I suppose that the only logical outcome in this case would be to set extent dimension that is 0 to 1 but doing that in the "guess the missing size" logic that I am implementing here is not sufficient: it requires deeper changes in `CreateOutputDataset` I could do that, but I start thinking that I may be missing something.

File: doc/source/programs/gdal_rasterize.rst (hunk 4 above)
Comment (elpaso) [reply doc/source/programs/gdal_rasterize.rst:170]: I don't follow: if it's a matter of wording can you suggest a better sentence?

File: apps/gdal_rasterize_lib.cpp (hunk 1 above)
Comment (elpaso) [reply apps/gdal_rasterize_lib.cpp]: done

File: apps/gdal_rasterize_lib.cpp (hunk 2 above)
Comment (elpaso) [reply apps/gdal_rasterize_lib.cpp]: I couldn't find the div by zero code path but I've added some checks for overflow.

File: apps/gdal_rasterize_lib.cpp (hunk 3 above)
Comment (elpaso) [reply apps/gdal_rasterize_lib.cpp]: The last commit contains the failing test for the case (I believe) you are talking about.

Here is set to an explicit value and it still fails:
https://github.com/OSGeo/gdal/pull/13442/commits/e40de21dedc93bde5b360cbee1304ee105908e45#diff-2b4c257fd925a541845fa90e75493bb44b29c76d82c0b2cf9073af7514511d49R756

File: apps/gdal_rasterize_lib.cpp (hunk 2 above)
Comment (rouault) [reply apps/gdal_rasterize_lib.cpp]: > I couldn't find the div by zero code path

right, it must be already covered by the "Could not determine bounds" related checks. The only checks needed are probably the ones about the floating point result being in [int_min, int_max] range.

File: doc/source/programs/gdal_rasterize.rst (hunk 4 above)
Comment (jratike80) [reply doc/source/programs/gdal_rasterize.rst:170]: What computing happens when "it will be computed from the other value in order to preserve the aspect ratio"? If the aim is to preserve the aspect ratio, doesn't it mean that ResX will be equal to ResY? Or are there situations when preserving the aspect ratio requires non-square pixels?  If not, could the wording be something like "If one of the two values is set to 0, square pixels with ResX=ResY will be generated"?, or "...the given pixel size is applied to both ResX and ResY"?

Comment (elpaso) [reply doc/source/programs/gdal_rasterize.rst:170]: Sure, I 100% agree that the xres will match yres  (except for corner case of 0 width/height that you mentioned in the other comment) but since this option is about the **size** and not the **resolution** (which has a separate option, and yes, I know they are related) I think it's confusing if we start talking about the resolution when it is the size that has been specified by the user option.

File: apps/gdal_rasterize_lib.cpp (hunk 3 above)
Comment (jratike80) [reply apps/gdal_rasterize_lib.cpp]: > Are you sure that's handled?

Because I cannot really read of write any code I was just wondering that probably this case is handled somehow because it feels so obvious that users will try to rasterize such datasets sometimes.

Then I started to think if a point has an envelope at all, but it seems to have. Interestingly PostGIS and SpatiaLite do not agree what it is.
`select st_astext(st_envelope(st_geomfromtext('POINT (1 1)')))`
gives `POINT (1 1)` with PostGIS but `POLYGON ((1 1, 1 1, 1 1, 1 1, 1 1))` with SpatiaLite.

Comment (elpaso) [reply apps/gdal_rasterize_lib.cpp]: Removing clamp to 1 for now.
