### PR TITLE
gdal vector rasterize: improve error message when invalid options paired with --update

### LINKED ISSUE #13771: Incorrect error text when missing --resolution --size gdal vector rasterize arguments.
### What is the bug?

Using `gdal vector rasterize` with arguments that indicate a new raster should be written, such as `--nodata`, fails with the following error message when `--resolution <xres>,<yres>` or `--size <xsize>,<ysize>` are not provided:

```
ERROR 6: '-tr xres yres' or '-ts xsize ysize' is required.
```

However, `gdal vector rasterize` doesn't support those old-style `gdal_rasterize` arguments so I suggest:

 - a better error message is output that specifies why the error occurred (user provided a argument that indicates a new raster should be written) as well as how to fix (specify `--resolution <xres>,<yres>` or `--size <xsize>,<ysize>`)
 - update the `gdal vector rasterize` documentation to include some text similar to that in the `gdal_rasterize` help, e.g. 

> The program creates a new target raster image when any of the `-of`, `-a_nodata`, `-init`, `-a_srs`, `-co`, `-te`, `-tr`, `-tap`, `-ts`, or `-ot` options are used. The resolution or size must be specified using the `-tr` or `-ts` option for all new rasters. The target raster will be overwritten if it already exists and any of these creation-related options are used.

### Steps to reproduce the issue

Example:
```
gdal dataset copy --source /vsicurl/https://github.com/OSGeo/gdal/raw/refs/heads/master/autotest/gdrivers/data/gtiff/int8.tif --destination int8.tif
gdal vector rasterize --burn 0 --nodata 0 --update -i /vsicurl/https://github.com/OSGeo/gdal/raw/refs/heads/master/autotest/ogr/data/geojson/polygon.geojson -o int8.tif
```
Output:
```
ERROR 6: '-tr xres yres' or '-ts xsize ysize' is required.
```

### Versions and provenance

GDAL 3.12.1 "Chicoutimi", released 2025/12/12 from conda-forge on Ubuntu 24.04

### Additional context

For info, I was attempting to burn polygon geometries as NoData into an existing raster to erase raster values under the polys. As the raster didn't have a NoData value set already, I tried also passing the `--nodata` argument, not realising this argument was incompatible with updating an existing raster. It's working now as I set the NoData value first with `gdal raster edit --nodata etc...`

### PR DESCRIPTION
**Pull request by dbaston**
Fixes #13771

### CODE REVIEW

File: apps/gdalalg_vector_rasterize.cpp [hunk 1]
```diff
@@ -238,6 +238,13 @@ bool GDALVectorRasterizeAlgorithm::RunStep(GDALPipelineStepRunContext &ctxt)
 
     if (!std::isnan(m_nodata))
     {
+        if (m_update)
+        {
+            ReportError(CE_Failure, CPLE_AppDefined,
+                        "Cannot specify --nodata when updating an updating an "
```
Comment (jratike80) [inline apps/gdalalg_vector_rasterize.cpp]: Doubled "updating an"

File: apps/gdalalg_vector_rasterize.cpp [hunk 2]
```diff
@@ -253,6 +260,13 @@ bool GDALVectorRasterizeAlgorithm::RunStep(GDALPipelineStepRunContext &ctxt)
 
     if (!m_srs.empty())
     {
+        if (m_update)
+        {
+            ReportError(CE_Failure, CPLE_AppDefined,
+                        "Cannot specify --crs when updating an updating an "
```
Comment (jratike80) [inline apps/gdalalg_vector_rasterize.cpp]: Doubled "updating an"

File: apps/gdalalg_vector_rasterize.cpp [hunk 3]
```diff
@@ -282,6 +296,13 @@ bool GDALVectorRasterizeAlgorithm::RunStep(GDALPipelineStepRunContext &ctxt)
 
     if (m_targetResolution.size())
     {
+        if (m_update)
+        {
+            ReportError(CE_Failure, CPLE_AppDefined,
+                        "Cannot specify --resolution when updating an updating "
```
Comment (jratike80) [inline apps/gdalalg_vector_rasterize.cpp]: Doubled "updating an"

File: apps/gdalalg_vector_rasterize.cpp [hunk 4]
```diff
@@ -290,6 +311,13 @@ bool GDALVectorRasterizeAlgorithm::RunStep(GDALPipelineStepRunContext &ctxt)
     }
     else if (m_targetSize.size())
     {
+        if (m_update)
+        {
+            ReportError(CE_Failure, CPLE_AppDefined,
+                        "Cannot specify --size when updating an updating an "
```
Comment (jratike80) [inline apps/gdalalg_vector_rasterize.cpp]: Doubled "updating an"

File: apps/gdalalg_vector_rasterize.cpp [hunk 5]
```diff
@@ -307,6 +335,13 @@ bool GDALVectorRasterizeAlgorithm::RunStep(GDALPipelineStepRunContext &ctxt)
 
     if (!m_outputType.empty())
     {
+        if (m_update)
+        {
+            ReportError(CE_Failure, CPLE_AppDefined,
+                        "Cannot specify --output-data-type when updating an "
+                        "updating an existing raster.");
```
Comment (jratike80) [inline apps/gdalalg_vector_rasterize.cpp]: Doubled "updating an"

**Comment by elpaso** [comment]
LGTM
Reading the docs here https://gdal.org/en/stable/programs/gdal_vector_rasterize.html I think there is still a missing detail in the description of --update: since we are dealing with two datasets here (input and output) I think we should make it clear that we are referring to the output one. There is an additional complication if the dataset is the same (e.g. a GPKG that contains the vector and where we also want to store the result).
