### PR TITLE
 Zarr: make GDALDataset::Close() report errors when write failure occurs

### LINKED ISSUE #12790: sozip error not reported back to user code
### What is the bug?

I am using GDAL to create a multidimensional zarr file that is sozip compressed. I see this error when creating the file:

ERROR 1: dish_positions.00000000.zarr/zarr.json already exists in ZIP file
ERROR 8: Open file /vsizip/data/fengine_init_pathfinder/cx66_dish_positions.00000000.zarr.zip/dish_positions.00000000.zarr/zarr.json to write failed

Everything is working fine when I do not use sozip compression. I enable sozip compression by adding a "/vsizip" prefix to the file name. Although there is an error reported on screen, I do not see an error code reported by the function creating or closing the multidimensional dataset. The resulting file ("*.zarr.zip") is created fine and looks almost correct, but all attributes seem to be missing.

A discussion on the mailing list told me that this is a real error, and GDAL is supposed to report it to the caller in user code. "Forgetting" the error seems to be an error in GDAL.

Some details:

I create the dataset (i.e. the file) via

                const auto driver_manager = GetGDALDriverManager();
                const auto driver = driver_manager->GetDriverByName("Zarr");
                const auto dataset = std::unique_ptr<GDALDataset>(driver->CreateMultiDimensional(
                    full_path.c_str(), root_group_options_c.data(), options_c.data()));

where "full_path" is "/vsizip/data/fengine_init_pathfinder/cx66_dish_positions.00000000.zarr.zip/dish_positions.00000000.zarr".

I then create multiple attributes ("CreateAttribute") and then

                const auto mdarray = group->CreateMDArray(meta->get_name(), dimensions, datatype,
                                                          array_options_c.data());
                    const bool success = mdarray->Write(
                        arrayStart.data(), count.data(), nullptr, bufferStride.data(), datatype,
                        frame + datatypesize * meta->offset, frame, buffer->frame_size);

and finish with

                const CPLErr err = dataset->Close();
                assert(!err);

The full code is available at <https://github.com/kotekan/kotekan/blob/eschnett/updates-2/lib/stages/gdalFileWrite.cpp>.

### Steps to reproduce the issue

See above.

### Versions and provenance

GDAL 3.11 build from source

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
and fix creating a /vsizip/ file
    
Fixes #12790

### CODE REVIEW

File: frmts/zarr/zarr_group.cpp [hunk 1]
```diff
@@ -24,13 +24,27 @@
...
+
+    for (auto &kv : m_oMapGroups)
+    {
+        ret = kv.second->Close() && ret;
+    }
+
     for (auto &kv : m_oMapMDArrays)
     {
-        kv.second->Flush();
+        ret = kv.second->Flush() && ret;
```
Comment (elpaso) [inline frmts/zarr/zarr_group.cpp:45]: just wondering if you could break the loop on first error or you need to complete the iteration for flushing all other items.

**Review by elpaso — APPROVED** [review]

File: frmts/zarr/zarr_group.cpp (hunk 1 above)
Comment (rouault) [reply frmts/zarr/zarr_group.cpp:45]: I wasn't sure about the right approach. I opted for flushing what could be even if a prior error occured
