### PR TITLE
overview: warn in case of conflicting mask sources

### LINKED ISSUE #13703: gdaladdo sets incorrect nodata for alpha band in RGBA geotiff if non-near resampling is used
### What is the bug?

Testcase: [sample2.zip](https://github.com/user-attachments/files/24639573/sample2.zip)

If I open `sample2.tif` in qgis and zoom in to native+ zoom, then all is OK.

If I zoom out so that overview is used, band 4 (alpha) is 254 and RGB is 0,0,0 or nodata,nodata,nodata (255,255,255). See the screenshots - red dot is the place of inspection.

Image

Image

### Steps to reproduce the issue

`gdaladdo -ro -r lanczos --config BIGTIFF_OVERVIEW YES --config PREDICTOR_OVERVIEW 2 --config COMPRESS_OVERVIEW DEFLATE sample2.tif`

### Versions and provenance

- GDAL 3.12.1 "Chicoutimi", released 2025/12/12
- Debian Testing, gdal-bin 3.12.1+dfsg-1 amd64
- Kernel 6.17.12+deb14-amd64 , #1 SMP PREEMPT_DYNAMIC Debian 6.17.12-1 (2025-12-14)

### Additional context

If `-r nearest` or no `-r` parameter is used, nodata areas are OK also in overviews.

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13703

```
$ gdal raster overview add --external sample2.tif -r average
Warning 1: Raster band 1 of dataset sample2.tif has several conflicting mask sources:
- nodata value
- related to a raster band that is an alpha band
Only the nodata value will be taken into account.
0...10...20...30...40...50...60...70...80...90...100 - done.
```

### CODE REVIEW

File: gcore/gdalrasterband.cpp [hunk 1]
```diff
@@ -9599,6 +9604,74 @@ GDALMaskValueRange GDALRasterBand::GetMaskValueRange() const
...
 
+/************************************************************************/
+/*                      HasConflictingMaskSources()                     */
+/************************************************************************/
+
+/**
+ * \brief Returns whether a raster band has conflicting mask sources.
+ *
+ * That is, if more than one of the following conditions is met:
+ * - it has an external mask flags (.msk file)
```
Comment (jratike80) [inline gcore/gdalrasterband.cpp:9616]: What if it has an internal binary mask band?

Comment (rouault) [reply gcore/gdalrasterband.cpp:9616]: good point. added

File: gcore/gdalrasterband.cpp [hunk 2]
```diff
@@ -9599,6 +9604,81 @@ GDALMaskValueRange GDALRasterBand::GetMaskValueRange() const
...
+        (!bHasExternalMask || poDS->oOvManager.GetMaskBand(nBand) != this);
+    const bool bHasNoData = HasNoData();
+    const bool bHasNODATA_VALUES =
+        poDS && poDS->GetMetadataItem("NODATA_VALUES");
+    const bool bHasAlphaBand =
+        poDS &&
+        poDS->GetRasterBand(poDS->GetRasterCount())->GetColorInterpretation() ==
+            GCI_AlphaBand;
+    int nCount = 0;
+    for (bool b : {bHasBinaryMaskBand, bHasExternalMask, bHasNoData,
```
Comment (elpaso) [inline gcore/gdalrasterband.cpp]: you can also use
```suggestion
    const std::vector<bool> maskSources {bHasBinaryMaskBand, bHasExternalMask, bHasNoData,  bHasNODATA_VALUES, bHasAlphaBand});
    const int count { std::count( makSources.cbegin(), maskSources.cend(), true) };
```

Comment (rouault) [reply gcore/gdalrasterband.cpp]: changed to your suggestion
