### PR TITLE
 GeoJSON: avoid duplication of FID in streaming parser (fixes #7258) 

### LINKED ISSUE #7258: Fid duplication when loading GeoJSON with some null id values
## Expected behavior and actual behavior.

When loading a GeoJSON file with mix of null and numbered ids, there is some duplicated feature id.

This bug was reported originally on QGIS https://github.com/qgis/QGIS/issues/51415

## Steps to reproduce the problem.

[nullids.zip](https://github.com/OSGeo/gdal/files/10758324/nullids.zip)

- Extract nullids.zip
- launch the following command 

```shell
ogrinfo -al ~/work/tmp/nullids.geojson
INFO: Open of `/home/julien/work/tmp/nullids.geojson'
      using driver `GeoJSON' successful.

Layer name: polygon_
Geometry: Multi Polygon
Feature Count: 12
Extent: (-1.228571, 0.415385) - (0.859341, 0.806593)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
FID Column = id
id: Integer (0.0)
OGRFeature(polygon_):3
  id (Integer) = 3
  MULTIPOLYGON (((-1.22637362637363 0.802197802197802,-1.08131868131868 0.806593406593407,-1.08571428571429 0.694505494505494,-1.21538461538462 0.696703296703297,-1.22637362637363 0.802197802197802)))

OGRFeature(polygon_):5
  id (Integer) = 5
  MULTIPOLYGON (((-0.90989010989011 0.802197802197802,-0.775824175824176 0.804395604395604,-0.784615384615384 0.69010989010989,-0.907692307692308 0.694505494505494,-0.90989010989011 0.802197802197802)))

OGRFeature(polygon_):2
  id (Integer) = 2
  MULTIPOLYGON (((-0.586813186813187 0.795604395604396,-0.441758241758242 0.802197802197802,-0.446153846153846 0.703296703296703,-0.575824175824176 0.701098901098901,-0.586813186813187 0.795604395604396)))

OGRFeature(polygon_):1
  id (Integer) = 1
  MULTIPOLYGON (((-0.268131868131868 0.795604395604396,-0.096703296703297 0.802197802197802,-0.103296703296703 0.70989010989011,-0.265934065934066 0.712087912087912,-0.268131868131868 0.795604395604396)))

OGRFeature(polygon_):4
  id (Integer) = 4
  MULTIPOLYGON (((0.072527472527473 0.797802197802198,0.213186813186813 0.793406593406593,0.204395604395605 0.703296703296703,0.076923076923077 0.712087912087912,0.072527472527473 0.797802197802198)))

OGRFeature(polygon_):0
  id (Integer) = (null)
  MULTIPOLYGON (((-1.17362637362637 0.525274725274725,-1.09230769230769 0.417582417582418,-1.22857142857143 0.415384615384615,-1.17362637362637 0.525274725274725)))

OGRFeature(polygon_):1
  id (Integer) = (null)
  MULTIPOLYGON (((-0.916483516483516 0.432967032967033,-0.848351648351648 0.545054945054945,-0.802197802197802 0.428571428571429,-0.916483516483516 0.432967032967033)))

OGRFeature(polygon_):2
  id (Integer) = (null)
  MULTIPOLYGON (((-0.567032967032967 0.446153846153846,-0.503296703296703 0.538461538461538,-0.446153846153846 0.428571428571429,-0.567032967032967 0.446153846153846)))

OGRFeature(polygon_):3
  id (Integer) = (null)
  MULTIPOLYGON (((-0.248351648351648 0.446153846153846,-0.191208791208791 0.545054945054945,-0.138461538461538 0.443956043956044,-0.248351648351648 0.446153846153846)))

OGRFeature(polygon_):4
  id (Integer) = (null)
  MULTIPOLYGON (((0.063736263736264 0.459340659340659,0.156043956043956 0.558241758241758,0.226373626373626 0.450549450549451,0.063736263736264 0.459340659340659)))

OGRFeature(polygon_):5
  id (Integer) = (null)
  MULTIPOLYGON (((0.386813186813187 0.446153846153846,0.483516483516484 0.553846153846154,0.547252747252747 0.446153846153846,0.386813186813187 0.446153846153846)))

OGRFeature(polygon_):6
  id (Integer) = (null)
  MULTIPOLYGON (((0.679120879120879 0.43956043956044,0.782417582417583 0.556043956043956,0.85934065934066 0.43956043956044,0.679120879120879 0.43956043956044)))
```
there is duplication

Strange thing is that if you use the geojson content directly as the dataset string, you'll get no duplication

```shell
ogrinfo -al "$(cat ~/work/tmp/nullids.geojson)"
INFO: Open of `{
"type": "FeatureCollection",
"name": "polygon_",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 3 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -1.226373626373626, 0.802197802197802 ], [ -1.081318681318681, 0.806593406593407 ], [ -1.085714285714286, 0.694505494505494 ], [ -1.215384615384615, 0.696703296703297 ], [ -1.226373626373626, 0.802197802197802 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": 5 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -0.90989010989011, 0.802197802197802 ], [ -0.775824175824176, 0.804395604395604 ], [ -0.784615384615384, 0.69010989010989 ], [ -0.907692307692308, 0.694505494505494 ], [ -0.90989010989011, 0.802197802197802 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": 2 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -0.586813186813187, 0.795604395604396 ], [ -0.441758241758242, 0.802197802197802 ], [ -0.446153846153846, 0.703296703296703 ], [ -0.575824175824176, 0.701098901098901 ], [ -0.586813186813187, 0.795604395604396 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": 1 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -0.268131868131868, 0.795604395604396 ], [ -0.096703296703297, 0.802197802197802 ], [ -0.103296703296703, 0.70989010989011 ], [ -0.265934065934066, 0.712087912087912 ], [ -0.268131868131868, 0.795604395604396 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": 4 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 0.072527472527473, 0.797802197802198 ], [ 0.213186813186813, 0.793406593406593 ], [ 0.204395604395605, 0.703296703296703 ], [ 0.076923076923077, 0.712087912087912 ], [ 0.072527472527473, 0.797802197802198 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -1.173626373626373, 0.525274725274725 ], [ -1.092307692307692, 0.417582417582418 ], [ -1.228571428571428, 0.415384615384615 ], [ -1.173626373626373, 0.525274725274725 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -0.916483516483516, 0.432967032967033 ], [ -0.848351648351648, 0.545054945054945 ], [ -0.802197802197802, 0.428571428571429 ], [ -0.916483516483516, 0.432967032967033 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -0.567032967032967, 0.446153846153846 ], [ -0.503296703296703, 0.538461538461538 ], [ -0.446153846153846, 0.428571428571429 ], [ -0.567032967032967, 0.446153846153846 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -0.248351648351648, 0.446153846153846 ], [ -0.191208791208791, 0.545054945054945 ], [ -0.138461538461538, 0.443956043956044 ], [ -0.248351648351648, 0.446153846153846 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 0.063736263736264, 0.459340659340659 ], [ 0.156043956043956, 0.558241758241758 ], [ 0.226373626373626, 0.450549450549451 ], [ 0.063736263736264, 0.459340659340659 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 0.386813186813187, 0.446153846153846 ], [ 0.483516483516484, 0.553846153846154 ], [ 0.547252747252747, 0.446153846153846 ], [ 0.386813186813187, 0.446153846153846 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 0.679120879120879, 0.43956043956044 ], [ 0.782417582417583, 0.556043956043956 ], [ 0.85934065934066, 0.43956043956044 ], [ 0.679120879120879, 0.43956043956044 ] ] ] ] } }
]
}'
      using driver `GeoJSON' successful.

Layer name: polygon_
Geometry: Multi Polygon
Feature Count: 12
Extent: (-1.228571, 0.415385) - (0.859341, 0.806593)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
FID Column = id
id: Integer (0.0)
OGRFeature(polygon_):1
  id (Integer) = 1
  MULTIPOLYGON (((-0.268131868131868 0.795604395604396,-0.096703296703297 0.802197802197802,-0.103296703296703 0.70989010989011,-0.265934065934066 0.712087912087912,-0.268131868131868 0.795604395604396)))

OGRFeature(polygon_):2
  id (Integer) = 2
  MULTIPOLYGON (((-0.586813186813187 0.795604395604396,-0.441758241758242 0.802197802197802,-0.446153846153846 0.703296703296703,-0.575824175824176 0.701098901098901,-0.586813186813187 0.795604395604396)))

OGRFeature(polygon_):3
  id (Integer) = 3
  MULTIPOLYGON (((-1.22637362637363 0.802197802197802,-1.08131868131868 0.806593406593407,-1.08571428571429 0.694505494505494,-1.21538461538462 0.696703296703297,-1.22637362637363 0.802197802197802)))

OGRFeature(polygon_):4
  id (Integer) = 4
  MULTIPOLYGON (((0.072527472527473 0.797802197802198,0.213186813186813 0.793406593406593,0.204395604395605 0.703296703296703,0.076923076923077 0.712087912087912,0.072527472527473 0.797802197802198)))

OGRFeature(polygon_):5
  id (Integer) = 5
  MULTIPOLYGON (((-0.90989010989011 0.802197802197802,-0.775824175824176 0.804395604395604,-0.784615384615384 0.69010989010989,-0.907692307692308 0.694505494505494,-0.90989010989011 0.802197802197802)))

OGRFeature(polygon_):6
  id (Integer) = (null)
  MULTIPOLYGON (((-1.17362637362637 0.525274725274725,-1.09230769230769 0.417582417582418,-1.22857142857143 0.415384615384615,-1.17362637362637 0.525274725274725)))

OGRFeature(polygon_):7
  id (Integer) = (null)
  MULTIPOLYGON (((-0.916483516483516 0.432967032967033,-0.848351648351648 0.545054945054945,-0.802197802197802 0.428571428571429,-0.916483516483516 0.432967032967033)))

OGRFeature(polygon_):8
  id (Integer) = (null)
  MULTIPOLYGON (((-0.567032967032967 0.446153846153846,-0.503296703296703 0.538461538461538,-0.446153846153846 0.428571428571429,-0.567032967032967 0.446153846153846)))

OGRFeature(polygon_):9
  id (Integer) = (null)
  MULTIPOLYGON (((-0.248351648351648 0.446153846153846,-0.191208791208791 0.545054945054945,-0.138461538461538 0.443956043956044,-0.248351648351648 0.446153846153846)))

OGRFeature(polygon_):10
  id (Integer) = (null)
  MULTIPOLYGON (((0.063736263736264 0.459340659340659,0.156043956043956 0.558241758241758,0.226373626373626 0.450549450549451,0.063736263736264 0.459340659340659)))

OGRFeature(polygon_):11
  id (Integer) = (null)
  MULTIPOLYGON (((0.386813186813187 0.446153846153846,0.483516483516484 0.553846153846154,0.547252747252747 0.446153846153846,0.386813186813187 0.446153846153846)))

OGRFeature(polygon_):12
  id (Integer) = (null)
  MULTIPOLYGON (((0.679120879120879 0.43956043956044,0.782417582417583 0.556043956043956,0.85934065934066 0.43956043956044,0.679120879120879 0.43956043956044)))
```

## Operating system

Debian 11

## GDAL version and provenance

I can reproduce both with Gdal 3.6.2 from debian package and debian master.

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

File: ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp [hunk 1]
```diff
@@ -733,6 +733,7 @@ void RegisterOGRGeoJSON()
         "Integer64List RealList StringList Date DateTime");
     poDriver->SetMetadataItem(GDAL_DMD_CREATIONFIELDDATASUBTYPES, "Boolean");
     poDriver->SetMetadataItem(GDAL_DMD_SUPPORTED_SQL_DIALECTS, "OGRSQL SQLITE");
+    poDriver->SetMetadataItem(GDAL_DCAP_MEASURED_GEOMETRIES, "YES");
```
Comment (elpaso) [inline ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp:736]: Is this change related with the GeoJson FID issue?

**Review by elpaso — APPROVED** [review]

File: ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp (hunk 1 above)
Comment (rouault) [reply ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp:736]: > Is this change related with the GeoJson FID issue?

no, that's why I put it in a separate commit. It is necessary for test_ogrsf to be happy
