### PR TITLE
PostGIS: use full geometry intersection for SetSpatialFilter(), and not only bounding box

### LINKED ISSUE #1700: PostGIS spatial filter implementation only takes into account the envelope of the filter geometry, not its shape
Tracking issue reported in https://lists.osgeo.org/pipermail/gdal-dev/2019-July/050538.html 

## Expected behavior and actual behavior.

I'm doing a spatial join between an union of geometries filtered from a 
geopackage and a tileindex layer stored in postgis, and the spatial 
filter set on the postgis layer behaves weird, the provided result is as 
if the bbox of the spatial filter/geometry was used, instead of the 
filter itself.

applying the exact same filter to a copy of the postgis layer stored in 
memory gives correct results.

Per https://gdal.org/api/ogrlayer_cpp.html#_CPPv4N8OGRLayer16SetSpatialFilterEP11OGRGeometry, SetSpatialFilter might only compare features with filter envelope (depending on the driver ?), which returns too many results.

It should filter on the exact geometry, and not its envelope.

## Steps to reproduce the problem.
```
#!/bin/env python3
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 et
import os
import re
import sys
import tempfile
from osgeo import gdal
from osgeo import ogr

# needs ssh db2.thruxton for port fwd
dbhandle = gdal.OpenEx("PG: host=localhost dbname=gisdata-local user=postgis", gdal.OF_VERBOSE_ERROR, allowed_drivers = ['PostgreSQL'])
gpkg = gdal.OpenEx('/tmp/dbdemogeor.gpkg')
communes = gpkg.GetLayerByName('adminexpress_201806_commune')
assert (dbhandle is not None)
layer = dbhandle.GetLayer('rtge.ortho')
print("{} tiles total, {} communes".format(layer.GetFeatureCount(), communes.GetFeatureCount()))

outdriver=ogr.GetDriverByName('MEMORY')
source=outdriver.CreateDataSource('memData')

tmp=outdriver.Open('memData',1)
source.CopyLayer(layer, 'out')
layer2 = source.GetLayer('out')

communes.SetAttributeFilter("insee_dep='63'")

multi  = ogr.Geometry(ogr.wkbMultiPolygon)
# compute the multigeometry for all the comms in the area list
for feature in communes:
    g = feature.GetGeometryRef()
    for i in range(0, g.GetGeometryCount()):
        multi.AddGeometry(g.GetGeometryRef(i))
communes.ResetReading()
union = multi.UnionCascaded()
# filter tileindex on a 100m bufferized union of the comms
layer.SetSpatialFilter(union.Buffer(100))

print("{} tiles are inside the geomunion for {} comms ({} surf)".format(layer.GetFeatureCount(), communes.GetFeatureCount(), union.GetArea(
)))

print("{} tiles in memory layer".format(layer2.GetFeatureCount()))
layer2.SetSpatialFilter(union.Buffer(100))
print("{} tiles in memory layer after filtering".format(layer2.GetFeatureCount()))

$python3 test_spatfilt_pgis.py 
405557 tiles total, 4092 communes
131055 tiles are inside the geomunion for 467 comms (8001479208.5 surf)
405557 tiles in memory layer
82868 tiles in memory layer after filtering
```
memory layer filtering returns the right amount of features, postgis layer filtering returns all the features that are inside the filter bbox/envelope.

So the PG driver should be fixed ?

## GDAL version and provenance

2.2.3/debian & 3.0.0/openbsd

### PR DESCRIPTION
**Pull request by rouault**
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2026-January/061350.html

Fixes #1700

### CODE REVIEW

**Comment by hobu** [comment]
I tagged this with a Breaking! label because it is definitely a behavior change that someone reading the release notes is going to want to know about.

**Comment by dbaston** [comment]
Yeah...I was wondering if we should put in a config option for it, even if the new behavior is the default. (Bonus if the option can be shared among other database drivers).

**Comment by rouault** [comment]
> ..I was wondering if we should put in a config option for it

I'm skeptical we need that complication. Do you have concrete use cases in mind where the new behavior wouldn't be desired ?

**Comment by dbaston** [comment]
A user may not want to transfer a computation task from many clients to a single shared server.

File: ogr/ogrsf_frmts/pg/ogrpgresultlayer.cpp [hunk 1]
```diff
@@ -297,35 +297,53 @@ OGRErr OGRPGResultLayer::ISetSpatialFilter(int iGeomField,
...
-                OGREnvelope sEnvelope;
-
-                m_poFilterGeom->getEnvelope(&sEnvelope);
-                if (poGeomFieldDefn->ePostgisType == GEOM_TYPE_GEOGRAPHY)
+                if (poGeomFieldDefn->ePostgisType == GEOM_TYPE_GEOMETRY &&
+                    poGeomFieldDefn->nSRSId > 0)
+                {
+                    OGRWktOptions sOptions;
+                    sOptions.variant = wkbVariantIso;
+                    const std::string osWKT =
```
Comment (dbaston) [inline ogr/ogrsf_frmts/pg/ogrpgresultlayer.cpp]: Why WKT instead of WKB?

File: ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp [hunk 2]
```diff
@@ -1057,30 +1057,46 @@ void OGRPGTableLayer::BuildWhere()
...
+                if (sEnvelope.MaxY > 90.0)
+                    sEnvelope.MaxY = 90.0;
+            }
+            CPLsnprintf(szBox3D_1, sizeof(szBox3D_1), "%.17g %.17g",
+                        sEnvelope.MinX, sEnvelope.MinY);
+            CPLsnprintf(szBox3D_2, sizeof(szBox3D_2), "%.17g %.17g",
+                        sEnvelope.MaxX, sEnvelope.MaxY);
+
+            osWHERE.Printf(
+                "WHERE %s && ST_SetSRID('BOX3D(%s, %s)'::box3d,%d) ",
```
Comment (dbaston) [inline ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp]: Consider `ST_MakeEnvelope(xmin, ymin, xmax, ymax)` to avoid number->text->number conversion.

Pretty sure the SRID is ignored so no need to call `ST_SetSRID`. Or it can be passed as a 5th arg to `ST_MakeEnvelope`.

(This is ancient code, I know)

File: ogr/ogrsf_frmts/pg/ogrpgresultlayer.cpp (hunk 1 above)
Comment (rouault) [reply ogr/ogrsf_frmts/pg/ogrpgresultlayer.cpp]: good point. change to HexEWKB

File: ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp (hunk 2 above)
Comment (rouault) [reply ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp]: > Pretty sure the SRID is ignored so no need to call `ST_SetSRID`

indeed. Changed to ST_MakeEnvelope()

**Comment by rouault** [comment]
> A user may not want to transfer a computation task from many clients to a single shared server.

What do you think about doing server-side bounding box intersection, and full intersection of the result set on the client?

**Comment by dbaston** [comment]
> What do you think about doing server-side bounding box intersection, and full intersection of the result set on the client?

Yes, that was the alternative in my mind (but I can see that I never said that, sorry.) So a config option like `SPATIAL_FILTER_INTERSECTION=[DATABASE,LOCAL]` could potentially toggle this behavior with various DB drivers.

**Comment by jratike80** [comment]
I think that a better name of the config option could be `SPATIAL_FILTER_INTERSECT` (or intersects?). Isn't the final result boolean intersects=true/false?

**Comment by rouault** [comment]
> a config option like `SPATIAL_FILTER_INTERSECTION=[DATABASE,LOCAL]`

I've implemented it as an *open option*.   @jratike80 I considered your alternative names, but I find the name "intersection" rather than the verb "intersect" more intuitive, despite pedantically this is indeed a boolean operation

**Comment by dbaston** [comment]
Should `InstallFilter` avoid setting `m_poFilterGeom` and `m_poPreparedFilterGeom` when `SPATIAL_FILTER_INTERSECTION=DATABASE` ? This would save some work and make later explicit checks for `poDS->IsSpatialFilterIntersectionLocal()` unnecessary, I think.

**Comment by rouault** [comment]
> Should `InstallFilter` avoid setting `m_poFilterGeom` and `m_poPreparedFilterGeom` when `SPATIAL_FILTER_INTERSECTION=DATABASE` ?

we have a OGR_L_GetSpatialFilter() method, so that would be a bit weird not setting m_poFilterGeom

>  This would save some work 

Just the creation of m_poPreparedFilterGeom. Otherwise per-feature iteration when the filter is evaluated server-side bypasss the FilterGeometry() call

File: doc/source/drivers/vector/pg.rst [hunk 3]
```diff
@@ -243,6 +243,19 @@ The following open options are supported:
...
+      :choices: LOCAL, SERVER
+      :default: LOCAL
+      :since: 3.13
+
+      Since GDAL 3.13, spatial filters are evaluated using full geometry intersection
+      rather than only bounding box intersection, as in earlier versions.
+      The ``SPATIAL_FILTER_INTERSECTION`` open option controls where this
+      intersection operation is performed. Even when the intersection is evaluated
+      locally (which is the default), the server still applies a bounding
+      box-based spatial filter to efficiently retrieve candidate features.
```
Comment (dbaston) [inline doc/source/drivers/vector/pg.rst:256]: Am I right that `ST_Intersects` is only called for geometry columns, not geography? Why is that? It would be helpful to explain here.

Comment (rouault) [reply doc/source/drivers/vector/pg.rst:256]: > Am I right that `ST_Intersects` is only called for geometry columns, not geography? 

yes

> Why is that?

I believe the reason is that there's a bit of conceptual mismatch because OGR only handles geometries (in a cartesian coordinate space or in a geographic coordinate space dealt as a cartesian space), whereas PostGIS geography considers spherical/ellipsoidal coordinate space.  The rationale for the current behavior is likely that with it you'd get the same result by exporting your PostGIS geography table to another OGR formats and apply the spatial filter on the later, rather than directly filtering the PostGIS DB. That's obviously debatable what should be done here.  The proper solution would be to extend the OGR data model so that geometry columns can be cartesian/geometry or geography, but that would have non trivial ramifications (like we'd probably need to use a geography aware library like S2 instead of GEOS for geography computations).  That said GeoParquet has also a geometry vs geography/spherical flag so PostGIS wouldn't be the only user here.

I've just added a mention about the geography case in the doc

File: doc/source/drivers/vector/pg.rst [hunk 4]
```diff
@@ -243,6 +243,23 @@ The following open options are supported:
...
+
+      Note that for PostGIS geometry columns of type GEOGRAPHY, the current
+      implemntation performs the intersection test on the client side, by dealing
```
Comment (dbaston) [inline doc/source/drivers/vector/pg.rst]:
```suggestion
      implementation performs the intersection test on the client side, by dealing
```
sorry :)

Comment (rouault) [reply doc/source/drivers/vector/pg.rst]: no problem. fixed.  thanks for the careful review

File: doc/source/drivers/vector/pg.rst (hunk 3 above)
Comment (dbaston) [reply doc/source/drivers/vector/pg.rst:256]: It makes sense that the results should be the same regardless of where the filter happens. If you want a server-side cartesian test for geography you could do `ST_Intersects(geog::geometry, filterGeom)`.

Comment (rouault) [reply doc/source/drivers/vector/pg.rst:256]: > If you want a server-side cartesian test for geography you could do `ST_Intersects(geog::geometry, filterGeom)`.

good suggestion. I've just done that (and thus amended the doc)

**Review by dbaston — APPROVED** [review]
