### PR TITLE
ogr: document why IsFieldNull always returns false for special fields

### LINKED ISSUE #14092: OGRFeature::IsFieldNull() has unexplained `// FIXME?`
### What is the bug?

currently, `OGRFeature::IsFieldNull()` in `ogr/ogrfeature.cpp` manages special fields (like FID, geometry, style, and area) with a vague `// FIXME?` comment and a simple `return false`

### Steps to reproduce the issue

1. open `ogr/ogrfeature.cpp` and look at `OGRFeature::IsFieldNull()`.
2. compare the special-field branch to the equivalent branch in
   `OGRFeature::IsFieldSet()` -the contrast is immediately apparent.
3. note the `// FIXME?` has been in the codebase since the nullable-field
   feature was added, with no follow-up.

### Versions and provenance

- **OS:** Linux Ubuntu 24.04
- **GDAL version:** 3.13.0  master

### Additional context

it is just a code readability improvement change

the proposed change replaces this with   `switch` statement,matching the  structure already used by the related `IsFieldSet()` method

### PR DESCRIPTION
**Pull request by KinshukSS2**
## description 

the change has no different after effect compared with the existing piece of code
it has a structure that has already been followed in places like `IsFieldSet()`

closes #14092 

for ref in ogrfeature.cpp

image

### CODE REVIEW

File: ogr/ogrfeature.cpp [hunk 1]
```diff
@@ -1669,8 +1669,21 @@ bool OGRFeature::IsFieldNull(int iField) const
...
+        switch (iSpecialField)
+        {
+            case SPF_FID:
+            case SPF_OGR_GEOMETRY:
+            case SPF_OGR_STYLE:
+            case SPF_OGR_GEOM_WKT:
+            case SPF_OGR_GEOM_AREA:
+            default:
+                return false;
+        }
```
Comment (rouault) [inline ogr/ogrfeature.cpp]:
```suggestion
        // Special fields (FID, geometry, style, area) are virtual/derived
        // values that have no nullable state.
        return false;
```
