### PR TITLE
gdalwarp: do not enable blank line detection when -tap and -te are specified (fixes #9059)

### LINKED ISSUE #9059: gdalwarp with -tap and -te does not generate file with provided extent
## Expected behavior and actual behavior.

gdalwarp should respect -te (target extent) also if it introduces blank lines

Seems to be related to:
https://github.com/OSGeo/gdal/issues/7905

## Steps to reproduce the problem.

I'm doing a gdalwarp on a file in EPSG:32631, that simply changes the bounding box, the original extent is:
600000.0  5590200.0 709800.0 5700000.0

gdalwarp -tap -tr 10.0 10.0 -te_srs EPSG:32631 -te 599800.0  5590200.0 709800.0 5700000.0 -t_srs EPSG:32631 T31UFS_20230405T105031_B04_10m.jp2 /tmp/out.tif

gdalinfo /tmp/out.tif shows:
Corner Coordinates:
Upper Left  (  600000.000, 5700000.000) (  4d26'19.96"E, 51d26'32.47"N)
Lower Left  (  600000.000, 5590200.000) (  4d24'31.37"E, 50d27'18.98"N)
Upper Right (  709800.000, 5700000.000) (  6d 1' 1.29"E, 51d24'44.43"N)
Lower Right (  709800.000, 5590200.000) (  5d57'13.93"E, 50d25'34.66"N)
Center      (  654900.000, 5645100.000) (  5d12'16.64"E, 50d56'12.12"N)

## Operating system
Arch Linux
## GDAL version and provenance
3.8.1

### PR DESCRIPTION
**Pull request by rouault**
fix #9059

### CODE REVIEW

**Review by elpaso — COMMENTED** [review]
Is this case already covered by a test?

File: apps/gdalwarp_lib.cpp [hunk 1]
```diff
@@ -4237,16 +4237,27 @@ static GDALDatasetH GDALWarpCreateOutput(
...
-                                psOptions->dfXRes;
+            if ((psOptions->bTargetAlignedPixels &&
+                 bNeedsSuggestedWarpOutput) ||
+                (psOptions->bCropToCutline &&
+                 psOptions->aosWarpOptions.FetchBool("CUTLINE_ALL_TOUCHED",
+                                                     false)))
+            {
+                bDetectBlankBorders = true;
+            }
+            constexpr double EPS = 1e-8;
```
Comment (elpaso) [inline apps/gdalwarp_lib.cpp:4248]: maybe use std::numeric_limits<double>::min()

Comment (rouault) [reply apps/gdalwarp_lib.cpp:4248]: > maybe use std::numeric_limits::min()

that would probably lead to a too small ellipson.
