### PR TITLE
[gdal_rasterize] Also accept doubles for -ts

### LINKED ISSUE #11829: gdal_rasterize -ts does not accept double anymore
### What is the bug?

See: https://github.com/qgis/QGIS/issues/60524

### Steps to reproduce the issue

See : https://github.com/qgis/QGIS/issues/60524

### Versions and provenance

3.10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
But warn if it has a decimal part.

Fixes #11829

### CODE REVIEW

**Comment by jratike80** [comment]
Out of curiosity, what will be the output size when the input is `-ts 100.4 200.6`?

**Comment by elpaso** [comment]
> Out of curiosity, what will be the output size when the input is `-ts 100.4 200.6`?

The same as  `-ts 100 200` internally casted to `int` (but you'll get a warning the precision was lost).

**Comment by jratike80** [comment]
If the price of one beer is 8.2€ but you have only 8, would you ask the bartender
"Is it OK if the conversion to int looses precision for the price parameter"?

How about "Warning: The value of the `-ts` parameter gets truncated into [lower] integer"?

File: apps/gdal_rasterize_lib.cpp [hunk 1]
```diff
@@ -1424,10 +1426,21 @@ GDALRasterizeOptionsNew(char **papszArgv,
...
-            psOptions->nYSize = oTs.value()[1];
+            const int nXSize = static_cast<int>(oTs.value()[0]);
+            const int nYSize = static_cast<int>(oTs.value()[1]);
+
+            // Warn the user if the conversion to int looses precision
+            if (nXSize != oTs.value()[0] || nYSize != oTs.value()[1])
+            {
+                CPLError(
+                    CE_Warning, CPLE_AppDefined,
+                    "Conversion to int looses precision for -ts parameter.");
```
Comment (rouault) [inline apps/gdal_rasterize_lib.cpp:1439]:
```suggestion
                    "-ts values parsed as %d %d.", nXSize, nYSize);
```

File: autotest/utilities/test_gdal_rasterize.py [hunk 2]
```diff
@@ -418,3 +417,33 @@ def test_gdal_rasterize_8(gdal_rasterize_path, tmp_path):
...
+    # Run the algorithm.
+    (_, err) = gdaltest.runexternal_out_and_err(
+        f"{gdal_rasterize_path} -at -burn 200 -ts 100.0 200.0 ../alg/data/cutline.csv {output_tif}"
+    )
+    assert err is None or err == "", f"got error/warning {err}"
+
+    (_, err) = gdaltest.runexternal_out_and_err(
+        f"{gdal_rasterize_path} -at -burn 200 -ts 100.4 200.6 ../alg/data/cutline.csv {output_tif}"
+    )
+    assert "Conversion to int looses precision for -ts parameter" in err
```
Comment (rouault) [inline autotest/utilities/test_gdal_rasterize.py:449]:
```suggestion
    assert "-ts values parsed as 100 200" in err
```

File: apps/gdal_rasterize_lib.cpp [hunk 3]
```diff
@@ -1424,10 +1426,21 @@ GDALRasterizeOptionsNew(char **papszArgv,
...
-            psOptions->nYSize = oTs.value()[1];
+            const int nXSize = static_cast<int>(oTs.value()[0]);
+            const int nYSize = static_cast<int>(oTs.value()[1]);
+
+            // Warn the user if the conversion to int looses precision
+            if (nXSize != oTs.value()[0] || nYSize != oTs.value()[1])
+            {
+                CPLError(
+                    CE_Warning, CPLE_AppDefined,
+                    "-ts values parsed as %d %d.", nXSize, nYSize);
```
Comment (rouault) [inline apps/gdal_rasterize_lib.cpp:1439]:
```suggestion
                CPLError(CE_Warning, CPLE_AppDefined,
                         "-ts values parsed as %d %d.", nXSize, nYSize);
```

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
cherry-picked to 3.10 per bb9523fc15785c9f777c72152af92740b8a964c2

**Comment by rouault** [comment]
The backport to `release/3.10` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 5be98e8ece... [gdal_rasterize] Also accept doubles for -ts
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging apps/gdal_rasterize_lib.cpp
CONFLICT (content): Merge conflict in apps/gdal_rasterize_lib.cpp
Auto-merging autotest/utilities/test_gdal_rasterize.py
CONFLICT (content): Merge conflict in autotest/utilities/test_gdal_rasterize.py

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.10 release/3.10
# Navigate to the new working tree
cd .worktrees/backport-release/3.10
# Create a new branch
git switch --create backport-11830-to-release/3.10
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 5be98e8ece4e78381865056b714b889dab0a0d46,a8257444747bce33ace816c8a21e0da04b95f5dd,687fb22c024a35d474df9596e709070409a7111a
# Push it to GitHub
git push --set-upstream origin backport-11830-to-release/3.10
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.10
```
Then, create a pull request where the `base` branch is `release/3.10` and the `compare`/`head` branch is `backport-11830-to-release/3.10`.
