### PR TITLE
Make OGR_G_SetPointXXXX and OGR_G_AddPointXXXXX functions return a OGRErr

### LINKED ISSUE #13772: `OGR_G_SetPoints` doesn't report allocation failure
### What is the bug?

`OGRSimpleCurve::setPoints` and `OGRSimpleCurve::setNumPoints` return `bool`, but `OGR_G_SetPoints` doesn't.

This is not a security issue, because even on the https://github.com/OSGeo/gdal/blob/460714afb716c007f3c543be11c6ff3d3283911b/ogr/ogr_api.cpp#L682 branch, `OGRSimpleCurve::setPoint` does a bounds check, but some users might still want to detect the allocation failure.

### Steps to reproduce the issue

N/A

### Versions and provenance

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13772

### CODE REVIEW

File: ogr/ogr_api.cpp [hunk 1]
```diff
@@ -781,18 +798,21 @@ void CPL_DLL OGR_G_SetPointsZM(OGRGeometryH hGeom, int nPointsIn,
                 ((nMStride == 0 && padfM == nullptr) ||
                  (nMStride == nSizeDouble && padfM != nullptr)))
             {
+                bool b;
```
Comment (elpaso) [inline ogr/ogr_api.cpp]:
```suggestion
                bool bSetPointResult;
```

Comment (rouault) [reply ogr/ogr_api.cpp]: fixed
