### PR TITLE
[cli][contour] Fix CLI issues #11957

### LINKED ISSUE #11957: "gdal raster contour" issues
- "gdal raster contour autotest/gcore/data/byte.tif out.gpkg", which lacks one of the required argument, shows the help message of the old gdal_contour utility. It should only indicate the name of one of the missing required arguments

- "gdal raster contour --interval 1 autotest/gcore/data/byte.tif out.gpkg" repeated twice overwrites the output file. It should require a --overwrite flag to be specified to do that

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #11957

1. "gdal raster contour autotest/gcore/data/byte.tif out.gpkg", which lacks one of the required argument, shows the help message of the old gdal_contour utility. It should only indicate the name of one of the missing required arguments

2. "gdal raster contour --interval 1 autotest/gcore/data/byte.tif out.gpkg" repeated twice overwrites the output file. It should require a --overwrite flag to be specified to do that

### CODE REVIEW

File: apps/gdalalg_raster_contour.cpp [hunk 1]
```diff
@@ -71,6 +71,7 @@ GDALRasterContourAlgorithm::GDALRasterContourAlgorithm()
     AddArg("group-transactions", 0,
            _("Group n features per transaction (default 100 000)"),
            &m_groupTransactions);
+    AddOverwriteArg(&m_overwrite);
```
Comment (rouault) [inline apps/gdalalg_raster_contour.cpp:74]: the .rst must be updated

File: autotest/utilities/test_gdalalg_raster_contour.py [hunk 2]
```diff
@@ -152,3 +162,42 @@ def test_gdalalg_raster_contour(tmp_vsimem, options, polygonize, expected_elev_v
                     assert geom.GetGeometryType() == ogr.wkbLineString
                     assert feat.GetField("ELEV") == expected_elev_values[i]
             lyr = None
+
+
+def test_gdalalg_raster_contour_overwrite(tmp_vsimem):
```
Comment (rouault) [inline autotest/utilities/test_gdalalg_raster_contour.py:167]:
```suggestion
@pytest.mark.require_driver("AAIGRID")
def test_gdalalg_raster_contour_overwrite(tmp_vsimem):
```

**Review by rouault — APPROVED** [review]
