### PR TITLE
gdaldem: fix wrong results on non north-up src ds wih aspect/tpi/tri (and…

### LINKED ISSUE #13100: gdaldem aspect produces wrong result for raster with positive y cell size
### What is the bug?

gdaldem aspect produces correct results for (tif) images with the (default) negative y pixel size, but not for positive y axis. I expect the results for both images (with the same bounds, same crs) to be the same.

A picture is worth a thousand words
Image

### Steps to reproduce the issue

Here's the Python code to produce the above plot that should work with any DEM (but I used this [srtm.tif](https://github.com/geocompx/geocompjl/raw/refs/heads/main/data/srtm.tif)).

<details><summary>Details</summary>
<p>

```python
import numpy as np
import rasterio
import rasterio.plot
import matplotlib.pyplot as plt
import subprocess

with rasterio.open('srtm.tif') as src:
    elevation = src.read(1)
    transform = src.transform
    profile = src.profile

flipped_elevation = np.flipud(elevation)

a, b, c, d, e, f = transform[:6]
height = elevation.shape[0]

new_f = f + height * e
flipped_transform = rasterio.transform.Affine(a, b, c, d, -e, new_f)

flipped_profile = profile.copy()
flipped_profile['transform'] = flipped_transform

with rasterio.open('srtm_flipped.tif', 'w', **flipped_profile) as dst:
    dst.write(flipped_elevation, 1)

with rasterio.open('srtm.tif') as src1, rasterio.open('srtm_flipped.tif') as src2:
    b1, b2 = src1.bounds, src2.bounds
    assert (b1.bottom, b1.top) == (b2.top, b2.bottom), "Y extents not properly flipped"

subprocess.run(['gdaldem', 'aspect', 'srtm.tif', 'srtm_aspect.tif'], check=True)
subprocess.run(['gdaldem', 'aspect', 'srtm_flipped.tif', 'srtm_flipped_aspect.tif'], check=True)

_, axes = plt.subplots(2, 2, figsize=(12, 10))

with rasterio.open('srtm.tif') as src:
    rasterio.plot.show(src, ax=axes[0, 0], title='Original Elevation', cmap='turbo')

with rasterio.open('srtm_aspect.tif') as src:
    rasterio.plot.show(src, ax=axes[0, 1], title='Original Aspect', cmap='viridis', vmin=0, vmax=360)

with rasterio.open('srtm_flipped.tif') as src:
    rasterio.plot.show(src, ax=axes[1, 0], title='Flipped Elevation', cmap='turbo')
    axes[1, 0].invert_yaxis()

with rasterio.open('srtm_flipped_aspect.tif') as src:
    rasterio.plot.show(src, ax=axes[1, 1], title='Flipped Aspect', cmap='viridis', vmin=0, vmax=360)
    axes[1, 1].invert_yaxis()

for ax in axes.flat:
    ax.title.set_fontweight('normal')

plt.tight_layout()
plt.savefig('aspect_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
```

</p>
</details> 

### Versions and provenance

GDAL 3.10.3, released 2025/04/01

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
… on rotated for hillshade/slope/roughness)

Fixes #13100

### CODE REVIEW

**Comment by jratike80** [comment]
Title says "...wrong results on north-up.." Is is so or "...wrong results on non-north-up..."?

**Comment by rouault** [comment]
> Title says "...wrong results on north-up.." Is is so or "...wrong results on non-north-up..."?

indeed, fixed; Thanks

File: apps/gdaldem_lib.cpp [hunk 1]
```diff
@@ -3634,6 +3634,39 @@ GDALDatasetH GDALDEMProcessing(const char *pszDest, GDALDatasetH hSrcDataset,
 
     GDALDEMProcessingOptions *psOptions = psOptionsToFree.get();
 
+    double adfGeoTransform[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
+
+    // Keep that variable in that scope.
+    // A reference on that dataset will be taken by GDALGeneric3x3Dataset
+    // (and released at its destruction) if we go to that code path, and
+    // GDALWarp() (actually the VRTWarpedDataset) will itself takes a reference
```
Comment (elpaso) [inline apps/gdaldem_lib.cpp]:
```suggestion
    // GDALWarp() (actually the VRTWarpedDataset) will itself take a reference
```

**Review by elpaso — APPROVED** [review]

File: apps/gdaldem_lib.cpp (hunk 1 above)
Comment (rouault) [reply apps/gdaldem_lib.cpp]: fixed

**Comment by evetion** [comment]
Thanks for the quick and pragmatic fix. FWIW, I think only aspect was wrong before, slope and tpi should produce identical answers even if you rotate the raster.
