### PR TITLE
[odbc] Always request numeric column values as numeric types

### LINKED ISSUE #3885: OGR Access MDB Driver appears unable to parse certain numbers
## Expected behavior and actual behavior.
For some odd reason QGIS does not properly read some records from some columns of a vanilla/aspatial Access MDB when joined against a GPKG with mixed spatial/aspatial data.

## Steps to reproduce the problem.
Have GPKG with geometries and some tabular data joined against a completely vanilla/aspatial MDB
Note that some records in QGIS are not parsed/loaded correctly (For example, CAMP_Length)
Verify that these records can be recalled properly outside of QGIS/OGRinfo

## Operating system
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043

## GDAL version and provenance
GDAL 3.3.0 from OSGeo4W-NG

## Further Information
QGIS view:  
image
Note how many segments have a CAMP_Length of 0. This is not valid. Some records in the dataset are NULL, but they show properly as NULL.

Compare to the view in CAMP-RS:  
image

Compare to the view in MDBPlus:  
image

```
PS C:\OSGeo4W64\bin> .\ogrinfo.exe -fields=yes -sql "SELECT * FROM Inventory" Q:\User\Brett_Carlock\Projects\QGIS\Data\CAMP-RS\CAMP-RS.mdb > stdout 2> stderr
```

It looks like OGR isn't reading some of the values properly, at least according to stderr. I guess these are the ones that read out as 0 when they should not be.

It is tricky to pick out in the stdout because BEGIN_MP of 0 is totally valid, especially for a segment that begins that roadway (the milepoint of that roadway would normally begin at 0.0mi and increase from there). However, END_MP and LENGTH can NEVER be 0, so any records that OGR parses with those as 0 are erroneous. NULL is perfectly acceptable.

[stdout.txt](https://github.com/qgis/QGIS/files/6539643/stdout.txt)
[stderr.txt](https://github.com/qgis/QGIS/files/6539644/stderr.txt)

**Additional context**
Same dataset as Issue #43287 
https://github.com/qgis/QGIS/issues/43287#issuecomment-847312168

### PR DESCRIPTION
**Pull request by nyalldawson**
The MS Access ODBC driver can return incorrect values for REAL
columns requested using char types.

Fixes #3885

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rouault I've reworked this now, so that the numeric column values are stored natively as a double, and so there's no change in behaviour for the existing GetColData methods. (I.e. ODBC drivers need to be explicitly adapted to retrieve field values as doubles)

**Comment by nyalldawson** [comment]
@rouault I suspect these changes are bumping up into a bug in the SQL Server ODBC driver -- possibly this https://stackoverflow.com/questions/6242895/numeric-value-out-of-range-error-when-using-sqlfetch-with-sql-c-float .

I'm wondering what you think would be the best way to handle this. Options I can think of are:

- Having a setting on the CPLODBCStatement to set whether numeric values should always be retrieved as string, and setting this from the SQL Server driver
- Do the opposite, and make retrieval as numeric values opt-in. Use this for pgeo/odbc drivers but not sql server.
- Try to detect automatically in CPLODBCStatement if the problematic driver is in use. (But I can't think of a reliable way to do this, given that a valid DSN string might not include the driver name at all)

What's your thoughts?

**Comment by rouault** [comment]
> What's your thoughts?

I don't have much to be honest. Your current approach looks good on the paper, but looking at test results (crash on Windows on ogr_pgeo.py, or test failure in MSSQLSpatial on Ubuntu 18.04),  it seems we hit bugs in ODBC drivers if we ask a column for both as string and double/float. So perhaps the "make retrieval as numeric values opt-in. Use this for pgeo/odbc drivers but not sql server" ?

**Comment by nyalldawson** [comment]
@rouault I've reworked this so that the new behaviour is opt-in, and only enabled for MDB files and the Pgeo driver... let's see what the CI says!

File: ogr/ogrsf_frmts/odbc/ogrodbclayer.cpp [hunk 1]
```diff
@@ -260,17 +260,36 @@ OGRFeature *OGRODBCLayer::GetNextRawFeature()
...
-        const char *pszValue = poStmt->GetColData( iSrcField );
-
-        if( pszValue == nullptr )
-            poFeature->SetFieldNull( iField );
-        else if( poFeature->GetFieldDefnRef(iField)->GetType() == OFTBinary )
-            poFeature->SetField( iField,
-                                 poStmt->GetColDataLength(iSrcField),
-                                 (GByte *) pszValue );
+
+        if ( eType == OFTReal && poStmt->Flags() & CPLODBCStatement::Flag::RetrieveNumericColumnsAsDouble )
```
Comment (rouault) [inline ogr/ogrsf_frmts/odbc/ogrodbclayer.cpp:266]: just to avoid relying on operator precedence rules:
```suggestion
        if ( eType == OFTReal && (poStmt->Flags() & CPLODBCStatement::Flag::RetrieveNumericColumnsAsDouble) )
```

File: port/cpl_odbc.cpp [hunk 2]
```diff
@@ -1183,9 +1200,47 @@ int CPLODBCStatement::Fetch( int nOrientation, int nOffset )
 
         char szWrkData[513] = {};
 
+        // If RetrieveNumericColumnsAsDouble flag is set, then read numeric columns using numeric data types and populate native double column values array.
+        // This allows retrieval of the original numeric value as a double via GetColDataAsDouble with risk of loss of precision.
```
Comment (rouault) [inline port/cpl_odbc.cpp:1204]: I assume this is:
```suggestion
        // This allows retrieval of the original numeric value as a double via GetColDataAsDouble without risk of loss of precision.
```

**Comment by rouault** [comment]
rebasing on master will fix the failure in the build-mac cmake CI target (due to https://github.com/OSGeo/gdal/pull/5156 being applied)

**Comment by Saijin-Naib** [comment]
You all are the best, seriously. Thank you!
