### PR TITLE
TileDB: fix memleak writing multiple attributes (fixes #1498)

### LINKED ISSUE #1498: tiledb: Valgrind warning about invalid memory access on autotest
@normanb 
Spotted by
```~/install-valgrind-3.15.0/bin/valgrind --leak-check=full python /home/even/.local/bin/pytest ../autotest/gdrivers/tiledb_write.py```

```
 gdrivers/tiledb_write.py ✓✓✓                                                                                                                                                                         50% █████    
 ==27185== Invalid read of size 8
==27185==    at 0x4C328E4: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1035)
==27185==    by 0x23D110B6: tiledb::sm::Buffer::write(void const*, unsigned long) (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23F0240F: tiledb::sm::Tile::write(void const*, unsigned long) (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23E56797: tiledb::sm::Writer::prepare_full_tiles_fixed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, std::vector<tiledb::sm::Tile, std::allocator<tiledb::sm::Tile> >*) const (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23E573D0: tiledb::sm::Writer::prepare_full_tiles(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, std::vector<tiledb::sm::Tile, std::allocator<tiledb::sm::Tile> >*) const (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23EACA6D: void tbb::interface9::internal::dynamic_grainsize_mode<tbb::interface9::internal::adaptive_mode<tbb::interface9::internal::auto_partition_type> >::work_balance<tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, tbb::internal::parallel_for_body<std::vector<tiledb::sm::Status, std::allocator<tiledb::sm::Status> > tiledb::sm::parallel_for<tiledb::sm::Status tiledb::sm::Writer::global_write<unsigned long>()::{lambda(unsigned long)#1}>(unsigned long, unsigned long, tiledb::sm::Status tiledb::sm::Writer::global_write<unsigned long>()::{lambda(unsigned long)#1} const&)::{lambda(unsigned long)#1}, unsigned long>, tbb::auto_partitioner const>, tbb::blocked_range<unsigned long> >(std::vector<tiledb::sm::Status, std::allocator<tiledb::sm::Status> >&, tbb::blocked_range<unsigned long>&) (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23EACE52: tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, tbb::internal::parallel_for_body<std::vector<tiledb::sm::Status, std::allocator<tiledb::sm::Status> > tiledb::sm::parallel_for<tiledb::sm::Status tiledb::sm::Writer::global_write<unsigned long>()::{lambda(unsigned long)#1}>(unsigned long, unsigned long, tiledb::sm::Status tiledb::sm::Writer::global_write<unsigned long>()::{lambda(unsigned long)#1} const&)::{lambda(unsigned long)#1}, unsigned long>, tbb::auto_partitioner const>::execute() (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23F18580: tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) (custom_scheduler.h:509)
==27185==    by 0x23F160CF: tbb::internal::generic_scheduler::local_spawn_root_and_wait(tbb::task*, tbb::task*&) (scheduler.cpp:670)
==27185==    by 0x23E6FB7E: tiledb::sm::Status tiledb::sm::Writer::global_write<unsigned long>() (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23E54C4A: tiledb::sm::Writer::global_write() (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==    by 0x23E57902: tiledb::sm::Writer::write() (in /home/even/install-tiledb-1.5.0/lib/libtiledb.so)
==27185==  Address 0x4820b040 is 0 bytes inside a block of size 262,144 free'd
==27185==    at 0x4C2EF90: free (vg_replace_malloc.c:540)
==27185==    by 0x218F70CE: VSIFree (cpl_vsisimple.cpp:873)
==27185==    by 0x216822B6: TileDBRasterBand::IWriteBlock(int, int, void*) (tiledbdataset.cpp:369)
==27185==    by 0x217CD118: GDALRasterBlock::Write() (gdalrasterblock.cpp:839)
==27185==    by 0x2173ABC0: GDALArrayBandBlockCache::FlushBlock(int, int, int) (gdalarraybandblockcache.cpp:436)
==27185==    by 0x2173A694: GDALArrayBandBlockCache::FlushCache() (gdalarraybandblockcache.cpp:275)
==27185==    by 0x217BE838: GDALRasterBand::FlushCache() (gdalrasterband.cpp:1030)
==27185==    by 0x217550F1: GDALDataset::FlushCache() (gdaldataset.cpp:427)
==27185==    by 0x217AE7B7: GDALPamDataset::FlushCache() (gdalpamdataset.cpp:171)
==27185==    by 0x216824BA: TileDBDataset::~TileDBDataset() (tiledbdataset.cpp:434)
==27185==    by 0x216826FB: TileDBDataset::~TileDBDataset() (tiledbdataset.cpp:456)
==27185==    by 0x21759ED1: GDALClose (gdaldataset.cpp:3565)
==27185==  Block was alloc'd at
==27185==    at 0x4C2DE96: malloc (vg_replace_malloc.c:309)
==27185==    by 0x218F7088: VSIMalloc (cpl_vsisimple.cpp:561)
==27185==    by 0x21682050: TileDBRasterBand::IWriteBlock(int, int, void*) (tiledbdataset.cpp:333)
==27185==    by 0x217CD118: GDALRasterBlock::Write() (gdalrasterblock.cpp:839)
==27185==    by 0x2173ABC0: GDALArrayBandBlockCache::FlushBlock(int, int, int) (gdalarraybandblockcache.cpp:436)
==27185==    by 0x2173A694: GDALArrayBandBlockCache::FlushCache() (gdalarraybandblockcache.cpp:275)
==27185==    by 0x217BE838: GDALRasterBand::FlushCache() (gdalrasterband.cpp:1030)
==27185==    by 0x217550F1: GDALDataset::FlushCache() (gdaldataset.cpp:427)
==27185==    by 0x217AE7B7: GDALPamDataset::FlushCache() (gdalpamdataset.cpp:171)
==27185==    by 0x216824BA: TileDBDataset::~TileDBDataset() (tiledbdataset.cpp:434)
==27185==    by 0x216826FB: TileDBDataset::~TileDBDataset() (tiledbdataset.cpp:456)
==27185==    by 0x21759ED1: GDALClose (gdaldataset.cpp:3565)
```

### PR DESCRIPTION
**Pull request by normanb**
## What does this PR do?

When writing multiple attributes to TileDB they were being freed before the query was submitted. This copies the pattern in `CreateCopy` of caching these blocks in a vector and then calling `VSIFree`

## What are related issues/pull requests?

https://github.com/OSGeo/gdal/issues/1498

## Tasklist

 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

File: gdal/frmts/tiledb/tiledbdataset.cpp [hunk 1]
```diff
@@ -331,9 +333,13 @@ CPLErr TileDBRasterBand::IWriteBlock( int nBlockXOff,
             int nBytes = GDALGetDataTypeSizeBytes( eAttrType );
             int nValues = nBlockXSize * nBlockYSize;
             void* pAttrBlock = VSIMalloc( nBytes * nValues );
+            aBlocks.push_back( pAttrBlock );
```
Comment (mloskot) [inline gdal/frmts/tiledb/tiledbdataset.cpp]: I'd make use of RAII

1. `std::vector<std::unique_ptr<void, decltype(&VSIFree)>> aBlocks;`
2. aBlocks.emplace_back(pAttrBlock, &VSIFree);

and remove all the `for ( auto pBlk: aBlocks )` as no longer necessary.

Quick comment w/o checking the wider scope, so may be invalid.

Comment (normanb) [reply gdal/frmts/tiledb/tiledbdataset.cpp]: @mloskot thanks, I will make that change
