### PR TITLE
VSICACHE: avoid EOF read

### LINKED ISSUE #9658: VSI_CACHE causing bad range requests in some circumstance (/vsizip//vsis3/)
### What is the bug?

I have a 4211788 byte (4MiB) zip file containing a ~10MiB tiff file in an S3 bucket.
I'm using gdal from python to open the last tiff file in the zip file.
The following works perfectly for me:
`gdal.Open("/vsizip//vsis3/cdn-misc.kx.gd/foss-tickets/file_example_TIFF_10MB.zip", gdal.GA_ReadOnly)`
However if I first turn on the VSI cache with `gdal.SetConfigOption("VSI_CACHE", "TRUE")`
Then it fails with:
`S3: Request at offset 4227072, after end of file`
Note that this *is* after the end of the file, and that it corresponds to the start of the 129th cache block - VSI cache blocks default to 32KiB in size.
So, it looks like the VSI cache is for some reason requesting a block outside the file.

I found out this works with `/vsizip//vsicurl/` too, not just `/vsizip/vsis3/`

### Steps to reproduce the issue

I've only figured out how to show this from python so far.
```
from osgeo import gdal

gdal.UseExceptions()

opts = {
    'VSI_CACHE': 'TRUE',
    'CPL_DEBUG': 'ON',
}

for k, v in opts.items():
    gdal.SetConfigOption(k, v)

# Use either /vsizip//vsis3/
path = '/vsizip//vsis3/cdn-misc.kx.gd/foss-tickets/file_example_TIFF_10MB.zip'
# or /vsizip//vsicurl/
path = '/vsizip//vsicurl/https://cdn-misc.kx.gd/foss-tickets/file_example_TIFF_10MB.zip'

gdal_tile = gdal.Open(path, gdal.GA_ReadOnly)
gdal_tile = None
```

You should see one or other of the following:
`S3: Request at offset 4227072, after end of file`
`VSICURL: Request at offset 4227072, after end of file`

I think in this case the program succeeds anyway in spite of trying to read beyond the end of the file, but I'm not sure if that's always the case.

### Versions and provenance

macOS Sonoma 14.3.1
GDAL 3.8.5

### Additional context

Wasn't too hard to make a new test file that exhibits this behaviour, so I think this must be affecting the majority of zip files, at least when the vsi-cache is on and the user tries to access the last file in the zip.

### PR DESCRIPTION
**Pull request by elpaso**
Do not read past EOF even if the client (e.g. VSIZIP) code say so.

Fix #9658

### CODE REVIEW

File: port/cpl_vsil_cache.cpp [hunk 1]
```diff
@@ -360,8 +360,15 @@ size_t VSICachedFile::Read(void *pBuffer, size_t nSize, size_t nCount)
...
-    const vsi_l_offset nEndBlock =
-        (m_nOffset + nRequestedBytes - 1) / m_nChunkSize;
+    // Calculate last block
+    const vsi_l_offset nLastBlock = m_nFileSize / m_nChunkSize;
+    vsi_l_offset nEndBlock = (m_nOffset + nRequestedBytes - 1) / m_nChunkSize;
+
+    // if nLastBlock is not 0 consider the min value to avoid out-of-range reads
+    if (nLastBlock != 0 && nEndBlock > nLastBlock)
+    {
+        nEndBlock = nLastBlock;
```
Comment (rouault) [inline port/cpl_vsil_cache.cpp:370]: is this code path exercised by existing tests?

Comment (elpaso) [reply port/cpl_vsil_cache.cpp:370]: I don't know. I was thinking at a test but I have no idea where to reproduce this scenario with vsicache and vsicurl in a test.

Comment (rouault) [reply port/cpl_vsil_cache.cpp:370]: Perhaps add an assertion and run autotest/gcore/vsifile.py ? There are tests in it with VSI_CACHE=YES

> but I have no idea how to reproduce this scenario with vsicache and vsicurl in a test.

Testing on a regular file should be enough

Comment (elpaso) [reply port/cpl_vsil_cache.cpp:370]: ok, done. But without using curl there is no way to catch the error message that was triggered by curl, so the test will always pass. 
The new code path is triggered by the test though.

Comment (rouault) [reply port/cpl_vsil_cache.cpp:370]: I was thinking to a simpler test that would not involve zip or tiff, but just use the VSILFILE API and issue a gdal.VSIFReadL() with a size bigger than the the file size.

Something like:
```
f = gdal.VSIFOpenL(tmp_filename, "wb")
gdal.VSIFWriteL(b"x" * 100000, 100000, 1, f)
gdal.VSIFCloseL(f)
with gdal.config_option("VSI_CACHE", "YES"):
    f = gdal.VSIFReadL(tmp_filename, "rb")
    gdal.VSIFSeekL(f, 60000, 0)
    data = gdal.VSIFReadL(1, 75000, f)  # reads past end of file
    gdal.VSIFCloseL(f)
    assert data == b"x" * 40000
```

Comment (elpaso) [reply port/cpl_vsil_cache.cpp:370]: ok, test updated and verified that it triggers the new code path.

**Comment by olsen232** [comment]
The 4MB zip file I attached to #9658 was just an example to demonstrate the bug, but this was causing me real-world issues opening TIFFs from a 4GB zip that I haven't uploaded here - today I've verified that this fixes the real-world issue for me.
