### PR TITLE
Warping and VRT derived overview related fixes

### LINKED ISSUE #13074: VRT mask corrupted for uint16 dataset
### What is the bug?

I'm creating tile images from a VRT. The VRT extracts bands from two sources: a six band uint16 GeoTIFF with R, G and B bands among others. Additionally, the VRT creates a mask band from a float32 GeoTIFF (elevation data), masking pixels with elevation below a threshold. The resulting imagery is only partially correctly masked: part of the image seems to be unmasked:

Image

Notice the sharp, straight line in the mask about a third into the image from the left. As reference, here's a grayscale version of the elevation data used: it has no such sharp difference at this location:

Image

Just looking at the mask band, it looks like this:

Image

Interestingly, doing the same operation with uint8 RGB imagery as input, using the same masking logic, does not produce these artifacts (at least not in any example we've seen so far).

### Steps to reproduce the issue

VRT XML:

```xml
<VRTDataset rasterXSize="12395" rasterYSize="11978">
    <SRS>EPSG:4326</SRS>
    <GeoTransform>13.097663923853693,6.250634549453937e-07,0.0,58.34381328587637,0.0,-3.286736983052987e-07</GeoTransform>
    <VRTRasterBand band="1" dataType="uint16">
        <NoDataValue>65535</NoDataValue>
        <SimpleSource>
            <SourceFilename>/vsis3/solvi-production/public/gdal-mask-test.tiff</SourceFilename>
            <SourceBand>1</SourceBand>
        </SimpleSource>
    </VRTRasterBand>
    <VRTRasterBand band="2" dataType="uint16">
        <NoDataValue>65535</NoDataValue>
        <SimpleSource>
            <SourceFilename>/vsis3/solvi-production/public/gdal-mask-test.tiff</SourceFilename>
            <SourceBand>2</SourceBand>
        </SimpleSource>
    </VRTRasterBand>
    <VRTRasterBand band="3" dataType="uint16">
        <NoDataValue>65535</NoDataValue>
        <SimpleSource>
            <SourceFilename>/vsis3/solvi-production/public/gdal-mask-test.tiff</SourceFilename>
            <SourceBand>3</SourceBand>
        </SimpleSource>
    </VRTRasterBand>
    <VRTRasterBand band="4" dataType="uint16">
        <NoDataValue>65535</NoDataValue>
        <SimpleSource>
            <SourceFilename>/vsis3/solvi-production/public/gdal-mask-test.tiff</SourceFilename>
            <SourceBand>4</SourceBand>
        </SimpleSource>
    </VRTRasterBand>
    <VRTRasterBand band="5" dataType="uint16">
        <NoDataValue>65535</NoDataValue>
        <SimpleSource>
            <SourceFilename>/vsis3/solvi-production/public/gdal-mask-test.tiff</SourceFilename>
            <SourceBand>5</SourceBand>
        </SimpleSource>
    </VRTRasterBand>
    <VRTRasterBand band="6" dataType="uint16">
        <NoDataValue>65535</NoDataValue>
        <SimpleSource>
            <SourceFilename>/vsis3/solvi-production/public/gdal-mask-test.tiff</SourceFilename>
            <SourceBand>6</SourceBand>
        </SimpleSource>
    </VRTRasterBand>
    <MaskBand>
        <VRTRasterBand dataType="Byte" subClass="VRTDerivedRasterBand">
            <PixelFunctionType>reclassify</PixelFunctionType>
            <PixelFunctionLanguage>Python</PixelFunctionLanguage>
            <PixelFunctionCode>
import numpy as np
def reclassify(in_ar, out_ar, xoff, yoff, xsize, ysize, raster_xsize, raster_ysize, buf_radius, gt, **kwargs):
    out_ar[:] = (in_ar[0] >= 0.21080050411).astype(np.uint8) * 255
            </PixelFunctionCode>
            <SourceTransferType>Float32</SourceTransferType>
            <SimpleSource>
                <SourceFilename relativeToVRT="1">/vsis3/solvi-production/public/gdal-mask-test-chm.tiff</SourceFilename>
                <SourceBand>1</SourceBand>
                <Resampling>nearest</Resampling>
                <SrcRect xOff="518.0035080872476" yOff="403.2228782325983" xSize="3098.789229683578" ySize="2994.505055077374" />
                <DstRect xOff="0" yOff="0" xSize="12395" ySize="11978" />
            </SimpleSource>
        </VRTRasterBand>
    </MaskBand>
    <OverviewList>2 4 8 16 32 64 128 256</OverviewList>
</VRTDataset>
```

Python code to extract image tile (we use some quite different code in production, using rasterio, but it gives same same corruption):

```python
import os
import numpy as np
from osgeo import gdal, osr


def linear_rescale(image, in_range=(0, 1), out_range=(1, 255)):
    imin, imax = in_range
    omin, omax = out_range
    image = np.clip(image, imin, imax) - imin
    image = image / float(imax - imin)
    return image * (omax - omin) + omin


def save_tile_as_png(filename, rasters, mask=None):
    """
    Save rasters (+ optional mask) as PNG using GDAL.
    rasters: (bands, height, width), uint8
    mask: (height, width), uint8 (0/255) -> alpha channel
    """
    if rasters.ndim != 3:
        raise ValueError("rasters must be (bands, height, width)")

    bands, height, width = rasters.shape
    if mask is not None:
        bands_out = bands + 1
    else:
        bands_out = bands

    if bands_out not in (1, 2, 3, 4):
        raise ValueError(f"PNG supports 1, 2, 3, or 4 bands (got {bands_out})")

    if rasters.dtype != np.uint8:
        rasters = rasters.astype(np.uint8)

    mem_driver = gdal.GetDriverByName("MEM")
    mem_ds = mem_driver.Create("", width, height, bands_out, gdal.GDT_Byte)

    for i in range(bands):
        mem_ds.GetRasterBand(i + 1).WriteArray(rasters[i])

    if mask is not None:
        alpha_band = mem_ds.GetRasterBand(bands_out)
        alpha_band.WriteArray(mask)
        alpha_band.SetColorInterpretation(gdal.GCI_AlphaBand)

    png_driver = gdal.GetDriverByName("PNG")
    png_driver.CreateCopy(filename, mem_ds, strict=0)

    mem_ds = None


# Enable GDAL Python VRTs
os.environ["GDAL_VRT_ENABLE_PYTHON"] = "YES"


def tile_gdal(
    src_path, bounds, tile_size=256, data_range=(400, 4000), output_bands=(2, 1, 0)
):
    def world_to_pixel(x, y, inv_gt):
        px = inv_gt[0] + inv_gt[1] * x + inv_gt[2] * y
        py = inv_gt[3] + inv_gt[4] * x + inv_gt[5] * y
        return (px, py)

    src_ds = gdal.Open(src_path)
    dst_crs = osr.SpatialReference()
    dst_crs.ImportFromEPSG(3857)

    warp_options = gdal.WarpOptions(dstSRS=dst_crs, format="VRT")
    vrt_ds = gdal.Warp("", src_ds, options=warp_options)

    gt = vrt_ds.GetGeoTransform()
    inv_gt = gdal.InvGeoTransform(gt)

    xmin, ymin, xmax, ymax = bounds

    ll = world_to_pixel(xmin, ymin, inv_gt)
    ul = world_to_pixel(xmin, ymax, inv_gt)
    ur = world_to_pixel(xmax, ymax, inv_gt)

    xoff = int(ll[0])
    yoff = int(ul[1])
    xsize = int(ur[0] - ll[0])
    ysize = int(ll[1] - ul[1])

    tile = []
    for b in [b + 1 for b in output_bands]:
        band = vrt_ds.GetRasterBand(b)
        arr = band.ReadAsArray(
            xoff,
            yoff,
            xsize,
            ysize,
            tile_size,
            tile_size,
        )
        tile.append(arr)

    tile = np.stack(tile)

    mask_band = vrt_ds.GetRasterBand(1).GetMaskBand()
    mask = mask_band.ReadAsArray(xoff, yoff, xsize, ysize, tile_size, tile_size)
    tile_rescaled = linear_rescale(tile, in_range=data_range)

    rasters = np.stack([tile_rescaled[i] for i in range(len(output_bands))])

    return rasters, mask


rasters, mask = tile_gdal(
    "weird-mask.vrt",
    (1458265.6256245933, 8039493.760978268, 1458418.4996811638, 8039646.635034839),
)

save_tile_as_png("rgb.png", rasters.astype(np.uint8), mask)
```

(Adjust paths as necessary in the last two calls to control VRT and output location.)

Since this appears to be some sort of corruption, I'm not 100% the bounds used will always give the results shown above: in production we get similar but not identical artifacts depending on location and zoom.

Also, apologies in advance if the code above is unnecessarily complex, I don't routinely use the Python gdal bindings.

### Versions and provenance

Tested on Debian bullseye and Ubuntu 24.04. GDAL version 3.10.3 and 3.11.3, both built from source locally.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13074 which exhibits 2 independent issues:
- warper: when source nodata is set and per-dataset mask band exists, ignore the later, and raise a warning message
- VRTDerivedRasterBand: avoid infinite recursion with virtual overviews

(the warper change is probably not appropriate for the 3.11 branch)

### CODE REVIEW

File: alg/gdalwarpoperation.cpp [hunk 1]
```diff
@@ -437,6 +437,18 @@ int GDALWarpOperation::ValidateOptions()
...
+    GDALRasterBandH hSrcBand =
+        GDALGetRasterBand(psOptions->hSrcDS, psOptions->panSrcBands[0]);
+    if (GDALGetMaskFlags(hSrcBand) == GMF_PER_DATASET &&
+        psOptions->padfSrcNoDataReal != nullptr)
+    {
+        CPLError(
+            CE_Warning, CPLE_AppDefined,
+            "Source dataset has both a per-dataset mask band and the warper "
+            "has been also configured with a source nodata value. Only taking "
+            "into account the later (i.e. ignoring the per-dataset mask band)");
```
Comment (dbaston) [inline alg/gdalwarpoperation.cpp]:
```suggestion
            "into account the latter (i.e. ignoring the per-dataset mask band)");
```

Comment (rouault) [reply alg/gdalwarpoperation.cpp]: fixed
