### PR TITLE
GEOJSON: fix mixed type field not flagged as JSON if first occurrence is a string  (fixes #7313)

### LINKED ISSUE #7313: JSON: mixed type field not flagged as JSON if first is a string
Also see: https://github.com/qgis/QGIS/issues/51911

```json
{ "type": "FeatureCollection",
  "features": [
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": "astring"}
      },
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": 42}
      },
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": {"nested": 75}}
      }
    ]
  }
```

`ogrinfo -al -q test_string_first.json`

```bash
OGRFeature(gh_51911_string_first):0
  prop0 (String) = astring
  POINT (102.0 0.5)

OGRFeature(gh_51911_string_first):1
  prop0 (String) = 42
  POINT (102.0 0.5)

OGRFeature(gh_51911_string_first):2
  prop0 (String) = { "nested": 75 }
  POINT (102.0 0.5)
```

But, moving the string at the second place:

```json
{ "type": "FeatureCollection",
  "features": [
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": 42}
      },
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": "astring"}
      },
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": {"nested": 75}}
      }
    ]
  }
```

`ogrinfo -al -q test_string_second.json`

```bash
Layer name: gh_51911
OGRFeature(gh_51911):0
  prop0 (String(JSON)) = 42
  POINT (102.0 0.5)

OGRFeature(gh_51911):1
  prop0 (String(JSON)) = astring
  POINT (102.0 0.5)

OGRFeature(gh_51911):2
  prop0 (String(JSON)) = { "nested": 75 }
  POINT (102.0 0.5)
```

### PR DESCRIPTION
**Pull request by elpaso**
Set the field subtype to OFSTJSON even when the first occurrence of the field was a string.

fixes #7313

### CODE REVIEW

File: ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp [hunk 1]
```diff
@@ -1934,7 +1934,13 @@ void OGRGeoJSONReaderAddOrUpdateField(
             if (eSubType == OFSTNone)
             {
                 if (eNewType == OFTStringList)
+                {
                     poFDefn->SetType(OFTStringList);
+                }
+                else if (eNewType == OFTInteger)
```
Comment (rouault) [inline ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp:1940]: what about OFTInteger64, OFTReal, and probably other types ?
Shouldn't that be:
```suggestion
                else if (eNewType != OFTString)
```

Comment (elpaso) [reply ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp:1940]: Correct, test case added for real.

**Comment by rouault** [comment]
(if you get a failure on a Mac CI, you may need to rebase on top of latest master, to get https://github.com/OSGeo/gdal/commit/3cbfb79d7194589974c7ba235d9278dbb7a4f0e7, but that may not be necessary as you've pushed after I committed it)
