### PR TITLE
TileDB: support multiple attribute names in dataset metadata (fixes #1493)

### LINKED ISSUE #1493: When writing multiple co-registered attributes to a TileDB dataset, only the last attribute name is recorded in the dataset metadata.
## Expected behavior and actual behavior.

When writing multiple co-registered datasets to a TileDB dataset, only the last attribute name is recorded in the dataset level metadata.

## Steps to reproduce the problem.

Not easy to reproduce without a lot of additional datasets. I have added a test to the test suite to recreate the issue and a PR will be issued.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

Master - GDAL 2.6.0dev-26342f736f-dirty, released 2019/04/30

### PR DESCRIPTION
**Pull request by normanb**
## What does this PR do?

Enables support for multiple attribute names when co-registering datasets with TileDB datasets.

## What are related issues/pull requests?

https://github.com/OSGeo/gdal/pull/1483

## Tasklist

 - [X] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

File: gdal/frmts/tiledb/tiledbdataset.cpp [hunk 1]
```diff
@@ -1768,23 +1768,29 @@ TileDBDataset::Create( const char * pszFilename, int nXSize, int nYSize, int nBa
...
-                CPLString().Printf( "%d", poDS->eDataType ),
-                "IMAGE_STRUCTURE" );
-
-        poDS->SetMetadataItem( "X_SIZE", CPLString().Printf( "%d", poDS->nRasterXSize ), "IMAGE_STRUCTURE" );
-        poDS->SetMetadataItem( "Y_SIZE", CPLString().Printf( "%d", poDS->nRasterYSize ), "IMAGE_STRUCTURE" );
+        char** papszImageStruct = nullptr;
+        papszImageStruct = CSLAddNameValue(papszImageStruct, "NBITS",
+                        CPLString().Printf( "%d", poDS->nBitsPerSample ) );
+        papszImageStruct = CSLAddNameValue(papszImageStruct, "DATA_TYPE",
+                        CPLString().Printf( "%d", poDS->eDataType ) );
```
Comment (rouault) [inline gdal/frmts/tiledb/tiledbdataset.cpp]: I didn't note that previously, but serializing the enumeration value as a integer is rather user (or perhaps here developer :-)) unfriendly. Maybe using GDALGetDataTypeName() would be more appropriate ?

Comment (normanb) [reply gdal/frmts/tiledb/tiledbdataset.cpp]: I have added backwards compatibility for 2.5.0 and changed the code to write strings for the data types.
