### PR TITLE
Make 'gdal raster/vector clip' work with --like dataset being a PostgreSQL (vector) dataset

### LINKED ISSUE #13091: CLI: gdal raster clip - fails to clip raster using PG vector data source
### What is the bug?

Clip fails when clipping vector data source is from PostgreSQL/PostGIS. Works fine with .gpkg clipping source.

gdal raster clip \
   --input=raster.tif \
   --like="PG:dbname=mydb" --like-sql="select geom from vector_table" \
   --output=clipped.tif --overwrite --progress

It gives the error:
ERROR 1: clip: Cannot get extent from clip dataset 

Per Even, the following work-around does indeed correct the issue:
--config GDAL_SKIP=PostGISRaster

Full discussion from listserver:
https://lists.osgeo.org/pipermail/gdal-dev/2025-September/060919.html

Thank you!

### Steps to reproduce the issue

gdal raster clip \
   --input=raster.tif \
   --like="PG:dbname=mydb" --like-sql="select geom from vector_table" \
   --output=clipped.tif --overwrite --progress

### Versions and provenance

Debian 12, GDAL 3.11.3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13091

### CODE REVIEW

File: gcore/gdalalgorithm.cpp [hunk 1]
```diff
@@ -2589,6 +2589,27 @@ bool GDALAlgorithm::ProcessDatasetArg(GDALAlgorithmArg *arg,
                 m_oMapDatasetNameToDataset.erase(oIter);
             }
 
+            // A bit of a hack for situations like 'gdal raster clip --like "PG:..."'
+            // where the PG: dataset will be first opened with the PostGISRaster
+            // driver whereas the PostgreSQL (vector) one is actually wanted.
+            if (poDS->GetRasterCount() == 0 && (flags & GDAL_OF_RASTER) != 0 &&
+                (flags & GDAL_OF_VECTOR) != 0 && aosAllowedDrivers.empty() &&
+                aosOpenOptions.empty())
```
Comment (elpaso) [inline gcore/gdalalgorithm.cpp:2597]: why to check for OO empty?

Comment (rouault) [reply gcore/gdalalgorithm.cpp:2597]: I wasn't too sure if it was appropriate to test another driver with the open options that could have been set for another one. In the particular case of the original issue, the --like operator doesn't support passing open options anyway...

**Comment by rouault** [comment]
The backport to `release/3.11` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply a5158c313b... Make 'gdal raster/vector clip' work with --like dataset being a PostgreSQL (vector) dataset
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/utilities/test_gdalalg_raster_clip.py
Auto-merging gcore/gdalalgorithm.cpp
CONFLICT (content): Merge conflict in gcore/gdalalgorithm.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.11 release/3.11
# Navigate to the new working tree
cd .worktrees/backport-release/3.11
# Create a new branch
git switch --create backport-13104-to-release/3.11
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick a5158c313b1a7de6e5814942727c85a13dc55e91
# Push it to GitHub
git push --set-upstream origin backport-13104-to-release/3.11
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.11
```
Then, create a pull request where the `base` branch is `release/3.11` and the `compare`/`head` branch is `backport-13104-to-release/3.11`.

**Comment by rouault** [comment]
cherry picked to 3.11 per 813b7072f3a03ec1e7f278e276a13ee24028aaa8
