### PR TITLE
OGRLayer::CreateFieldFromArrow/WriteArrowBatch: support Arrow string view type

### LINKED ISSUE #13942: Creating OGR dataset via Arrow that contains string view columns fails
### Feature description

With apologies for a not purely GDAL reproducer, I think that the newish string view (and binary view) data types are possibly not supported in the arrow writer interface for GDAL/OGR.

```python
import pyogrio.raw
import pyarrow as pa
import geoarrow.pyarrow as ga

tab = pa.table(
    {
        "col": pa.array(["foofy"], pa.string_view()),
        "geometry": ga.as_wkb(["POINT (0 1)"]),
    }
)

pyogrio.raw.write_arrow(tab, "foofy.fgb", geometry_type="Point")
# > FieldError: Error while creating field from Arrow for field 0 with name 'col' and type vu (Type 'vu' for field col is not supported.).
```

The error is coming from pyogrio, but I think the failure is from `OGR_L_CreateFieldFromArrowSchema()`.

https://github.com/geopandas/pyogrio/blob/3b2d40273b501c10ecf46cbd37c6e555754c89af/pyogrio/_io.pyx#L3092-L3099

The view types are a tiny bit different than the pure string representation, inlining strings less than 12 bytes and offloading longer strings into one or more "variaidic" buffers. I don't think there's any need to produce these but libraries like DataFusion, DuckDB, and Polars are producing them more frequently because they align more closely with the internal representation of strings in the database.

https://github.com/apache/arrow-nanoarrow/blob/36546d105b3bdcb936a93d3f5854419026630e04/src/nanoarrow/common/inline_array.h#L518-L537

https://github.com/apache/arrow-nanoarrow/blob/36546d105b3bdcb936a93d3f5854419026630e04/src/nanoarrow/common/array.c#L800-L810

https://github.com/apache/arrow-nanoarrow/blob/36546d105b3bdcb936a93d3f5854419026630e04/src/nanoarrow/common/inline_array.h#L1129-L1141

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13942

### CODE REVIEW

File: ogr/ogrfeature.cpp [hunk 1]
```diff
@@ -4465,6 +4465,59 @@ void OGRFeature::SetField(int iField, const char *pszValue)
...
+            static_cast<char *>(VSI_MALLOC_VERBOSE(svValue.size() + 1));
+        if (pauFields[iField].String)
+        {
+            memcpy(pauFields[iField].String, svValue.data(), svValue.size());
+            pauFields[iField].String[svValue.size()] = 0;
+        }
+        else
+        {
+            OGR_RawField_SetUnset(&pauFields[iField]);
+        }
```
Comment (paleolimbot) [inline ogr/ogrfeature.cpp:4513]: Is `OGR_RawField_SetUnset(&pauFields[iField]);` the correct thing to do when `VSI_MALLOC_VERBOSE()` evaluates to `nullptr`?

Comment (rouault) [reply ogr/ogrfeature.cpp:4513]: > I can also give this a try based on this PR

would be welcome

> the correct thing to do when `VSI_MALLOC_VERBOSE()` evaluates to `nullptr`?

yes, that's what we do in other similar code paths
