### PR TITLE
GTI: make relative filenames in XML or .gti.gpkg relative to the main file

### LINKED ISSUE #14344: GTI XML files do not search for relative file paths
### What is the bug?

I made a GTI XML at https://github.com/pedros007/gdal-gti-sample to test how the GTI XML can point to overviews of overviews.   It works great for [sample_gti.xml](https://github.com/pedros007/gdal-gti-sample/blob/main/data/sample_gti.xml).  However, it seems the file paths must either be relative or run from the same directory.

### Steps to reproduce the issue

If I change my XML to:

```patch
diff --git a/data/sample_gti.xml b/data/sample_gti.xml
index fa13c01..3faeac3 100644
--- a/data/sample_gti.xml
+++ b/data/sample_gti.xml
@@ -1,18 +1,18 @@
 <GDALTileIndexDataset>
-    <IndexDataset>/tmp/gdal-gti-sample/data/z13_gti.gpkg</IndexDataset>
+    <IndexDataset>z13_gti.gpkg</IndexDataset>

     <Overview><Factor>2</Factor></Overview>
     <Overview><Factor>4</Factor></Overview>
     <Overview><Factor>8</Factor></Overview>
     <Overview><Factor>16</Factor></Overview>
     <Overview>
-      <Dataset>GTI:/tmp/gdal-gti-sample/data/z8_gti.gpkg</Dataset>
+      <Dataset>z8_gti.gpkg</Dataset>
       <Factor>32</Factor>
       <Factor>64</Factor>
       <Factor>128</Factor>
     </Overview>
     <Overview>
-      <Dataset>GTI:/tmp/gdal-gti-sample/data/z4_gti.gpkg</Dataset>
+      <Dataset>z4_gti.gpkg</Dataset>
       <Factor>256</Factor>
       <Factor>512</Factor>
       <Factor>1024</Factor>
```

Then if I run gdalinfo inside the data dir it works great:

    cd data && gdalinfo sample_gti.xml
    Driver: GTI/GDAL Raster Tile Index
    ...

However, if I run outside the directory it gets confused:

    gdalinfo data/sample_gti.xml
    ERROR 4: z13_gti.gpkg: No such file or directory
    gdalinfo failed - unable to open 'data/sample_gti.xml’

I would have expected the driver to have a search path relative to the XML file itself.

### Versions and provenance

Tested with ghcr.io/osgeo/gdal:ubuntu-full-3.12.2 `GDAL 3.12.2 "Chicoutimi", released 2026/02/03`.

### Additional context

Could this also work when data lives at `/vsicurl/` locations?  That is, if data lives at `/vsicurl/http://example.com/test.xml` but it references a file `z13.gpkg`, would it construct the URL `/vsicurl/http://example.com/z13.gpkg`?

### PR DESCRIPTION
**Pull request by rouault**
Fixes #14344

### CODE REVIEW

**Review by pedros007 — APPROVED** [review]
I have not had a chance to run this yet, but glancing at the diff & new tests I think it will solve the problem I was facing. Thanks!

File: frmts/gti/gdaltileindexdataset.cpp [hunk 1]
```diff
@@ -2907,8 +2930,28 @@ void GDALTileIndexDataset::LoadOverviews()
...
             }
 
+            std::string osResolvedDSName(osDSName);
+            if (!m_osBaseDir.empty() && !osResolvedDSName.empty() &&
+                CPLIsFilenameRelative(osResolvedDSName.c_str()))
+            {
+                if (cpl::starts_with(osResolvedDSName, "GTI:"))
+                {
+                    osResolvedDSName =
+                        "GTI:" + CPLFormFilenameSafe(m_osBaseDir.c_str(),
```
Comment (elpaso) [inline frmts/gti/gdaltileindexdataset.cpp]:
```suggestion
                        GTI_PREFIX + CPLFormFilenameSafe(m_osBaseDir.c_str(),
```

File: frmts/gti/gdaltileindexdataset.cpp [hunk 2]
```diff
@@ -2907,8 +2930,28 @@ void GDALTileIndexDataset::LoadOverviews()
...
+                                                     osResolvedDSName.c_str() +
+                                                         strlen("GTI:"),
```
Comment (elpaso) [inline frmts/gti/gdaltileindexdataset.cpp]:
```suggestion
                                                         strlen(GTI_PREFIX),
```

File: frmts/gti/gdaltileindexdataset.cpp [hunk 3]
```diff
@@ -2907,8 +2930,28 @@ void GDALTileIndexDataset::LoadOverviews()
                 aosNewOpenOptions.SetNameValue("@LAYER", osLyrName.c_str());
             }
 
+            std::string osResolvedDSName(osDSName);
+            if (!m_osBaseDir.empty() && !osResolvedDSName.empty() &&
+                CPLIsFilenameRelative(osResolvedDSName.c_str()))
+            {
+                if (cpl::starts_with(osResolvedDSName, "GTI:"))
```
Comment (elpaso) [inline frmts/gti/gdaltileindexdataset.cpp]:
```suggestion
                if (cpl::starts_with(osResolvedDSName, GTI_PREFIX))
```

**Review by elpaso — APPROVED** [review]

File: frmts/gti/gdaltileindexdataset.cpp (hunk 1 above)
Comment (rouault) [reply frmts/gti/gdaltileindexdataset.cpp]: fixed
