### PR TITLE
gdalwarp: change INIT_DEST=NO_DATA warning to failure

### LINKED ISSUE #12210: GDALWarpOperation::InitializeDestinationBuffer(): change warning about invalid INIT_DEST value to a failure
### What is the bug?

per https://github.com/OSGeo/gdal/pull/12198 , we issue a warning if INIT_DEST=NO_DATA but there is no destination no data. Change that to a failure in GDAL 3.12

### Steps to reproduce the issue

-

### Versions and provenance

-

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LoveChauhan-18**
Fixes #12210

Promote the warning emitted when INIT_DEST=NO_DATA is used without a
destination nodata value to a failure, so the warp operation aborts
when the configuration is invalid.

### CODE REVIEW

File: alg/gdalwarpoperation.cpp [hunk 1]
```diff
@@ -846,8 +846,7 @@ CPLErr GDALWarpOperation::InitializeDestinationBuffer(void *pDstBuffer,
             if (psOptions->padfDstNoDataReal == nullptr)
             {
                 CPLError(CE_Failure, CPLE_AppDefined,
-                         "INIT_DEST was set to NO_DATA, but a NoData value was 
-                         not defined.");                        
+                         "INIT_DEST was set to NO_DATA, but a NoData value was not defined.");                        
             }
```
Comment (jratike80) [inline alg/gdalwarpoperation.cpp:851]: How about splitting the message properly on two lines, like for example on line 3130?

Comment (rouault) [reply alg/gdalwarpoperation.cpp:851]: I've adjusted this, and updated a unit test

**Comment by LoveChauhan-18** [comment]
Thanks for reviewing this PR.

The build errors have been fixed and all CI checks are now passing. Please let me know if any further adjustments are needed.

File: alg/gdalwarpoperation.cpp (hunk 1 above)
Comment (LoveChauhan-18) [reply alg/gdalwarpoperation.cpp:851]: Thanks for the update and improvements!
