### PR TITLE
PG/PGDump: fix truncation of identifiers with UTF-8 characters

### LINKED ISSUE #12532: [ogr2ogr] output to PostgreSQL throws encoding error after shortening column name
### What is the bug?

The problem happens when using `ogr2ogr` to convert a CSV file to a PostgreSQL database. The CSV file has a column with a large name and with portuguese special characters. The column name is `59-Actividades cinematográficas, de vídeo, de produção de pro`

The `ogr2ogr` output is:

```
PG: LaunderName('59-Actividades cinematográficas, de vídeo, de produção de pro') -> '59_actividades cinematográficas, de vídeo, de produ�_5c5ec485'
GDALVectorTranslate: Forcing transaction commit as table overwriting occurred
ERROR 1: ERROR:  invalid byte sequence for encoding "UTF8": 0xc3 0x5f

ERROR 1: CREATE TABLE "staging"."debug_cosme" ( "ogc_fid" SERIAL, PRIMARY KEY ("ogc_fid"), "concelho" VARCHAR, "59_actividades cinematográficas, de vídeo, de produ�_5c5ec485" VARCHAR )
ERROR:  invalid byte sequence for encoding "UTF8": 0xc3 0x5f
```

The CSV file was saved with the UTF-8 encoding and I manually typed it to ensure there were no weird characters in between. Removing the last 1-2 characters of the column name makes it so the column is no longer shortened and the operation completes successfully.

Using the "LAUNDER_ASCII=YES" works, but we also use non-latin files, this wouldn't be a good solution.

### Steps to reproduce the issue

- Input file: [debug_ogr.csv](https://github.com/user-attachments/files/20625626/debug_ogr.csv)

- Command:

```
ogr2ogr "-f" "PostgreSQL" "PG:user=xxx password=xxx host=localhost port=xxx dbname=xxx" debug_ogr.csv "-nln" "staging.debug_cosme" -overwrite --debug ON
```

### Versions and provenance

Tried it with GDAL versions 3.10.1 and 3.11.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #12532

### CODE REVIEW

File: ogr/ogrfeature.cpp [hunk 1]
```diff
@@ -7222,19 +7222,19 @@ int OGRFeature::Validate(int nValidateFlags, int bEmitError) const
...
-                CPLError(CE_Failure, CPLE_AppDefined,
-                         "Field %s.%s has a %d UTF-8 characters whereas "
-                         "a maximum of %d is allowed",
-                         poDefn->GetName(),
-                         poDefn->GetFieldDefn(i)->GetNameRef(),
-                         CPLStrlenUTF8(GetFieldAsString(i)),
-                         poDefn->GetFieldDefn(i)->GetWidth());
+                CPLError(
+                    CE_Failure, CPLE_AppDefined,
+                    "Field %s.%s has a %" PRIu64 " UTF-8 characters whereas "
```
Comment (elpaso) [inline ogr/ogrfeature.cpp]:
```suggestion
                    "Field %s.%s has %" PRIu64 " UTF-8 characters whereas "
```

File: ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp [hunk 2]
```diff
@@ -1828,39 +1828,16 @@ CPLString OGRPGEscapeColumnName(const char *pszColumnName)
 /************************************************************************/
 
 CPLString OGRPGEscapeString(void *hPGConnIn, const char *pszStrValue,
```
Comment (elpaso) [inline ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp:1830]: this is not public API, is it possible to change the signature now that the extra arguments are not used?

**Review by elpaso — APPROVED** [review]

File: ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp (hunk 2 above)
Comment (rouault) [reply ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp:1830]: This function is passed to a function pointer, and the PGDump driver also uses it, but uses the extra arguments that the PG driver doesn't, so we have to let them

**Comment by rouault** [comment]
The backport to `release/3.11` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 772e0339bd... PG/PGDump: fix truncation of identifiers with UTF-8 characters
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/cpp/CMakeLists.txt
Auto-merging autotest/cpp/test_cpl.cpp
CONFLICT (content): Merge conflict in autotest/cpp/test_cpl.cpp
Auto-merging autotest/ogr/ogr_pgdump.py
Auto-merging ogr/ogrfeature.cpp
Auto-merging ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp
Auto-merging ogr/ogrsf_frmts/pg/ogr_pg.h
Auto-merging ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp
Auto-merging ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp
Auto-merging ogr/ogrsf_frmts/pgdump/ogrpgdumplayer.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.11 release/3.11
# Navigate to the new working tree
cd .worktrees/backport-release/3.11
# Create a new branch
git switch --create backport-12538-to-release/3.11
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 772e0339bdb87e2b03fb4503e6b98cf1be019d20,cbdf6de7230ba4313e7f2c5054aca7eb53953f79
# Push it to GitHub
git push --set-upstream origin backport-12538-to-release/3.11
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.11
```
Then, create a pull request where the `base` branch is `release/3.11` and the `compare`/`head` branch is `backport-12538-to-release/3.11`.

**Comment by rouault** [comment]
cherry picked in 3.11 per 7286d0ed8bd25809498d6e6628b43ab900243381

File: ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp [hunk 3]
```diff
@@ -1828,39 +1828,16 @@ CPLString OGRPGEscapeColumnName(const char *pszColumnName)
...
-                {
-                    nSrcLen = iChar;
-                    break;
-                }
-                iUTF8Char++;
-            }
-        }
-    }
-
+    const size_t nSrcLen = strlen(pszStrValue);
```
Comment (jef-n) [inline ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp:1840]: @rouault was the truncation of values removed intentionally?  Breaks usage in alkis-import.

Comment (rouault) [reply ogr/ogrsf_frmts/pg/ogrpgtablelayer.cpp:1840]: Arg, no I don't know what I had smoked. Looking at the code I had the impression that OGRPGEscapeString() was never called with nMaxWidth >= 0 but I missed the single call site where it was... And no test checked that...  Fixed per 039b704bdbc36d2b55a5f4bdd49b5af36b2858cb . I'm likely going to generate a 3.11.3
