### PR TITLE
CPL: Propagate error handler user data correctly (fixes #1098)

### LINKED ISSUE #1098: Segfault: Error handler gets wrong context data
## Expected behavior and actual behavior.

A global error handler ends up getting threadlocal error user data, leading to badness.

1. Global error handler gets installed by `gdal.ConfigurePythonLogging()`, calling `CPLSetErrorHandlerEx()`. The Python callback function pointer is saved in the global `pErrorHandlerUserData`
2. `GTiffDataset.Open()` calls `CPLPushErrorHandlerEx(GTIFFErrorHandler...)`. This creates a threadlocal error context. The userData in this case is a vector of `GTIFFErrorStruct`.
3. `CPLSetCurrentErrorHandlerCatchDebug` is called on the `GTiffErrorHandler` to ensure debug messages are passed through to the default error handler (`bCatchDebug=false`)
4. For that particular image the GTiff driver ends up with a second curl request during `Open()` while the `GTiffErrorHandler` is installed. Often no second request is needed, which is why it doesn't often show up.
5. The curl request calls `CPLDebug()`
6. `CPLDebug` doesn't call the `GTiffErrorHandler` because `bCatchDebug==false`
7. `CPLDebug` calls the default Python error handler (ie. `PyCPLErrorHandler`)
8. `PyCPLErrorHandler` calls `CPLGetErrorHandlerUserData()`
9. `CPLGetErrorHandlerUserData()` calls `CPLGetErrorContext()` which gets the _threadlocal `GTiffErrorHandler`_ from `handlerStack[0]`, and returns it's userData (the vector).
10. `PyCPLErrorHandler` casts the userData to a Python function and calls it.
11. 💥 

#### Thoughts

* Any custom error handler can be global _or_ thread local, so accessing just the global userData directly doesn't help. And the problem isn't specific to a Python handler.
* Presumably the same problem will happen whenever there are multiple entries in the handler stack and `bCatchDebug=false` is set on any earlier one(s), since `CPLGetErrorHandlerUserData()` will always navigate the entire handler stack again.
* Error handlers should really be tightly associated with their userData.

## Steps to reproduce the problem.

```
import logging
from osgeo import gdal

logging.basicConfig(level=logging.DEBUG)

gdal.SetConfigOption("CPL_DEBUG", "ON")
gdal.UseExceptions()
gdal.ConfigurePythonLogging()

print("opening")
ds = gdal.Open("/vsicurl/http://s3.amazonaws.com/etc-data.koordinates.com/gdal-1098/00000001.tif", gdal.GA_ReadOnly)
print("got ds!", ds)
```

GDB:
(with some additional printf statements when error-handling related functions are called)
```
+CPLSetErrorHandlerEx
+CPLSetErrorHandlerEx
opening
DEBUG:gdal:S3: GetFileList(/vsis3/etc-data.koordinates.com/gdal-1098)
DEBUG:gdal:HTTP: libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
[New Thread 0x7fffe58ce700 (LWP 1733)]
[Thread 0x7fffe58ce700 (LWP 1733) exited]
DEBUG:gdal:VSICURL: Downloading 0-16383 (https://s3.amazonaws.com/etc-data.koordinates.com/gdal-1098/00000001.tif)...
DEBUG:gdal:VSICURL: Got response_code=206
+CPLPushErrorHandlerEx
+CPLSetCurrentErrorHandlerCatchDebug

Program received signal SIGSEGV, Segmentation fault.
0x00000000004d40c9 in PyObject_Call (kw=0x0, arg=(1, 0, 'VSICURL: Downloading 32768-49151 (https://s3.amazonaws.com/etc-data.koordinates.com/gdal-1098/00000001.tif)...'), func=<unknown at remote 0x7fffffffdec0>) at ../Objects/abstract.c:2525
2525	../Objects/abstract.c: No such file or directory.
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fe3740 (LWP 1710)):
#0  0x00000000004d40c9 in PyObject_Call (kw=0x0, arg=(1, 0, 'VSICURL: Downloading 32768-49151 (https://s3.amazonaws.com/etc-data.koordinates.com/gdal-1098/00000001.tif)...'), func=<unknown at remote 0x7fffffffdec0>) at ../Objects/abstract.c:2525
#1  PyEval_CallObjectWithKeywords (func=<unknown at remote 0x7fffffffdec0>, arg=(1, 0, 'VSICURL: Downloading 32768-49151 (https://s3.amazonaws.com/etc-data.koordinates.com/gdal-1098/00000001.tif)...'), kw=0x0) at ../Python/ceval.c:3889
#2  0x00007ffff699b8bd in PyCPLErrorHandler (eErrClass=<optimized out>, err_no=0, pszErrorMsg=0xc01b10 "VSICURL: Downloading 32768-49151 (https://s3.amazonaws.com/etc-data.koordinates.com/gdal-1098/00000001.tif)...") at extensions/gdal_wrap.cpp:3818
#3  0x00007ffff6060e7a in CPLDebug (pszCategory=0x7ffff641c972 "VSICURL", pszFormat=0x7ffff641caef "Downloading %s (%s)...") at cpl_error.cpp:686
#4  0x00007ffff609f638 in (anonymous namespace)::VSICurlHandle::DownloadRegion (this=this@entry=0xbfd580, startOffset=startOffset@entry=32768, nBlocks=1) at cpl_vsil_curl.cpp:1533
#5  0x00007ffff609ffe3 in (anonymous namespace)::VSICurlHandle::Read (this=0xbfd580, pBufferIn=<optimized out>, nSize=1, nMemb=152) at cpl_vsil_curl.cpp:1890
#6  0x00007ffff5ae3732 in TIFFReadDirEntryDataAndRealloc (tif=0xbdde00, offset=<optimized out>, size=152, pdest=0x7fffffffdbc0) at tif_dirread.c:820
#7  0x00007ffff5ae399f in TIFFReadDirEntryArrayWithLimit (tif=tif@entry=0xbdde00, direntry=direntry@entry=0xbf4850, count=count@entry=0x7fffffffdc14, desttypesize=desttypesize@entry=1, value=value@entry=0x7fffffffdc18, maxcount=maxcount@entry=18446744073709551615) at tif_dirread.c:913
#8  0x00007ffff5ae3fb4 in TIFFReadDirEntryArray (value=0x7fffffffdc18, desttypesize=1, count=0x7fffffffdc14, direntry=0xbf4850, tif=0xbdde00) at tif_dirread.c:927
#9  TIFFReadDirEntryByteArray (tif=0xbdde00, direntry=0xbf4850, value=0x7fffffffdc78) at tif_dirread.c:953
#10 0x00007ffff5ae62a2 in TIFFFetchNormalTag (tif=tif@entry=0xbdde00, dp=dp@entry=0xbf4850, recover=recover@entry=1) at tif_dirread.c:4941
#11 0x00007ffff5ae8ce1 in TIFFReadDirectory (tif=tif@entry=0xbdde00) at tif_dirread.c:3985
#12 0x00007ffff5b0bc38 in TIFFClientOpen (name=0xb80b00 "/vsis3/etc-data.koordinates.com/gdal-1098/00000001.tif", mode=0x7ffff625b4df "r", clientdata=<optimized out>, readproc=0x7ffff5b1a240 <_tiffReadProc(thandle_t, tdata_t, tsize_t)>, writeproc=0x7ffff5b1a300 <_tiffWriteProc(thandle_t, tdata_t, tsize_t)>, seekproc=0x7ffff5b1a4e0 <_tiffSeekProc(thandle_t, toff_t, int)>, closeproc=0x7ffff5b1a200 <_tiffCloseProc(thandle_t)>, sizeproc=0x7ffff5b1a480 <_tiffSizeProc(thandle_t)>, mapproc=0x7ffff5b1a120 <_tiffMapProc(thandle_t, tdata_t*, toff_t*)>, unmapproc=0x7ffff5b1a150 <_tiffUnmapProc(thandle_t, tdata_t, toff_t)>) at tif_open.c:464
#13 0x00007ffff5b1a817 in VSI_TIFFOpen (name=<optimized out>, name@entry=0xb80b00 "/vsis3/etc-data.koordinates.com/gdal-1098/00000001.tif", mode=0x7ffff625b4df "r", fpL=0xbfd580) at tifvsi.cpp:379
#14 0x00007ffff585d624 in GTiffDataset::Open (poOpenInfo=0x7fffffffdfd0) at geotiff.cpp:12322
#15 0x00007ffff5bbe84e in GDALOpenEx (pszFilename=0x7ffff7ec6954 "/vsis3/etc-data.koordinates.com/gdal-1098/00000001.tif", nOpenFlags=66, papszAllowedDrivers=0x0, papszOpenOptions=0x0, papszSiblingFiles=<optimized out>) at gdaldataset.cpp:2825
#16 0x00007ffff69d49ea in _wrap_Open (args=<optimized out>) at extensions/gdal_wrap.cpp:29371
#17 0x00000000004c7f54 in call_function (oparg=<optimized out>, pp_stack=0x7fffffffe200) at ../Python/ceval.c:4020
#18 PyEval_EvalFrameEx (f=f@entry=Frame 0x7ffff7f41208, for file ./gdal-segfault.py, line 11, in <module> (), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
...
```

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

master (2.3.2+) at d97cc5f

### PR DESCRIPTION
**Pull request by rcoup**
## What does this PR do?

Fixes [crashes in logging where error handlers receive the wrong context data](https://github.com/OSGeo/gdal/issues/1098).

Solves this by:
1. centralising error propagation (thread local handler stack + global) via a new local `ApplyHandler()` function.
2. pushing the active handler's user data onto a threadlocal variable (`CTLS_ERRORHANDLERACTIVEDATA`). 
3. it is represented there as a `void**` (because "no active userData" != "active userData that is 0")
4. make `CPLGetErrorHandlerUserData()` look at the threadlocal variable first.

I've kept the existing behaviour/semantics, including the differences between `CPLDebug(...)` & `CPLError(CE_Debug, ...)`.

The testcase from #1098 passes ok ("_ERROR:gdal:AppDefined: Cannot open TIFF file due to missing codec._"), as do the existing tests in `misc.py`.

## What are related issues/pull requests?

#1098

## Tasklist

 - ~Add test case(s)~
 - [x] Review
 - [x] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

File: gdal/port/cpl_error.cpp [hunk 1]
```diff
@@ -193,6 +207,70 @@ void* CPL_STDCALL CPLGetErrorHandlerUserData(void)
         psCtx->psHandlerStack->pUserData : pErrorHandlerUserData );
 }
 
+
+void ApplyErrorHandler( CPLErrorContext *psCtx, CPLErr eErrClass,
```
Comment (rouault) [inline gdal/port/cpl_error.cpp]: static

File: gdal/port/cpl_error.cpp [hunk 2]
```diff
@@ -193,6 +207,70 @@ void* CPL_STDCALL CPLGetErrorHandlerUserData(void)
...
+                        CPLErrorNum err_no, const char *pszMessage,
+                        bool is_cpldebug )
```
Comment (rouault) [inline gdal/port/cpl_error.cpp]: is_cpldebug doesn't seem necessary. You could just test eErrClass == CE_Debug

Comment (rouault) [reply gdal/port/cpl_error.cpp]: My quick grepping of CPLError CE_Debug shows only 4 call sites
```
frmts/rda/rdadataset.cpp:                CPLError( CE_Debug, CPLE_AppDefined,
frmts/hdf4/hdf4imagedataset.cpp:        CPLError( CE_Debug, CPLE_AppDefined,
frmts/ecw/ecwdataset.cpp:        CPLError( CE_Debug, CPLE_AppDefined,
frmts/ecw/ecwdataset.cpp:        CPLError( CE_Debug, CPLE_AppDefined,
```
And those should probably changed to CPLDebug() call for the clarity. I don't think we need to make a semantic difference between CPLDebug() and CPLError(CE_Debug, )
