### PR TITLE
HDF4-EOS: fix potential Out-of-Bounds Write in SWfinfo()

### LINKED ISSUE #14440: Out-of-Bounds Write in SWfinfo() via unchecked strcat on dimlist buffer
### What is the bug?

Summary: SWfinfo` performs unchecked concatenation of dimension strings into the `dimlist` buffer using `strcat`
https://github.com/OSGeo/gdal/blob/037fa9ed04e730e676bf4f36ea04b649f58685f4/frmts/hdf4/hdf-eos/SWapi.c#L1344 
The function signature accepts dimlist as a raw char* with no accompanying size_t dimlist_len parameter. The cumulative length of all dimension names plus commas is never validated against any bound.

Path 1 — Stack buffer overflow in dimstr[64] via memcpy
```
char dimstr[64];   // fixed 64-byte stack buffer

for (i = 0; i < ndims; i++)
{
    memcpy(dimstr, ptr[i] + 1, slen[i] - 2);  // slen[i] comes from metadata
    dimstr[slen[i] - 2] = 0;                  // no check: slen[i] could be > 64
```
Path 2 — Heap/stack overflow in caller's dimlist buffer via strcat
```
// Function signature — no size parameter for dimlist:
int32 SWfinfo(int32 swathID, const char *fieldtype, const char *fieldname,
              int32 *rank, int32 dims[], int32 *numbertype,
              char *dimlist)   // ← raw pointer, no length

    if (dimlist != NULL)
    {
        if (i > 0) strcat(dimlist, ",");
        strcat(dimlist, dimstr);   // ← writes blindly into caller's buffer
    }
```
Attack Vector: Metadata source -> EHgetmetavalue("DimList") -> EHparsestr()->
              slen[i] > 64  ->  memcpy overflow in dimstr[64]
                        OR
              sum of dim names > sizeof(dimlist)  ->  strcat overflow

```
// Add a length check before memcpy:
if (slen[i] < 2 || (slen[i] - 2) >= (int32)sizeof(dimstr))
{
    status = -1;
    break;
}
memcpy(dimstr, ptr[i] + 1, slen[i] - 2);
dimstr[slen[i] - 2] = 0;
```

Fix2:
```
// Change signature to:
int32 SWfinfo(int32 swathID, const char *fieldtype, const char *fieldname,
              int32 *rank, int32 dims[], int32 *numbertype,
              char *dimlist, size_t dimlist_len);  // ← add this

// Then replace strcat with:
if (dimlist != NULL)
{
    if (i > 0) strncat(dimlist, ",", dimlist_len - strlen(dimlist) - 1);
    strncat(dimlist, dimstr, dimlist_len - strlen(dimlist) - 1);
}
```

### Steps to reproduce the issue

1. Create a crafted HDF4 file with a DimList dimension name longer than
   64 characters in StructMetadata. This can be done with any HDF4 library
   (pyhdf, h5py with HDF4 support, or the HDF4 command-line tools).
   The key requirement is that StructMetadata.0 contains:

       DimList=("AAAA...AAAA")   <- name must be >= 65 characters

   A working proof-of-concept script is available on request.

2. Open the file with any GDAL-based application:
```
gdalinfo malicious.hdf
```
3. The crash occurs inside SWfinfo() when it processes the malicious DimList.
```
ERROR: AddressSanitizer: stack-buffer-overflow
WRITE of size 65 at offset 0
```

### Versions and provenance

[GDAL 3.12.3](https://github.com/OSGeo/gdal/releases/tag/v3.12.3)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #14440

### CODE REVIEW

File: frmts/hdf4/hdf-eos/SWapi.c [hunk 1]
```diff
@@ -1330,21 +1330,37 @@ SWfinfo(int32 swathID, const char *fieldtype, const char *fieldname,
...
-		strcat(dimlist, dimstr);
-	    }
-
-	}
+    size_t dimlistlen = 0;
+    for (i = 0; i < ndims; i++)
+    {
+        if (slen[i] >= 2)
+        {
+            memcpy(dimstr, ptr[i] + 1, slen[i] - 2);
```
Comment (elpaso) [inline frmts/hdf4/hdf-eos/SWapi.c:1351]: Don't we need to check if `slen[i] - 2` is < 64 before copying?

Comment (rouault) [reply frmts/hdf4/hdf-eos/SWapi.c:1351]: that might indeed be more prudent. Done (as well as a unrelated fix when looking at code around that one... which one shouldn't do to keep one's sanity :-))

**Review by karnakarreddi — APPROVED** [review]
