### PR TITLE
Overview generation: fix multi-threaded bug, resulting in locks/crashes with GeoPackage in particular

### LINKED ISSUE #10245: Sporadic error with multi-threaded overview generation
### What is the bug?

Running BuildOverviews on a GeoPackage dataset with config GDAL_NUM_THREADS=ALL_CPUS results in sporadic errors. The errors seem to happen around 50% of the time.

### Steps to reproduce the issue

Running a script to repeat the BuildOverviews() function on the same source
[MassiveGeopackage_output.zip](https://github.com/user-attachments/files/15899499/MassiveGeopackage_output.zip)
 file multiple times. The files are stored on a spinning hard drive.

```python
from osgeo import gdal
import os
import shutil

srcfile = r'F:\05_Annet\2024-06-19-gdaladdo-bug\data\MassiveGeopackage_output.gpkg'
copiedfile = r'F:\05_Annet\2024-06-19-gdaladdo-bug\out\test-overviews.gpkg'

for i in range(20):
    print(f'Attempt {i}')
    
    shutil.copy(srcfile,copiedfile)
    gdal.SetConfigOption('GDAL_NUM_THREADS','ALL_CPUS')
    
    gpkg_ds = gdal.OpenEx(copiedfile,1)
    gpkg_ds.BuildOverviews(resampling='bilinear', overviewlist=[2,4])
    gpkg_ds = None

    os.unlink(copiedfile)
```

This results in the following output:
```
Attempt 1
ERROR 1: sqlite3_exec(COMMIT) failed: database is locked
ERROR 1: F:\05_Annet\2024-06-19-gdaladdo-bug\out\test-overviews.gpkg - zoom_level=1, band 1: IReadBlock failed at X offset 0, Y offset 0
Attempt 2
Attempt 3
ERROR 1: sqlite3_exec(COMMIT) failed: database is locked
ERROR 1: F:\05_Annet\2024-06-19-gdaladdo-bug\out\test-overviews.gpkg - zoom_level=1, band 1: IReadBlock failed at X offset 0, Y offset 0
Attempt 4
Attempt 5
ERROR 1: sqlite3_exec(COMMIT) failed: database is locked
ERROR 1: F:\05_Annet\2024-06-19-gdaladdo-bug\out\test-overviews.gpkg - zoom_level=1, band 1: IReadBlock failed at X offset 0, Y offset 0
Attempt 6
Attempt 7
Attempt 8
Attempt 9
Attempt 10
Attempt 11
ERROR 1: sqlite3_exec(COMMIT) failed: database is locked
ERROR 1: F:\05_Annet\2024-06-19-gdaladdo-bug\out\test-overviews.gpkg - zoom_level=1, band 1: IReadBlock failed at X offset 0, Y offset 0
Attempt 12
Attempt 13
Attempt 14
Attempt 15
Attempt 16
Attempt 17
```

### Versions and provenance

Windows 11
Python 3.12
GDAL 3.8.2 wheel from https://github.com/cgohlke/geospatial-wheels

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10245

### CODE REVIEW

File: gcore/overview.cpp [hunk 1]
```diff
@@ -155,42 +163,24 @@ static CPLErr GDALResampleChunk_NearT(
...
-    GDALColorTable * /* poColorTable_unused */, GDALDataType /* eSrcDataType */,
-    bool /* bPropagateNoData */)
+static CPLErr GDALResampleChunk_Near(const GDALOverviewResampleArgs &args,
+                                     const void *pChunk, void **ppDstBuffer,
+                                     GDALDataType *peDstBufferDataType)
 {
-    *peDstBufferDataType = eWrkDataType;
-    if (eWrkDataType == GDT_Byte)
+    *peDstBufferDataType = args.eWrkDataType;
+    if (args.eWrkDataType == GDT_Byte)
```
Comment (elpaso) [inline gcore/overview.cpp:171]: Can we have a switch here ?

File: gcore/overview.cpp [hunk 2]
```diff
@@ -1708,73 +1712,45 @@ static CPLErr GDALResampleChunk_AverageOrRMS_T(
...
-    GDALDataType *peDstBufferDataType, const char *pszResampling,
-    bool bHasNoData, double dfNoDataValue, GDALColorTable *poColorTable,
-    GDALDataType /* eSrcDataType */, bool bPropagateNoData)
+static CPLErr
+GDALResampleChunk_AverageOrRMS(const GDALOverviewResampleArgs &args,
+                               const void *pChunk, void **ppDstBuffer,
+                               GDALDataType *peDstBufferDataType)
 {
-    if (eWrkDataType == GDT_Byte)
+    if (args.eWrkDataType == GDT_Byte)
```
Comment (elpaso) [inline gcore/overview.cpp:1720]: switch ?

File: gcore/overview.cpp [hunk 3]
```diff
@@ -2310,61 +2306,42 @@ static CPLErr GDALResampleChunk_Mode_T(
...
+        GDALGetDataTypeSizeBytes(args.eWrkDataType));
     if (*ppDstBuffer == nullptr)
     {
         return CE_Failure;
     }
 
-    *peDstBufferDataType = eWrkDataType;
-    if (eWrkDataType == GDT_Byte)
+    *peDstBufferDataType = args.eWrkDataType;
+    if (args.eWrkDataType == GDT_Byte)
```
Comment (elpaso) [inline gcore/overview.cpp:2322]: switch?

**Review by elpaso — APPROVED** [review]

File: gcore/overview.cpp (hunk 1 above)
Comment (rouault) [reply gcore/overview.cpp]: done

File: gcore/overview.cpp (hunk 3 above)
Comment (rouault) [reply gcore/overview.cpp]: done

**Comment by rouault** [comment]
3.9 backport  in https://github.com/OSGeo/gdal/pull/10255
