### PR TITLE
Fix FlatGeobuf MultiLineString spec conformance

### LINKED ISSUE #10774: FlatGeobuf writer/reader does not adhere to spec for MultiLineString
### What is the bug?

From https://github.com/flatgeobuf/flatgeobuf/blob/1d3647cec277aee63494a9f3b1958c3cb58674f5/src/fbs/feature.fbs#L6 the spec says that ends is defined as "Array of end index in flat coordinates per geometry part with exterior ring first (NOTE: allowed and recommended to be null if 1 part)".

The writer implementation in GDAL writes ends also for single part MultiLineStrings, here https://github.com/OSGeo/gdal/blob/5999d8b87cf370d15a944e375d56cf0d8ef7a95f/ogr/ogrsf_frmts/flatgeobuf/geometrywriter.cpp#L92-L98. This is not wrong per se but not recommended in the spec.

The reader implementation in GDAL assumes ends exists and throws if they do not here https://github.com/OSGeo/gdal/blob/5999d8b87cf370d15a944e375d56cf0d8ef7a95f/ogr/ogrsf_frmts/flatgeobuf/geometryreader.cpp#L119-L120. This is the bad one, since other implementation may write singlepart MultiLineStrings and as such will fail to read such files.

### Steps to reproduce the issue

Will be supplied in a pull request I intend to work on as soon as I can.

### Versions and provenance

Ubuntu 24.04, GDAL 3.8.4, released 2024/02/08

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bjornharrtell**
## What does this PR do?

Fix #10774

## What are related issues/pull requests?

#10774

## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [ ] Review
 - [x] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by bjornharrtell** [comment]
First commit intends to fix the writer side, and should fail tests because reader side cannot handle it until it's fixed.

File: ogr/ogrsf_frmts/flatgeobuf/geometrywriter.cpp [hunk 1]
```diff
@@ -91,6 +91,9 @@ uint32_t GeometryWriter::writeSimpleCurve(const OGRSimpleCurve *sc)
 
 void GeometryWriter::writeMultiLineString(const OGRMultiLineString *mls)
 {
+    // NOTE: should not write ends if less than 2 parts
```
Comment (rouault) [inline ogr/ogrsf_frmts/flatgeobuf/geometrywriter.cpp:94]: hum that seems wrong to me. This will not even write the geometry at all if it made of one part... unless I'm missing something. The loop below doesn't only update m_ends: writeSimpleCurve() sets the x/y/z/m arrays

Comment (bjornharrtell) [reply ogr/ogrsf_frmts/flatgeobuf/geometrywriter.cpp]: ah yes, I was clearly confused, thanks.

**Comment by bjornharrtell** [comment]
Expected test failure:

30: ERROR 1: Unexpected nullptr: MultiLineString ends data
30: ERROR 1: Failed to read geometry
30: ERROR 1: Fatal error parsing feature

**Comment by bjornharrtell** [comment]
Think this is ready. Don't understand the Linux Builds / Fedora Rawhide, clang++ failure, it doesn't seem related?

**Comment by rouault** [comment]
> Don't understand the Linux Builds / Fedora Rawhide, clang++ failure, it doesn't seem related?

yes, unrelated. Lickely linked to a GEOS update. Will look at that separately

For my information, what is the backward compatibility story of this PR:
- will code with this PR be able to read "bad multipolygons" written in the past ?
- will "good multipolygons" written by code with this PR be readable by old GDAL versions ?

Should that be backported to the stable branch? (but this depends on the answers to above questions. Typically we don't want FlatGeoBuf files produced by GDAL 3.9.2 to no longer be readable by GDAL 3.9.3)

**Comment by bjornharrtell** [comment]
@rouault mabye you made a typo but this problem is *only* about singlepart MultiLineString, *not* MultiPolygon (or Polygon). I'm sure I would have found this earlier if it affected Polygon encoding which encodes in a similar way using "ends", but AFAIK Polygon encoding is correctly implemented in GDAL and elsewhere.

This patch will make GDAL able to read files with singlepart MultiLineStrings encoded by other implementations.

This patch will currently also make GDAL write singlepart MultiLineStrings in the way other implementations, making such files unreadable pre-patch GDAL. This is also what allowed to reproduce the issue in roundtrip tests. I agree writing output that will break older GDAL versions is undesired and unfortunate. I suppose I could leave GDAL writer alone since it isn't doing anything wrong per se, it's "just" not the recommended way per spec and not optimal (however the savings of omitting ends it likley very small). It doesn't feel great to have GDAL be special about it but neither does breaking userspace. I've already convinced myself to go the compatible route, I will modify this PR promptly.

Backport to supported older GDAL versions would be nice, to support output from other implementations. At the moment I don't feel it's likely I will try and retrofit "the GDAL way" to write singlepart MultiLineString to all other implementations.

**Comment by bjornharrtell** [comment]
@rouault I've now changed this PR to only affect the reader. If you approve can you merge with squash or do I need to rebase/squash?

**Comment by rouault** [comment]
> mabye you made a typo but this problem is _only_ about singlepart MultiLineString, _not_ MultiPolygon

sorry, yes I meant MultiLineString

> I've now changed this PR to only affect the reader. If you approve can you merge with squash or do I need to rebase/squash?

I'll squash using the github button

But could you add a unit test with a geometry written the "new" way to check the reader correctly reads it ?

**Comment by rouault** [comment]
@bjornharrtell  I wanted to update the test to actually check the geometry, but the file appears to be partly broken. See:
```
$ ogrinfo autotest/ogr/data/flatgeobuf/test_ogr_flatgeobuf_singlepart_mls_new.fgb -al
INFO: Open of `autotest/ogr/data/flatgeobuf/test_ogr_flatgeobuf_singlepart_mls_new.fgb'
      using driver `FlatGeobuf' successful.

Layer name: unknown
Geometry: Multi Line String
ERROR 1: Buffer verification failed
ERROR 1: Fatal error parsing feature
Feature Count: 1
ERROR 1: Buffer verification failed
ERROR 1: Fatal error parsing feature
Extent: (0.000000, 0.000000) - (1.000000, 1.000000)
Layer SRS WKT:
(unknown)
OGRFeature(unknown):0
  MULTILINESTRING ((0 0,1 1))

ERROR 1: Buffer verification failed
ERROR 1: Fatal error parsing feature
```
It would be good if you could provide a "clean" version.

**Comment by bjornharrtell** [comment]
Hmm that is concerning... and I'm not sure what the cause is at this point.

**Comment by bjornharrtell** [comment]
I've made several runs to generate a new file (using my C# / .NET reference implementation) and the result is a 144 bytes file which I've now commited and pushed here and hope it is correct. The one I made yesterday was 400 bytes... which seems quite wrong actually. As for how I was able to produce an invalid file, I really have no clue at this point.

**Comment by rouault** [comment]
> pushed here and hope it is correct.

looks good here too. I've just pushed https://github.com/OSGeo/gdal/pull/10775/commits/a58bd224fced76071194af3d2ca270c4da6aaefb to improve testing

**Comment by rouault** [comment]
The backport to `release/3.9` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
<details>
<summary>stderr</summary>

```
error: commit 28de8f1382c09c369e318e4318c81c6c9740ed31 is a merge but no -m option was given.
fatal: cherry-pick failed

```
</details>

<details>
<summary>stdout</summary>

```
[backport-10775-to-release/3.9 9a0ddb846e] Make write conform to spec
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 00:05:05 2024 +0200
 1 file changed, 3 insertions(+)
[backport-10775-to-release/3.9 354fb5af10] Fix missing actual write
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 05:48:33 2024 +0200
 1 file changed, 5 insertions(+), 2 deletions(-)
[backport-10775-to-release/3.9 09306daf50] Attempt to fix reader
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 06:08:55 2024 +0200
 1 file changed, 22 insertions(+), 13 deletions(-)
[backport-10775-to-release/3.9 39f5a63c38] Fix bad type
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 06:29:00 2024 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[backport-10775-to-release/3.9 aac4ebc6d0] Revert to changes to writing logic
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 20:49:48 2024 +0200
 1 file changed, 6 deletions(-)
[backport-10775-to-release/3.9 ee1056f062] Regression test for fixed FlatGeobuf reader external singlepart MultiLineString
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 21:47:04 2024 +0200
 2 files changed, 17 insertions(+)
 create mode 100644 autotest/ogr/data/flatgeobuf/test_ogr_flatgeobuf_singlepart_mls_new.fgb
[backport-10775-to-release/3.9 7b722efaea] Fix name
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 22:16:42 2024 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[backport-10775-to-release/3.9 a17db58739] Fix path
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Thu Sep 12 22:18:00 2024 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[backport-10775-to-release/3.9 7d9a00a4bf] Test file wasn't right now it should be
 Author: Björn Harrtell <bjorn@septima.dk>
 Date: Fri Sep 13 00:49:44 2024 +0200
 1 file changed, 0 insertions(+), 0 deletions(-)

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.9 release/3.9
# Navigate to the new working tree
cd .worktrees/backport-release/3.9
# Create a new branch
git switch --create backport-10775-to-release/3.9
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 5592c2953fb7d9d37e7d61b5c7ac89ad20587823,1d46b51d60dc90d2fc5bfe2e829f6f0622537db5,002386735664d75b2d19d13fe64ca517b2e95cbf,7d44244bc8b3c8191fb0d3aade61dc0361e6bf82,ff18e0b0d00b873701c33961483d415e39746e56,f0b24a916929b8b71cecf5357b6aadb5a65791b1,cdbf109676975443f0173fd36b070a2c0d6d326d,61e5754def0beec60f55c186f62b2f0a5bdf9330,56b5d7f556d7e73951999132cc8b341fbad9d659,28de8f1382c09c369e318e4318c81c6c9740ed31,68958273c4df21fbc83593d254be7371349164bc,c0e9df8bb2cdc575cc0a4ac2266b5acea4a43f58,90feb9a0e054d7b255f413eccf73553f12d8b5ef,a58bd224fced76071194af3d2ca270c4da6aaefb
# Push it to GitHub
git push --set-upstream origin backport-10775-to-release/3.9
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.9
```
Then, create a pull request where the `base` branch is `release/3.9` and the `compare`/`head` branch is `backport-10775-to-release/3.9`.
