### PR TITLE
ogr2ogr: force -preserve_fid when doing GPX to GPKG (fixes #9225)

### LINKED ISSUE #9225: GPX: track_fid one off in the track_points table
Test data: test.gpx file from the autotests https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/gpx/test.gpx
Test method: convert GPX into gpkg or PostGIS
`ogr2ogr -f gpkg gpxtest.gpkg test.gpx`

The issue: 
Fids in the "tracks" table start from 1
kuva
Track_fids in the "track_points" table start from 0
kuva

As a result joining `track_points.track_fid=tracks.fid` joins all track points to wrong tracks.

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

File: apps/ogr2ogr_lib.cpp [hunk 1]
```diff
@@ -4324,6 +4324,21 @@ SetupTargetLayer::Setup(OGRLayer *poSrcLayer, const char *pszNewLayerName,
                 bPreserveFID = false;
             }
         }
+        // Detect scenario of converting from GPX to a format like GPKG
+        // Cf https://github.com/OSGeo/gdal/issues/9225
+        else if (!bPreserveFID && !m_bUnsetFid && !bAppend &&
+                 m_poSrcDS->GetDriver() &&
+                 EQUAL(m_poSrcDS->GetDriver()->GetDescription(), "GPX") &&
+                 pszDestCreationOptions != nullptr &&
```
Comment (elpaso) [inline apps/ogr2ogr_lib.cpp:4332]:
```suggestion
                 pszDestCreationOptions &&
```

Comment (elpaso) [inline apps/ogr2ogr_lib.cpp:4332]:
```suggestion
                 pszDestCreationOptions &&
```

**Review by elpaso — APPROVED** [review]

File: apps/ogr2ogr_lib.cpp (hunk 1 above)
Comment (rouault) [reply apps/ogr2ogr_lib.cpp]: done
