### PR TITLE
ogr2ogr/VectorTranslate: fix (and improve) selectFields support in Arrow code path

### LINKED ISSUE #13401: VectorTranslate: SelectFields=[] ignored if OGR2OGR_USE_ARROW_API=YES
### What is the bug?

When using `gdal.VectorTranslate` with `SelectField=[]` (so no columns should be retained) this is ignored if `OGR2OGR_USE_ARROW_API=YES`. If `OGR2OGR_USE_ARROW_API=NO` it works fine.

Filtering on e.g. one field, e.g. `SelectField=["OIDN"]` works fine.

Appending with a `SelectField=[]` and `addFields=True` is also in the test-script as I first thought the problem would have been there...

### Steps to reproduce the issue

Reproducing script:
``` python
import tempfile
from pathlib import Path

from osgeo import gdal

gdal.UseExceptions()

# Prepare test data
gfo_uri = "https://github.com/geofileops/geofileops/raw/refs/heads/main"
orig_path = f"/vsicurl/{gfo_uri}/tests/data/polygon-parcel.gpkg"
tmp_dir = Path(tempfile.gettempdir())
no_fields_path = tmp_dir / "polygon-parcel.gpkg"

for use_arrow in [False, True]:
    for select_fields in [[], ["OIDN"]]:

        if no_fields_path.exists():
            no_fields_path.unlink()

        arrow_api_key = "OGR2OGR_USE_ARROW_API"
        gdal.SetConfigOption(arrow_api_key, "YES" if use_arrow else "NO")

        print(f"--- {arrow_api_key}={gdal.GetConfigOption(arrow_api_key)}, {select_fields=} ---")

        # Create a copy with no fields
        options = gdal.VectorTranslateOptions(selectFields=select_fields)
        ds = gdal.VectorTranslate(destNameOrDestDS=no_fields_path, srcDS=orig_path, options=options)
        ds = None

        # Check that the file actually has no fields
        ds = gdal.OpenEx(no_fields_path, gdal.OF_VECTOR | gdal.OF_READONLY)
        layer = ds.GetLayer()
        layer_defn = layer.GetLayerDefn()
        print(f"Number of fields in no-fields gpkg: {layer_defn.GetFieldCount()}")
        ds = None

        # Now append the original file again without fields
        options = gdal.VectorTranslateOptions(accessMode="append", selectFields=select_fields, addFields=True)
        ds = gdal.VectorTranslate(destNameOrDestDS=no_fields_path, srcDS=orig_path, options=options)
        ds = None

        # The file should still have no fields
        ds = gdal.OpenEx(no_fields_path, gdal.OF_VECTOR | gdal.OF_READONLY)
        layer = ds.GetLayer()
        layer_defn = layer.GetLayerDefn()
        print(f"Number of fields after appending original gpkg: {layer_defn.GetFieldCount()}")
        ds = None
```
Output:
```
--- OGR2OGR_USE_ARROW_API=NO, select_fields=[] ---
Number of fields in no-fields gpkg: 0
Number of fields after appending original gpkg: 0
--- OGR2OGR_USE_ARROW_API=NO, select_fields=['OIDN'] ---
Number of fields in no-fields gpkg: 1
Number of fields after appending original gpkg: 1
--- OGR2OGR_USE_ARROW_API=YES, select_fields=[] ---
Number of fields in no-fields gpkg: 11
Number of fields after appending original gpkg: 11
--- OGR2OGR_USE_ARROW_API=YES, select_fields=['OIDN'] ---
Number of fields in no-fields gpkg: 1
Number of fields after appending original gpkg: 1
```

### Versions and provenance

Windows 11, GDAL 3.11.3 installed via conda-forge.

### Additional context

Noticed because some geofileops tests started failing when enabling OGR2OGR_USE_ARROW_API for GDAL > 3.11.4.
PR: https://github.com/geofileops/geofileops/pull/773

### PR DESCRIPTION
**Pull request by rouault**
Fixes #13401

### CODE REVIEW

File: apps/ogr2ogr_lib.cpp [hunk 1]
```diff
@@ -4428,6 +4436,55 @@ bool SetupTargetLayer::CanUseWriteArrowBatch(
...
+    {
+        const char *pszFieldName =
+            poSrcFDefn->GetFieldDefn(iSrcField)->GetNameRef();
+        bool bFieldRequested =
+            CSLFindString(m_papszSelFields, pszFieldName) >= 0;
+        bFieldRequested |= aosWHEREUsedFields.FindString(pszFieldName) >= 0;
+        bFieldRequested |=
+            (m_pszZField != nullptr && EQUAL(pszFieldName, m_pszZField));
+
+        /* If source field not requested, add it to ignored files list
```
Comment (elpaso) [inline apps/ogr2ogr_lib.cpp]: The comment does not seem very clear to me.

**Review by elpaso — APPROVED** [review]

File: apps/ogr2ogr_lib.cpp (hunk 1 above)
Comment (rouault) [reply apps/ogr2ogr_lib.cpp]: There was a typo files vs fields. hanged to "If the source field is not requested, add it to the list of ignored fields."

**Comment by rouault** [comment]
The backport to `release/3.12` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply e8eb6b97e2... ogr2ogr/VectorTranslate: fix (and improve) selectFields support in Arrow code path
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging apps/ogr2ogr_lib.cpp
CONFLICT (content): Merge conflict in apps/ogr2ogr_lib.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.12 release/3.12
# Navigate to the new working tree
cd .worktrees/backport-release/3.12
# Create a new branch
git switch --create backport-13414-to-release/3.12
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick e8eb6b97e20f1c24d07d04ddc00755caf53d5377
# Push it to GitHub
git push --set-upstream origin backport-13414-to-release/3.12
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.12
```
Then, create a pull request where the `base` branch is `release/3.12` and the `compare`/`head` branch is `backport-13414-to-release/3.12`.

**Comment by rouault** [comment]
cherry-picked to 3.12 per ece0fa93c42e9586fb82f66ab74248e3e43f6a11
