### PR TITLE
[DWG] : support AcDbFace reading (fixes #4535)

### LINKED ISSUE #4535: [DWG] Dwg Driver does not support polygons reading
## Expected behavior and actual behavior.

When i read a DWG with DWGDriver (GDAL Compiled with ODA), AcDbFace and AcDbRegion are ignored, in fact, a lot of DWG files contain those type of object. In the reader there are nothing to read polygons present in the dwg. I would like to convert also AcDbRegion and AcDbFaces to Ogr Polygons

## Steps to reproduce the problem.

Create a DWG with faces or regions, the launch this command line ,

 `ogrinfo.exe C:\Users\fkouadjosse\Downloads\Luc\Modele_intraSITE.dwg entities --debug ON `
 
the output does not contains any polygon and the output explains that AcDbFace or AcDbRegion are ignored.

## Operating system

Windows 10 64 bit & Linux Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 3.2 on Ubuntu & 3.0.4 on Windows

Clipboard - 22 septembre 2021 09_21
1

### PR DESCRIPTION
**Pull request by lchevallier69**
When reader encounter AcDbFace, it translate it to 4 vertices polygon

### CODE REVIEW

File: ogr/ogrsf_frmts/dwg/ogr_dwg.h [hunk 1]
```diff
@@ -124,6 +124,7 @@ class OGRDWGLayer final: public OGRLayer
     OGRFeature *        TranslateHATCH( OdDbEntityPtr poEntity );
     OGRFeature *        TranslateTEXT( OdDbEntityPtr poEntity );
     OGRFeature *        TranslateINSERT( OdDbEntityPtr poEntity );
+	OGRFeature *        Translate3DFACE(OdDbEntityPtr poEntity);
```
Comment (rouault) [inline ogr/ogrsf_frmts/dwg/ogr_dwg.h:127]: using 4-space indentation instead of tabulation:
```suggestion
     OGRFeature *        Translate3DFACE(OdDbEntityPtr poEntity);
```

File: ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp [hunk 2]
```diff
@@ -1385,6 +1417,10 @@ OGRFeature *OGRDWGLayer::GetNextUnfilteredFeature()
         else if( EQUAL(pszEntityClassName,"AcDbHatch") )
         {
             poFeature = TranslateHATCH( poEntity );
+        }
+		else if (EQUAL(pszEntityClassName, "AcDbFace"))
```
Comment (rouault) [inline ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp:1421]:
```suggestion
         else if (EQUAL(pszEntityClassName, "AcDbFace"))
```

File: ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp [hunk 3]
```diff
@@ -1128,6 +1128,38 @@ class GeometryInsertTransformer : public OGRCoordinateTransformation
...
+
+    OdInt16 index;
+    OdGePoint3d point;
+
+    for (index = 0; index <= 3; index++)
+    {
+        pFace->getVertexAt(index, point);
+        poLinearRing->addPoint(point.x,point.y,point.z);
+    }
+    poPolygon->addRingDirectly(poLinearRing);
```
Comment (rouault) [inline ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp:1157]: I assume that point at index 3 is the same as index 0 ? Otherwise you should call closeRings() to add as last point the first point

File: ogr/ogrsf_frmts/dwg/ogr_dwg.h (hunk 1 above)
Comment (lchevallier69) [reply ogr/ogrsf_frmts/dwg/ogr_dwg.h]: sorry first commit, i did not knew the code format you use, i apply changes on tabs

File: ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp (hunk 2 above)
Comment (lchevallier69) [reply ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp]: idem

**Comment by lchevallier69** [comment]
@rouault do you want me to squash all commits on each push or may i do it before pull request approved ?

File: ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp (hunk 3 above)
Comment (lchevallier69) [reply ogr/ogrsf_frmts/dwg/ogrdwglayer.cpp:1157]: ok fine, i apply the closeRings check

**Comment by rouault** [comment]
> do you want me to squash all commits on each push or may i do it before pull request approved ?

I'll use the squash&merge github functionality

**Comment by lchevallier69** [comment]
not draft, it is finished, just PR remarks has been modified
