### PR TITLE
GDALGetCacheMax64(): fix TSAN complaint (fixes #1837)

### LINKED ISSUE #1837: GDALGetCacheMax64() TSAN complaint
Super low priority...

In the I don't really care category, but TSAN complained about `GDALGetCacheMax64()`.  It doesn't like the bool check: `if( !bCacheMaxInitialized )`.  I don't think that two threads getting into this code would really be a big deal.   This would easily solve with `call_once`, but this would be the first use of call_once in GDAL.  But maybe it's not so easy since there interaction in `GDALSetCacheMax64()` for `bCacheMaxInitialized`

```c++
namespace {
std::once_flag flagSetupGDALGetCacheMax64;
}

GIntBig CPL_STDCALL GDALGetCacheMax64()
{
    std::call_once(flagSetupGDALGetCacheMax64, [](){
        // All the setup code here.
    });
    return nCacheMax;
}
```

https://en.cppreference.com/w/cpp/thread/call_once

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

File: port/cpl_multiproc.cpp [hunk 1]
```diff
@@ -1462,35 +1462,31 @@ int CPLCreateOrAcquireMutexEx(CPLMutex **phMutex, double dfWaitInSeconds,
...
 
 {
-    bool bSuccess = false;
-
     pthread_mutex_lock(&global_mutex);
     if (*phMutex == nullptr)
     {
         *phMutex = CPLCreateMutexInternal(true, nOptions);
-        bSuccess = *phMutex != nullptr;
+        const bool bSuccess = *phMutex != nullptr;
```
Comment (elpaso) [inline port/cpl_multiproc.cpp:1469]: are the changes in this file related to the TSAN complaint mentioned above?

On a side note, is there chance we can eventually get rid of in-house mutex handling in favor of std:: library methods?

**Review by elpaso — APPROVED** [review]

File: port/cpl_multiproc.cpp (hunk 1 above)
Comment (rouault) [reply port/cpl_multiproc.cpp:1469]: > are the changes in this file related to the TSAN complaint mentioned above?

not directly, I also incorporated that commit from #1108 because a sanitizer that would test this PR would also frown upon that issue

> On a side note, is there chance we can eventually get rid of in-house mutex handling in favor of std:: library methods?

could be a nice cleanup indeed.
