### PR TITLE
OpenFileGDB: fix attribute filter when an equality comparison is involved…

### LINKED ISSUE #10345: ESRI FileGDB Driver 3.9.1 ERROR 1
### What is the bug?

FileGDB Driver 3.9.1 throws "ERROR 1: Cannot find filename for layer ..." errors for some layers only when converting from GPKG to File GDB. The errors appear are misleading as the layers are created successfully in the output File GDB.

### Steps to reproduce the issue

Upgrade File GDB driver from to 3.9.1 under OSGeo4W.

### Versions and provenance

Windows 10
GDAL 3.9.1, released 2024/06/22
OSGeo4W

### Additional context

These errors also occur with 3.8.5, but I don't think they always occurred in earlier versions.

### PR DESCRIPTION
**Pull request by rouault**
… with a field with an index created with a LOWER(field_name) expression

Fixes #10345

### CODE REVIEW

File: ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp [hunk 1]
```diff
@@ -1439,12 +1477,17 @@ bool FileGDBIndexIterator::FindPages(int iLevel, uint64_t nPage)
                        nStrLen * sizeof(GUInt16));
                 for (int j = 0; j < nStrLen; j++)
                     CPL_LSBPTR16(&asMax[j]);
+                    // Note: we have an inconsistency. OGR SQL equality operator
+                    // is advertized top be case insensitive, but we have always
```
Comment (elpaso) [inline ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp:1481]:
```suggestion
                    // is advertized to be case insensitive, but we have always
```

File: ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp [hunk 2]
```diff
@@ -1806,7 +1850,11 @@ int64_t FileGDBIndexIterator::GetNextRow()
                            nStrLen * 2);
                     for (int j = 0; j < nStrLen; j++)
                         CPL_LSBPTR16(&asVal[j]);
-                    nComp = FileGDBUTF16StrCompare(asUTF16Str, asVal, nStrLen);
+                    // Note: we have an inconsistency. OGR SQL equality operator
+                    // is advertized top be case insensitive, but we have always
```
Comment (elpaso) [inline ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp:1854]:
```suggestion
                    // is advertized to be case insensitive, but we have always
```

**Comment by rouault** [comment]
The backport to `release/3.9` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply d60294fcf7... OpenFileGDB: fix attribute filter when an equality comparison is involved with a field with an index created with a LOWER(field_name) expression
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/ogr/ogr_openfilegdb.py
CONFLICT (content): Merge conflict in autotest/ogr/ogr_openfilegdb.py
Auto-merging ogr/ogrsf_frmts/openfilegdb/filegdbindex.cpp
Auto-merging ogr/ogrsf_frmts/openfilegdb/filegdbtable.h
Auto-merging ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.9 release/3.9
# Navigate to the new working tree
cd .worktrees/backport-release/3.9
# Create a new branch
git switch --create backport-10346-to-release/3.9
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick d60294fcf721a9aa934db7e792be63cbc49021be,8ef298f2c1289093dae5da60d2f12a482a405a70
# Push it to GitHub
git push --set-upstream origin backport-10346-to-release/3.9
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.9
```
Then, create a pull request where the `base` branch is `release/3.9` and the `compare`/`head` branch is `backport-10346-to-release/3.9`.

**Comment by rouault** [comment]
backported to 3.9 per https://github.com/OSGeo/gdal/pull/10373
