### PR TITLE
[GML] Support CityGML3 Shell

### LINKED ISSUE #12769: ogrinfo show geometry error - OGC CityGML 3.0
### What is the bug?

I wanted to load CityGML into QGIS. Unfortunately, it doesn't work. @agiudiceandrea gave me the hint about ogrinfo.
Can you helb me?
Issue in QGIS #https://github.com/qgis/QGIS/issues/62621

### Steps to reproduce the issue

ogrinfo

### Versions and provenance

3.10.2 in qgis

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #12769

Also, expose SKIP_RESOLVE_ELEMS as an open option

### CODE REVIEW

File: ogr/ogrsf_frmts/gml/ogrgmldriver.cpp [hunk 1]
```diff
@@ -214,9 +214,14 @@ void RegisterOGRGML()
         "to read schema for imports along with includes or not' default='NO'/>"
         "  <Option name='SKIP_CORRUPTED_FEATURES' type='boolean' "
         "description='Whether to skip features that cannot be parsed instead "
-        "of "
-        "failing' "
-        "default='NO'/>"
+        "of failing' default='NO'/>"
+        "  <Option name='SKIP_RESOLVE_ELEMS' type='string-select' "
```
Comment (rouault) [inline ogr/ogrsf_frmts/gml/ogrgmldriver.cpp]:
```suggestion
        "  <Option name='SKIP_RESOLVE_ELEMS' type='string' "
```

**Review by rouault — APPROVED** [review]

**Comment by elpaso** [comment]
@rouault there is still a failing test on mac but it seems unrelated.
