### PR TITLE
netCDF: fix reading MODIS_ARRAY.nc file that has non CF-compliant way…

### LINKED ISSUE #4075: BUG: Affine missing for netcdf file
From: https://github.com/corteva/rioxarray/issues/371
Input file: https://github.com/corteva/rioxarray/blob/master/test/test_data/input/MODIS_ARRAY.nc?raw=true

Information about dx/dy:
```python
>>> import xarray
>>> rds = xarray.open_dataarray("MODIS_ARRAY.nc")
>>> (rds.x.values[:-1] - rds.x.values[1:]).max()
-231.65635826345533
>>> (rds.x.values[:-1] - rds.x.values[1:]).min()
-231.65635826438665
>>> (rds.y.values[:-1] - rds.y.values[1:]).max()
231.65635826438665
>>> (rds.y.values[:-1] - rds.y.values[1:]).min()
231.65635826345533
```

Most likely culprit: https://github.com/OSGeo/gdal/pull/3753 [commit](https://github.com/OSGeo/gdal/commit/295cc128cf825aa0a66762dcade905b62d46a4e0#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2)

Other potential culprits:
- https://github.com/OSGeo/gdal/commit/7ea0f5d143ae412f0695b2d311006a4e65ba41ff#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2
- https://github.com/OSGeo/gdal/commit/ced20253a7d7d61d3865feba93e020a434bc9617#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2

## Expected behavior and actual behavior.

GDAL version 3.3.0 or previous:
```python
from osgeo import gdal
ds = gdal.Open("MODIS_ARRAY.nc")
ds.GetGeoTransform(can_return_null=True)
```
```
(-7274009.649486291, 231.6563582639561, 0.0, 5050108.61015275, 0.0, -231.65635826375018)
```
GDAL version 3.3.1:
```python
from osgeo import gdal
ds = gdal.Open("MODIS_ARRAY.nc")
ds.GetGeoTransform(can_return_null=True)
```

## Operating system

Ubuntu 20, MacOS, etc.

## GDAL version and provenance

Issue in GDAL version 3.3.1

### PR DESCRIPTION
**Pull request by rouault**
… of expressing axis and CRS (fixes #4075)

### CODE REVIEW

File: gdal/frmts/netcdf/netcdfdataset.cpp [hunk 1]
```diff
@@ -3368,6 +3368,17 @@ void netCDFDataset::SetProjectionFromVar( int nGroupId, int nVarId,
             // oSRS.SetWellKnownGeogCS("WGS84");
         }
     }
+    else
+    {
+        // Dataset from https://github.com/OSGeo/gdal/issues/4075 has a "crs"
```
Comment (snowman2) [inline gdal/frmts/netcdf/netcdfdataset.cpp:3373]: I wouldn't worry about reading in the non CF-compliant CRS information. That isn't something that has worked in the past and is handled by rioxarray: https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html. Definitely want to encourage others to use the CF-compliant version for storing the CRS.

File: gdal/frmts/netcdf/netcdfdataset.cpp [hunk 2]
```diff
@@ -3392,6 +3403,11 @@ void netCDFDataset::SetProjectionFromVar( int nGroupId, int nVarId,
         // variables without same name than dimension using the same resolving
         // logic. This should handle for example NASA Ocean Color L2 products.
 
+        const bool bIgnoreXYAxisNameChecks =
+            CPLTestBool(CPLGetConfigOption("GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS", "NO")) ||
+            // Dataset from https://github.com/OSGeo/gdal/issues/4075 has a res and transform attributes
+            (FetchAttr(nGroupId, nVarId, "res") != nullptr &&
```
Comment (snowman2) [inline gdal/frmts/netcdf/netcdfdataset.cpp:3409]: I wouldn't worry about using the res/transform attributes here either. It hasn't worked in the past and doesn't need to moving forward. That is the way `xarray` currently does it for metadata purposes only and will likely not be used moving forward [ref](https://github.com/pydata/xarray/issues/4697). `rioxarray` uses the method currently supported by GDAL with the `GeoTransform` attribute [ref](https://github.com/corteva/rioxarray/blob/c5203665aa1a7e76e4729df9a80568f999db01dc/rioxarray/rioxarray.py#L494-L496).

File: gdal/frmts/netcdf/netcdfdataset.cpp [hunk 3]
```diff
@@ -3392,6 +3403,11 @@ void netCDFDataset::SetProjectionFromVar( int nGroupId, int nVarId,
         // variables without same name than dimension using the same resolving
         // logic. This should handle for example NASA Ocean Color L2 products.
 
+        const bool bIgnoreXYAxisNameChecks =
+            CPLTestBool(CPLGetConfigOption("GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS", "NO")) ||
```
Comment (snowman2) [inline gdal/frmts/netcdf/netcdfdataset.cpp:3407]: `GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS` will be very helpful for backwards compatibility. Thanks :+1:. Hopefully it won't be needed for datasets moving forward :crossed_fingers:

File: gdal/frmts/netcdf/netcdfdataset.cpp [hunk 4]
```diff
@@ -3419,14 +3440,19 @@ void netCDFDataset::SetProjectionFromVar( int nGroupId, int nVarId,
...
             {
                 if( !NCDFIsVarLatitude(nGroupId, nVarDimYID, nullptr) &&
                     !NCDFIsVarProjectionY(nGroupId, nVarDimYID, nullptr) &&
                     // In case of inversion of X/Y
                     !NCDFIsVarLongitude(nGroupId, nVarDimYID, nullptr) &&
                     !NCDFIsVarProjectionX(nGroupId, nVarDimYID, nullptr) )
                 {
+                    CPLDebug("netCDF",
+                             "Georeferencing ignored due to non-specific "
+                             "enough Y avis name. "
```
Comment (snowman2) [inline gdal/frmts/netcdf/netcdfdataset.cpp:3453]: /s/avis/axis/

File: gdal/frmts/netcdf/netcdfdataset.cpp [hunk 5]
```diff
@@ -3400,14 +3416,19 @@ void netCDFDataset::SetProjectionFromVar( int nGroupId, int nVarId,
...
             {
                 if( !NCDFIsVarLongitude(nGroupId, nVarDimXID, nullptr) &&
                     !NCDFIsVarProjectionX(nGroupId, nVarDimXID, nullptr) &&
                     // In case of inversion of X/Y
                     !NCDFIsVarLatitude(nGroupId, nVarDimXID, nullptr) &&
                     !NCDFIsVarProjectionY(nGroupId, nVarDimXID, nullptr) )
                 {
+                    CPLDebug("netCDF",
+                             "Georeferencing ignored due to non-specific "
+                             "enough X avis name. "
```
Comment (snowman2) [inline gdal/frmts/netcdf/netcdfdataset.cpp:3429]: /s/avis/axis/

**Comment by snowman2** [comment]
Thanks @rouault :+1:

File: gdal/frmts/netcdf/netcdfdataset.cpp (hunk 1 above)
Comment (rouault) [reply gdal/frmts/netcdf/netcdfdataset.cpp:3373]: ok thaks for the info. I'll keep that as it's now coded

Comment (snowman2) [reply gdal/frmts/netcdf/netcdfdataset.cpp:3373]: Okay, I would use fromUserInput then as I have seen some CRS attrs with WKT strings as well.

File: gdal/frmts/netcdf/netcdfdataset.cpp (hunk 2 above)
Comment (snowman2) [reply gdal/frmts/netcdf/netcdfdataset.cpp:3409]: Should also note that it isn't a GDAL transform: http://xarray.pydata.org/en/stable/generated/xarray.open_rasterio.html

Comment (snowman2) [reply gdal/frmts/netcdf/netcdfdataset.cpp:3409]: See the example in the docstring in the link above.

File: gdal/frmts/netcdf/netcdfdataset.cpp (hunk 1 above)
Comment (snowman2) [reply gdal/frmts/netcdf/netcdfdataset.cpp:3373]: Reference: https://github.com/opendatacube/datacube-core/blob/3997b90f7cc1fe909b3e5ee0da395bb07fd969d5/datacube/api/core.py#L514

Comment (snowman2) [reply gdal/frmts/netcdf/netcdfdataset.cpp:3373]: Looks like it could be an EPSG reference as well: https://github.com/opendatacube/datacube-core/blob/3997b90f7cc1fe909b3e5ee0da395bb07fd969d5/datacube/utils/geometry/_base.py#L134
