### PR TITLE
ogr2ogr / PG driver: make ogr2ogr -lco GEOM_TYPE=geography work when …

### LINKED ISSUE #5069: ogr2ogr/PostgreSQL respects layer cration option GEOM_TYPE=geography only when also GEOMETRY_NAME is set
I tried to import a GeoPackage with ogr2ogr into a PostGIS database with geometry type geography. Initially, it looked as the layer creation option `-lco GEOM_TYPE=geography` was ignored. While experimenting, I found that the option is respected when also `-lco GEOMETRY_NAME=geography`  was set.

```
gdalinfo --version
GDAL 3.4.0, released 2021/11/04
```
Steps to reproduce:

docker-compose.yml:
```
version: "3"

services:
  geodb:
    image: postgis/postgis:14-3.1-alpine
    container_name: postgis
    environment:
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: geodb
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - pgdata-geodb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata-geodb: null
``` 
Download https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/geojson/multipolygon.geojson and convert it to GPKG:

`ogr2ogr -f GPKG multipolygon.gpkg multipolygon.geojson`

Start PostGIS in docker container (in the same directory as docker-compose.yml):

`docker-compose up`

**Import data only with `GEOM_TYPE`:**
```
CPL_DEBUG=ON ogr2ogr -f PostgreSQL postgresql://postgis:postgis@localhost:5432/geodb multipolygon.gpkg -lco GEOM_TYPE=geography -a_srs "EPSG:4326" -nln "only_geom_type"
```
The PostGIS table creation command is:
```
CREATE TABLE "public"."only_geom_type" ( "fid" SERIAL, PRIMARY KEY ("fid"), "geom" geometry(MULTIPOLYGON,4326) )
```

<details>

ogr2ogr Output:
```
GPKG: GeoPackage v1.2.0
GDAL: GDALOpen(multipolygon.gpkg, this=0x5608cdfefb60) succeeds as GPKG.
GDAL: GDALDriver::Create(PostgreSQL,postgresql://postgis:postgis@localhost:5432/geodb,0,0,0,Unknown,(nil))
PG: PostGIS schema: 'public'
PG: PostgreSQL version string : 'PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit'
PG: PostGIS version string : '3.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1'
PG: Could not retrieve table oid for only_geom_type
GDALVectorTranslate: Using FID=fid and -preserve_fid
PG: Could not retrieve table oid for only_geom_type
GPKG: ResetStatement(SELECT m."fid", m."geom" FROM "multipolygon" m)
GPKG: finalize 0x5608ce361b60
GDALVectorTranslate: 1 features written in layer 'only_geom_type'
PG: PQputCopyEnd()
GDAL: GDALClose(multipolygon.gpkg, this=0x5608cdfefb60)
GDAL: GDALClose(postgresql://postgis:postgis@localhost:5432/geodb, this=0x5608ce05f6e0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

Postgis logs:
```
postgis  | 2022-01-07 10:23:38.895 UTC [67] LOG:  statement: set client_encoding to 'UNICODE'
postgis  | 2022-01-07 10:23:38.897 UTC [67] LOG:  execute <unnamed>: SELECT n.nspname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE proname = 'postgis_version'
postgis  | 2022-01-07 10:23:38.898 UTC [67] LOG:  execute <unnamed>: SET search_path='',public
postgis  | 2022-01-07 10:23:38.898 UTC [67] LOG:  execute <unnamed>: SELECT version()
postgis  | 2022-01-07 10:23:38.898 UTC [67] LOG:  execute <unnamed>: SHOW standard_conforming_strings
postgis  | 2022-01-07 10:23:38.899 UTC [67] LOG:  execute <unnamed>: SELECT oid, typname FROM pg_type WHERE typname IN ('geometry', 'geography') AND typtype='b'
postgis  | 2022-01-07 10:23:38.907 UTC [67] LOG:  execute <unnamed>: SELECT postgis_version()
postgis  | 2022-01-07 10:23:38.907 UTC [67] LOG:  execute <unnamed>: SET ENABLE_SEQSCAN = ON
postgis  | 2022-01-07 10:23:38.910 UTC [67] LOG:  execute <unnamed>: SELECT 1 FROM information_schema.tables WHERE table_name = 'geometry_columns' LIMIT 1
postgis  | 2022-01-07 10:23:38.911 UTC [67] LOG:  execute <unnamed>: SELECT 1 FROM information_schema.tables WHERE table_name = 'spatial_ref_sys' LIMIT 1
postgis  | 2022-01-07 10:23:38.911 UTC [67] LOG:  execute <unnamed>: SELECT ST_Srid('POINT EMPTY'::GEOMETRY)
postgis  | 2022-01-07 10:23:38.912 UTC [67] LOG:  execute <unnamed>: SELECT current_schema()
postgis  | 2022-01-07 10:23:38.913 UTC [67] LOG:  execute <unnamed>: BEGIN
postgis  | 2022-01-07 10:23:38.914 UTC [67] LOG:  execute <unnamed>: SELECT c.oid FROM pg_class c JOIN pg_namespace n ON c.relnamespace=n.oid WHERE c.relname = 'only_geom_type' AND n.nspname = 'public'
postgis  | 2022-01-07 10:23:38.914 UTC [67] LOG:  execute <unnamed>: SELECT c.oid FROM pg_class c JOIN pg_namespace n ON c.relnamespace=n.oid WHERE c.relname = 'only_geom_type' AND n.nspname = 'public'
postgis  | 2022-01-07 10:23:38.919 UTC [67] LOG:  execute <unnamed>: SELECT c.relname, n.nspname, c.relkind, a.attname, t.typname, postgis_typmod_dims(a.atttypmod) dim, postgis_typmod_srid(a.atttypmod) srid, postgis_typmod_type(a.atttypmod)::text geomtyp, array_agg(pg_get_constraintdef(s.oid))::text att_constraints, a.attnotnull, d.description FROM pg_class c JOIN pg_attribute a ON a.attrelid=c.oid JOIN pg_namespace n ON c.relnamespace = n.oid AND c.relkind in ('r','v','m','f') AND NOT ( n.nspname = 'public' AND c.relname = 'raster_columns' ) JOIN pg_type t ON a.atttypid = t.oid AND (t.typname = 'geometry'::name OR t.typname = 'geography'::name) LEFT JOIN pg_constraint s ON s.connamespace = n.oid AND s.conrelid = c.oid AND a.attnum = ANY (s.conkey) AND (pg_get_constraintdef(s.oid) LIKE '%geometrytype(% = %' OR pg_get_constraintdef(s.oid) LIKE '%ndims(% = %' OR pg_get_constraintdef(s.oid) LIKE '%srid(% = %') LEFT JOIN pg_description d ON d.objoid = c.oid AND d.classoid = 'pg_class'::regclass::oid AND d.objsubid = 0 GROUP BY c.relname, n.nspname, c.relkind, a.attname, t.typname, dim, srid, geomtyp, a.attnotnull, c.oid, a.attnum, d.description ORDER BY c.oid, a.attnum
postgis  | 2022-01-07 10:23:38.926 UTC [67] LOG:  execute <unnamed>: SELECT srid FROM spatial_ref_sys WHERE auth_name = 'EPSG' AND auth_srid = 4326
postgis  | 2022-01-07 10:23:38.937 UTC [67] LOG:  execute <unnamed>: SELECT srid FROM geometry_columns WHERE f_table_name = 'only_geom_type' AND f_geometry_column = 'geom' AND f_table_schema = 'public'
postgis  | 2022-01-07 10:23:38.938 UTC [67] LOG:  execute <unnamed>: SELECT srid FROM spatial_ref_sys WHERE auth_name = 'EPSG' AND auth_srid = 4326
postgis  | 2022-01-07 10:23:38.939 UTC [67] LOG:  execute <unnamed>: CREATE TABLE "public"."only_geom_type" ( "fid" SERIAL, PRIMARY KEY ("fid"), "geom" geometry(MULTIPOLYGON,4326) )
postgis  | 2022-01-07 10:23:38.955 UTC [67] LOG:  execute <unnamed>: CREATE INDEX "only_geom_type_geom_geom_idx" ON "only_geom_type" USING GIST ("geom")
postgis  | 2022-01-07 10:23:38.956 UTC [67] LOG:  execute <unnamed>: COPY "only_geom_type" ("geom", "fid") FROM STDIN;
postgis  | 2022-01-07 10:23:38.957 UTC [67] LOG:  execute <unnamed>: SELECT setval(pg_get_serial_sequence('"only_geom_type"', 'fid'), MAX("fid")) FROM "only_geom_type"
postgis  | 2022-01-07 10:23:38.957 UTC [67] LOG:  execute <unnamed>: COMMIT
```

</details>

**Import data with `GEOM_TYPE` and `GEOMETRY_NAME`:**
```
CPL_DEBUG=ON ogr2ogr -f PostgreSQL postgresql://postgis:postgis@localhost:5432/geodb multipolygon.gpkg -lco GEOMETRY_NAME=geography -lco GEOM_TYPE=geography -a_srs "EPSG:4326" -nln "geom_type_and_geometry_name"
```

The PostGIS table creation command is:
```
CREATE TABLE "public"."geom_type_and_geometry_name" ( "fid" SERIAL, PRIMARY KEY ("fid"), "geography" geography(MULTIPOLYGON,4326) )
```

<details>

ogr2ogr log:
```
GPKG: GeoPackage v1.2.0
GDAL: GDALOpen(multipolygon.gpkg, this=0x55841f75dc30) succeeds as GPKG.
GDAL: GDALDriver::Create(PostgreSQL,postgresql://postgis:postgis@localhost:5432/geodb,0,0,0,Unknown,(nil))
PG: PostGIS schema: 'public'
PG: PostgreSQL version string : 'PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit'
PG: PostGIS version string : '3.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1'
PG: Could not retrieve table oid for geom_type_and_geometry_name
GDALVectorTranslate: Using FID=fid and -preserve_fid
PG: Could not retrieve table oid for geom_type_and_geometry_name
GPKG: ResetStatement(SELECT m."fid", m."geom" FROM "multipolygon" m)
GPKG: finalize 0x55841facfd30
GDALVectorTranslate: 1 features written in layer 'geom_type_and_geometry_name'
PG: PQputCopyEnd()
GDAL: GDALClose(multipolygon.gpkg, this=0x55841f75dc30)
GDAL: GDALClose(postgresql://postgis:postgis@localhost:5432/geodb, this=0x55841f7cd7e0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

Postgis log:
```
postgis  | 2022-01-07 10:25:44.682 UTC [75] LOG:  statement: set client_encoding to 'UNICODE'
postgis  | 2022-01-07 10:25:44.683 UTC [75] LOG:  execute <unnamed>: SELECT n.nspname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE proname = 'postgis_version'
postgis  | 2022-01-07 10:25:44.684 UTC [75] LOG:  execute <unnamed>: SET search_path='',public
postgis  | 2022-01-07 10:25:44.684 UTC [75] LOG:  execute <unnamed>: SELECT version()
postgis  | 2022-01-07 10:25:44.684 UTC [75] LOG:  execute <unnamed>: SHOW standard_conforming_strings
postgis  | 2022-01-07 10:25:44.685 UTC [75] LOG:  execute <unnamed>: SELECT oid, typname FROM pg_type WHERE typname IN ('geometry', 'geography') AND typtype='b'
postgis  | 2022-01-07 10:25:44.691 UTC [75] LOG:  execute <unnamed>: SELECT postgis_version()
postgis  | 2022-01-07 10:25:44.691 UTC [75] LOG:  execute <unnamed>: SET ENABLE_SEQSCAN = ON
postgis  | 2022-01-07 10:25:44.694 UTC [75] LOG:  execute <unnamed>: SELECT 1 FROM information_schema.tables WHERE table_name = 'geometry_columns' LIMIT 1
postgis  | 2022-01-07 10:25:44.695 UTC [75] LOG:  execute <unnamed>: SELECT 1 FROM information_schema.tables WHERE table_name = 'spatial_ref_sys' LIMIT 1
postgis  | 2022-01-07 10:25:44.695 UTC [75] LOG:  execute <unnamed>: SELECT ST_Srid('POINT EMPTY'::GEOMETRY)
postgis  | 2022-01-07 10:25:44.696 UTC [75] LOG:  execute <unnamed>: SELECT current_schema()
postgis  | 2022-01-07 10:25:44.697 UTC [75] LOG:  execute <unnamed>: BEGIN
postgis  | 2022-01-07 10:25:44.698 UTC [75] LOG:  execute <unnamed>: SELECT c.oid FROM pg_class c JOIN pg_namespace n ON c.relnamespace=n.oid WHERE c.relname = 'geom_type_and_geometry_name' AND n.nspname = 'public'
postgis  | 2022-01-07 10:25:44.698 UTC [75] LOG:  execute <unnamed>: SELECT c.oid FROM pg_class c JOIN pg_namespace n ON c.relnamespace=n.oid WHERE c.relname = 'geom_type_and_geometry_name' AND n.nspname = 'public'
postgis  | 2022-01-07 10:25:44.702 UTC [75] LOG:  execute <unnamed>: SELECT c.relname, n.nspname, c.relkind, a.attname, t.typname, postgis_typmod_dims(a.atttypmod) dim, postgis_typmod_srid(a.atttypmod) srid, postgis_typmod_type(a.atttypmod)::text geomtyp, array_agg(pg_get_constraintdef(s.oid))::text att_constraints, a.attnotnull, d.description FROM pg_class c JOIN pg_attribute a ON a.attrelid=c.oid JOIN pg_namespace n ON c.relnamespace = n.oid AND c.relkind in ('r','v','m','f') AND NOT ( n.nspname = 'public' AND c.relname = 'raster_columns' ) JOIN pg_type t ON a.atttypid = t.oid AND (t.typname = 'geometry'::name OR t.typname = 'geography'::name) LEFT JOIN pg_constraint s ON s.connamespace = n.oid AND s.conrelid = c.oid AND a.attnum = ANY (s.conkey) AND (pg_get_constraintdef(s.oid) LIKE '%geometrytype(% = %' OR pg_get_constraintdef(s.oid) LIKE '%ndims(% = %' OR pg_get_constraintdef(s.oid) LIKE '%srid(% = %') LEFT JOIN pg_description d ON d.objoid = c.oid AND d.classoid = 'pg_class'::regclass::oid AND d.objsubid = 0 GROUP BY c.relname, n.nspname, c.relkind, a.attname, t.typname, dim, srid, geomtyp, a.attnotnull, c.oid, a.attnum, d.description ORDER BY c.oid, a.attnum
postgis  | 2022-01-07 10:25:44.709 UTC [75] LOG:  execute <unnamed>: SELECT srid FROM spatial_ref_sys WHERE auth_name = 'EPSG' AND auth_srid = 4326
postgis  | 2022-01-07 10:25:44.713 UTC [75] LOG:  execute <unnamed>: SELECT srtext, auth_name, auth_srid FROM spatial_ref_sys WHERE srid = 4326
postgis  | 2022-01-07 10:25:44.713 UTC [75] LOG:  execute <unnamed>: CREATE TABLE "public"."geom_type_and_geometry_name" ( "fid" SERIAL, PRIMARY KEY ("fid"), "geography" geography(MULTIPOLYGON,4326) )
postgis  | 2022-01-07 10:25:44.734 UTC [75] LOG:  execute <unnamed>: CREATE INDEX "geom_type_and_geometry_name_geography_geom_idx" ON "geom_type_and_geometry_name" USING GIST ("geography")
postgis  | 2022-01-07 10:25:44.736 UTC [75] LOG:  execute <unnamed>: COPY "geom_type_and_geometry_name" ("geography", "fid") FROM STDIN;
postgis  | 2022-01-07 10:25:44.737 UTC [75] LOG:  execute <unnamed>: SELECT setval(pg_get_serial_sequence('"geom_type_and_geometry_name"', 'fid'), MAX("fid")) FROM "geom_type_and_geometry_name"
postgis  | 2022-01-07 10:25:44.737 UTC [75] LOG:  execute <unnamed>: COMMIT
```

</details>

### PR DESCRIPTION
**Pull request by rouault**
…the source layer has a named geometry column, and also reject creating geography columns with a SRS != EPSG:4326 (fixes #5069)

### CODE REVIEW

File: ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp [hunk 1]
```diff
@@ -1817,6 +1817,17 @@ OGRPGDataSource::ICreateLayer( const char * pszLayerName,
     if( poSRS != nullptr )
         nSRSId = FetchSRSId( poSRS );
 
+    if( eType != wkbNone && EQUAL(pszGeomType, "geography") &&
+        nSRSId != nUndefinedSRID && nSRSId != 4326 )
```
Comment (rbuffat) [inline ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp:1821]: See https://github.com/OSGeo/gdal/issues/5069#issuecomment-1008154717
