### PR TITLE
Fix issue with gdal_viewshed with gcc 9.4 in debug mode (master only)

### LINKED ISSUE #10825: CPLWorkerThreadPool: regression in master
@abellgithub I believe this is related to your recent changes

``pytest autotest/utilities/test_gdal_viewshed.py --capture=no -ra -vv --capture=no -ra -vv`` on a *debug* build randomly stall or crashes for me, with traces like:

```
gdal_viewshed_path = '/home/even/gdal/gdal/build_cmake/apps/gdal_viewshed', tmp_path = PosixPath('/tmp/pytest-of-even/pytest-648/test_gdal_viewshed0')
viewshed_input = '/tmp/pytest-of-even/pytest-648/test_gdal_viewshed0/test_gdal_viewshed_in.tif'

    def test_gdal_viewshed(gdal_viewshed_path, tmp_path, viewshed_input):
    
        viewshed_out = str(tmp_path / "test_gdal_viewshed_out.tif")
    
        _, err = gdaltest.runexternal_out_and_err(
            gdal_viewshed_path
            + " -oz {} -ox {} -oy {} {} {}".format(
                oz[0], ox[0], oy[0], viewshed_input, viewshed_out
            )
        )
>       assert err is None or err == ""
E       assert ("ERROR 7: Assertion `psWorkerThread->bMarkedAsWaiting' failed in file `/home/even/gdal/gdal/port/cpl_worker_thread_pool.cpp', line 218\n\nERROR ret code = -6" is None or "ERROR 7: Assertion `psWorkerThread->bMarkedAsWaiting' failed in file `/home/even/gdal/gdal/port/cpl_worker_thread_pool.cpp', line 218\n\nERROR ret code = -6" == ''
E         + ERROR 7: Assertion `psWorkerThread->bMarkedAsWaiting' failed in file `/home/even/gdal/gdal/port/cpl_worker_thread_pool.cpp', line 218
E         + 
E         + ERROR ret code = -6)

```

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10825

### CODE REVIEW

File: alg/viewshed/viewshed.h [hunk 1]
```diff
@@ -83,10 +81,10 @@ class Viewshed
 
   private:
     Options oOpts;
-    Window oOutExtent;
-    Window oCurExtent;
-    DatasetPtr poDstDS;
-    GDALRasterBand *pSrcBand;
+    Window oOutExtent{};
```
Comment (elpaso) [inline alg/viewshed/viewshed.h:84]: I'm curious: what changes here? Isn't the default ctor called in both cases?

**Review by elpaso — APPROVED** [review]

File: alg/viewshed/viewshed.h (hunk 1 above)
Comment (rouault) [reply alg/viewshed/viewshed.h:84]: The help please -Weffc++ given that the constructor no longer explicitly initialize those members.
