### PR TITLE
gdal dataset copy/rename: make it work with vector datasets, and directories

### LINKED ISSUE #14097: `gdal dataset cp` not working on ESRI Shapefile
### What is the bug?

`gdal dataset cp` doesn't seem to work on ESRI Shapefiles.

### Steps to reproduce the issue

This works
```console
$ gdal vector info geonb_provinciallimits-limitesprovinciales_shp
```

This removes all the relevant auxiliary files corresponding to the dataset except the .shp.xml file
```console
$ gdal dataset rm geonb_provinciallimits-limitesprovinciales_shp
```

However, below two commands doesn't work and throws the error
```console
$ gdal dataset cp geonb_provinciallimits-limitesprovinciales_shp nb_outline
ERROR 1: No identifiable driver for geonb_provinciallimits-limitesprovinciales_shp
```

```console
$ gdal dataset cp geonb_provinciallimits-limitesprovinciales_shp\geonb_provinciallimits-limitesprovinciales.shp nb_outline.shp
ERROR 1: No identifiable driver for geonb_provinciallimits-limitesprovinciales_shp\geonb_provinciallimits-limitesprovinciales.shp.
```

The expected behavior is to create a folder titled `nb_outline` with all the relevant files copied (1st case) and `nb_outline.shp` with all the relevant files copied (2nd case)

[geonb_provinciallimits-limitesprovinciales_shp.zip](https://github.com/user-attachments/files/25857718/geonb_provinciallimits-limitesprovinciales_shp.zip)

### Versions and provenance

- Operating system: `Windows 11 Pro`
- GDAL version: `GDAL 3.12.2 "Chicoutimi", released 2026/02/03`
- Installed `gdal` using `pixi global install gdal`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #14097

### CODE REVIEW

File: gcore/gdaldriver.cpp [hunk 1]
```diff
@@ -1835,31 +1837,43 @@ CPLErr GDALDriver::DefaultRename(const char *pszNewName, const char *pszOldName)
...
+
+    for (int i = 0; i < aosFileList.size(); ++i)
+    {
+        if (CPLMoveFile(aosNewFileList[i], aosFileList[i]) != 0)
         {
             eErr = CE_Failure;
             // Try to put the ones we moved back.
             for (--i; i >= 0; i--)
             {
                 // Nothing we can do if the moving back doesn't work...
```
Comment (elpaso) [inline gcore/gdaldriver.cpp:1870]: is there any warning to the user if this happens?

File: gcore/gdaldriver.cpp [hunk 2]
```diff
@@ -1970,27 +1985,39 @@ CPLErr GDALDriver::DefaultCopyFiles(const char *pszNewName,
...
+
+    for (int i = 0; i < aosFileList.size(); ++i)
+    {
+        if (CPLCopyFile(aosNewFileList[i], aosFileList[i]) != 0)
         {
             eErr = CE_Failure;
             // Try to put the ones we moved back.
             for (--i; i >= 0; --i)
-                VSIUnlink(papszNewFileList[i]);
+                VSIUnlink(aosNewFileList[i]);
```
Comment (elpaso) [inline gcore/gdaldriver.cpp]: same concern as before about the broken status

**Review by elpaso — APPROVED** [review]

File: gcore/gdaldriver.cpp (hunk 1 above)
Comment (rouault) [reply gcore/gdaldriver.cpp:1870]: additoinal warning emitted in CPLMoveFile()

File: gcore/gdaldriver.cpp (hunk 2 above)
Comment (rouault) [reply gcore/gdaldriver.cpp]: additional warning emitted if VSIUnlink() fails
