### PR TITLE
ogr2ogr/Parquet: add hack to avoid super lengthy processing when using -limit with a Parquet dataset source (workarounds/fixes #9497)

### LINKED ISSUE #9497: ogr2ogr hangs reading from remote GeoParquet datasets
### What is the bug?

ogr2ogr appears to hang when reading from a remote GeoParquet dataset and stops mid-way through writing out a few features. I'm using the recent Overture Maps buildings dataset.

`ogr2ogr --config AWS_NO_SIGN_REQUEST yes -f GeoJSONSeq out.geojsonseq -limit 10 /vsis3/overturemaps-us-west-2/release/2024-03-12-alpha.0/theme=buildings/type=building`

```
{ "type": "Feature", "properties": { "id": "08bf2a40219b0fff0200c394dae731bd", "bbox.minx": -167.4001236, "bbox.maxx": -167.3998506, "bbox.miny": -83.6500139, "bbox.maxy": -83.6499838, "version": 0, "update_time": "2015-02-01T01:46:06.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w325830447@3", "confidence": null } ], "names.primary": "Marlene Weather Station", "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -167.3999539, -83.6500135 ], [ -167.3999133, -83.6500116 ], [ -167.3998804, -83.6500083 ], [ -167.3998582, -83.6500038 ], [ -167.3998506, -83.6499988 ], [ -167.3998584, -83.6499938 ], [ -167.3998807, -83.6499893 ], [ -167.3999152, -83.6499859 ], [ -167.3999577, -83.649984 ], [ -167.4000037, -83.6499838 ], [ -167.4000478, -83.6499852 ], [ -167.4000852, -83.6499882 ], [ -167.4001108, -83.6499922 ], [ -167.4001236, -83.6499969 ], [ -167.4001221, -83.6500018 ], [ -167.4001066, -83.6500064 ], [ -167.4000786, -83.6500102 ], [ -167.4000412, -83.6500128 ], [ -167.3999981, -83.6500139 ], [ -167.3999539, -83.6500135 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a05afff0200e90ab3b011fa", "bbox.minx": -136.8030749, "bbox.maxx": -136.801886, "bbox.miny": -74.7671777, "bbox.maxy": -74.7669439, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098696@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.8028948, -74.7669439 ], [ -136.8030749, -74.7670273 ], [ -136.8020661, -74.7671777 ], [ -136.801886, -74.7670942 ], [ -136.8028948, -74.7669439 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a058fff020009945ce09d65", "bbox.minx": -136.8033409, "bbox.maxx": -136.8023483, "bbox.miny": -74.7668605, "bbox.maxy": -74.766657, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098698@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.8033409, -74.7667304 ], [ -136.802516, -74.7668605 ], [ -136.8023483, -74.7667871 ], [ -136.8031732, -74.766657 ], [ -136.8033409, -74.7667304 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a04efff02006264a736fc56", "bbox.minx": -136.8031471, "bbox.maxx": -136.8025614, "bbox.miny": -74.7660076, "bbox.maxy": -74.7659004, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098694@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.8030898, -74.7660076 ], [ -136.8025614, -74.7659821 ], [ -136.8026186, -74.7659004 ], [ -136.8031471, -74.765926 ], [ -136.8030898, -74.7660076 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a04afff0200cf5e511a3f1b", "bbox.minx": -136.8023377, "bbox.maxx": -136.8014847, "bbox.miny": -74.7661436, "bbox.maxy": -74.765933, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098695@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.8020881, -74.7661436 ], [ -136.8014847, -74.7660121 ], [ -136.8017343, -74.765933 ], [ -136.8023377, -74.7660645 ], [ -136.8020881, -74.7661436 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a3b4fff0200ab8cfb0881ed", "bbox.minx": -136.8020028, "bbox.maxx": -136.801468, "bbox.miny": -74.7675212, "bbox.maxy": -74.7673884, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098699@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.801468, -74.7674725 ], [ -136.8016254, -74.7673884 ], [ -136.8020028, -74.7674372 ], [ -136.8018454, -74.7675212 ], [ -136.801468, -74.7674725 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a3b4fff020059677fb61838", "bbox.minx": -136.8011347, "bbox.maxx": -136.8007651, "bbox.miny": -74.7673467, "bbox.maxy": -74.7672867, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098693@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.8011347, -74.7673392 ], [ -136.8007811, -74.7673467 ], [ -136.8007651, -74.7672942 ], [ -136.8011187, -74.7672867 ], [ -136.8011347, -74.7673392 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bf35ad6a3a4fff0200da1e7cc23633", "bbox.minx": -136.8006861, "bbox.maxx": -136.8001265, "bbox.miny": -74.7663307, "bbox.maxy": -74.7662395, "version": 0, "update_time": "2024-02-14T01:23:09.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w1250098697@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -136.8001265, -74.7662846 ], [ -136.8006258, -74.7662395 ], [ -136.8006861, -74.7662855 ], [ -136.8001868, -74.7663307 ], [ -136.8001265, -74.7662846 ] ] ] } }
{ "type": "Feature", "properties": { "id": "08bd46b2c6d9cfff0200cc59c05498b8", "bbox.minx": -176.2033171, "bbox.maxx": -176.2031859, "bbox.miny": -44.3188709, "bbox.maxy": -44.3187666, "version": 0, "update_time": "2017-08-27T22:52:43.000Z", "sources": [ { "property": "", "dataset": "OpenStreetMap", "record_id": "w519176553@1", "confidence": null } ], "names.primary": null, "class": null, "level": null, "has_parts": false, "height": null, "num_floors": null, "facade_color": null, "facade_material": null, "roof_material": null, "roof_shape": null, "roof_direction": null, "roof_orientation": null, "roof_color": null, "eave_height": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -176.2032603, -44.3187666 ], [ -176.2033171, -44.3187949 ], [ -176.2032887, -44.3188241 ], [ -176.2033055, -44.3188324 ], [ -176.20
```
The last feature - which is only the 9th feature - is only partially written before things hang.

### Steps to reproduce the issue

`ogr2ogr --config AWS_NO_SIGN_REQUEST yes -f GeoJSONSeq out.geojsonseq -limit 10 /vsis3/overturemaps-us-west-2/release/2024-03-12-alpha.0/theme=buildings/type=building`

Other things I tried:
Reading from a specific file completes fine:
`ogr2ogr --config AWS_NO_SIGN_REQUEST yes -f GeoJSONSeq out.geojsonseq -limit 10 /vsis3/overturemaps-us-west-2/release/2024-03-12-alpha.0/theme=buildings/type=building/part-00231-4dfc75cd-2680-4d52-b5e0-f4cc9f36b267-c000.zstd.parquet`

I also downloaded a few files and placed them in a local directory and everything seemed fine.:
`ogr2ogr --config AWS_NO_SIGN_REQUEST yes -f GeoJSONSeq out.geojsonseq -limit 10 type=building/`

### Versions and provenance

I'm using the docker image from `ghcr.io/osgeo/gdal:alpine-small-3.8.4` and running all the above commands using
`docker run ghcr.io/osgeo/gdal ogr2ogr` in case that changes things.

```
$ docker run ghcr.io/osgeo/gdal ogr2ogr --version
GDAL 3.9.0dev-24e151d1cb6281973714207afbbce3a59719fa6f, released 2024/02/05
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes https://github.com/OSGeo/gdal/issues/9497

### CODE REVIEW

File: ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp [hunk 1]
```diff
@@ -254,8 +255,50 @@ static GDALDataset *OpenFromDatasetFactory(
     const bool bIsVSI = STARTS_WITH(osBasePath.c_str(), "/vsi");
     if (bIsVSI)
     {
-        PARQUET_THROW_NOT_OK(scannerBuilder->FragmentReadahead(2));
-        // scannerBuilder->BatchSize(10);
+        const int nFragmentReadAhead =
```
Comment (elpaso) [inline ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp:258]: are these changes related to the bugfix?

Comment (rouault) [reply ogr/ogrsf_frmts/parquet/ogrparquetdriver.cpp:258]: not directly. Various tunables I tried (unsuccessfully) to diagnose things. The bugfix itself is the last commit.

**Review by elpaso — APPROVED** [review]
