### PR TITLE
JP2OpenJPEG: use GetSiblingFiles()

### LINKED ISSUE #10360: `GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR` does nothing for JP2OpenJPEG
### What is the bug?

`GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR` has no effect on the JP2OpenJPEG driver, and it tries to open too many files.

### Steps to reproduce the issue

```bash
# 14 extra syscalls
$ strace -e trace=%file gdalinfo T35TMK_20230430T090559_B06_20m.jp2 2>&1 | grep ENOENT | grep 20m
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux.xml", 0x7ffdd2fcc760, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.ovr", 0x7ffdd2fcc840, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.OVR", 0x7ffdd2fcc840, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.msk", 0x7ffdd2fcc8d0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.MSK", 0x7ffdd2fcc8d0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux.xml", 0x7ffdd2fccc40, 0) = -1 ENOENT (No such file or directory)

# 14 extra syscalls
$ GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR strace -e trace=%file gdalinfo T35TMK_20230430T090559_B06_20m.jp2 2>&1 | grep ENOENT | grep 20m
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux.xml", 0x7ffc22df84b0, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.ovr", 0x7ffc22df8590, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.OVR", 0x7ffc22df8590, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.msk", 0x7ffc22df8620, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.MSK", 0x7ffc22df8620, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux.xml", 0x7ffc22df8990, 0) = -1 ENOENT (No such file or directory)

# 8 extra syscalls
$ GDAL_PAM_ENABLED=NO GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR strace -e trace=%file gdalinfo T35TMK_20230430T090559_B06_20m.jp2 2>&1 | grep ENOENT | grep 20m
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.ovr", 0x7ffce1f87230, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.OVR", 0x7ffce1f87230, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.aux", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.AUX", O_RDONLY) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.msk", 0x7ffce1f872c0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "T35TMK_20230430T090559_B06_20m.jp2.MSK", 0x7ffce1f872c0, 0) = -1 ENOENT (No such file or directory)

# huh, 0?
$ strace -e trace=%file gdalinfo x_20m.tif 2>&1 | grep ENOENT | grep 20m

# well, still 0
$ GDAL_PAM_ENABLED=NO GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR strace -e trace=%file gdalinfo x_20m.tif 2>&1 | grep ENOENT | grep 20m
```

### Versions and provenance

`ghcr.io/osgeo/gdal:ubuntu-full-3.9.1`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10360

and other similar related changes in other drivers

### CODE REVIEW

File: gcore/gdalopeninfo.cpp [hunk 1]
```diff
@@ -404,7 +404,12 @@ GDALOpenInfo::~GDALOpenInfo()
 /************************************************************************/
 
 /** Return sibling files.
- * @return sibling files. Ownership below to the object.
+ *
+ * If the list of sibling files has not already been established, it will be,
+ * unless the GDAL_DISABLE_READDIR_ON_OPEN configuration option has been set to
+ * YES or EMPTY_DIR when this instance was constructed.
+ *
+ * @return sibling files. Ownership belong to the object.
```
Comment (elpaso) [inline gcore/gdalopeninfo.cpp:412]: To which object? The caller or `this` (I assume the second but maybe clearer to mention ownership wasn't "transfered") ?

**Review by elpaso — APPROVED** [review]

File: gcore/gdalopeninfo.cpp (hunk 1 above)
Comment (rouault) [reply gcore/gdalopeninfo.cpp]: to "this". Comment clarified to reflect ... this :-)
