### PR TITLE
STACIT: STAC 1.1 support

### LINKED ISSUE #11753: STACIT driver does not correctly support STAC 1.1
### What is the bug?

The STACIT driver does not correctly support the new STAC specs v1.1. While I believe it already is aware of the new raster extension, it still is looking for the `proj:epsg` field which has been removed and replaced by `proj:code`.
 

### Steps to reproduce the issue

Stac 1.1 doesn't work
```bash
gdalinfo 'STACIT:"/vsicurl/https://raw.githubusercontent.com/radiantearth/stac-spec/refs/tags/v1.1.0/examples/extended-item.json":asset=analytic'
```

Stac 1.0 works
```bash
gdalinfo 'STACIT:"/vsicurl/https://raw.githubusercontent.com/radiantearth/stac-spec/refs/tags/v1.0.0/examples/extended-item.json":asset=analytic'
```

### Versions and provenance

GDAL 3.10.0, released 2024/11/01
Linux Ubuntu 22.04

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #11753

### CODE REVIEW

**Comment by m-mohr** [comment]
Thanks @rouault 

It might be worth considering https://github.com/OSGeo/gdal/pull/10773/files#r1756556144

**Comment by thomas-maschler** [comment]
Will this still be backwards compatible and also support stac 1.0?

File: frmts/stacit/stacitdataset.cpp [hunk 1]
```diff
@@ -218,34 +227,43 @@ static void ParseAsset(const CPLJSONObject &jAsset,
...
     {
-        osProjUserString = "EPSG:" + oProjEPSG.ToString();
+        osProjUserString = oProjCode.ToString();
     }
     else
     {
-        auto oProjWKT2 = GetAssetOrFeatureProperty("proj:wkt2");
-        if (oProjWKT2.IsValid() &&
-            oProjWKT2.GetType() == CPLJSONObject::Type::String)
+        auto oProjEPSG = GetAssetOrFeatureProperty("proj:epsg");
```
Comment (elpaso) [inline frmts/stacit/stacitdataset.cpp:238]: can it be const?
(other `autos` below as well)

**Review by elpaso — APPROVED** [review]

**Comment by rouault** [comment]
> Will this still be backwards compatible and also support stac 1.0?

it should. Existing tests still pass

File: frmts/stacit/stacitdataset.cpp (hunk 1 above)
Comment (rouault) [reply frmts/stacit/stacitdataset.cpp]: yes, fixed.
